/* QNA CHINESE 主題課程 · 內容資料檔
   全部原創，與當代中文／時代華語／實用中文讀寫無關。
   越南文為初稿，待 Quinn 校對。音檔一律由 Quinn 錄製，不使用 AI 語音。 */
var TC=[
{
id:"intro",unit:"交友與日常聊天",no:1,
title:"第一次見面怎麼介紹自己？",viTitle:"Lần đầu gặp mặt, giới thiệu bản thân thế nào?",
task:{zh:"學完這一課，你可以在第一次見面時介紹自己：說出名字、國籍、工作或身分，說明來臺灣多久了，並且把同樣的問題問回去。",
vi:"Học xong bài này, bạn có thể tự giới thiệu khi gặp lần đầu: nói tên, quốc tịch, công việc, đã ở Đài Loan bao lâu, và hỏi ngược lại đối phương."},
warmup:["你來臺灣多久了？","第一次見面，你通常會先說什麼？","在越南，第一次見面可以問對方的年齡嗎？在臺灣呢？","你希望別人怎麼稱呼你？"],
media:"兩個人在語言中心走廊初次見面、交換聯絡方式的照片。",
dialog:[
{who:"阿明",zh:"你好，我叫陳文明，你可以叫我阿明。",py:"Nǐ hǎo, wǒ jiào Chén Wénmíng, nǐ kěyǐ jiào wǒ Ā-Míng.",vi:"Xin chào, tôi tên là Trần Văn Minh, bạn có thể gọi tôi là A Minh."},
{who:"小美",zh:"你好，我是阮氏梅，大家都叫我小美。",py:"Nǐ hǎo, wǒ shì Ruǎn Shì Méi, dàjiā dōu jiào wǒ Xiǎo-Měi.",vi:"Xin chào, tôi là Nguyễn Thị Mai, mọi người đều gọi tôi là Tiểu Mai."},
{who:"阿明",zh:"小美，你是越南人嗎？",py:"Xiǎo-Měi, nǐ shì Yuènán rén ma?",vi:"Tiểu Mai, bạn là người Việt Nam phải không?"},
{who:"小美",zh:"對，我是越南人，從河內來的。你呢？",py:"Duì, wǒ shì Yuènán rén, cóng Hénèi lái de. Nǐ ne?",vi:"Đúng vậy, tôi là người Việt Nam, đến từ Hà Nội. Còn bạn?"},
{who:"阿明",zh:"我是臺灣人，臺中人。你來臺灣多久了？",py:"Wǒ shì Táiwān rén, Táizhōng rén. Nǐ lái Táiwān duōjiǔ le?",vi:"Tôi là người Đài Loan, người Đài Trung. Bạn đến Đài Loan bao lâu rồi?"},
{who:"小美",zh:"差不多一年了。",py:"Chàbùduō yì nián le.",vi:"Khoảng một năm rồi."},
{who:"阿明",zh:"你在這裡做什麼？",py:"Nǐ zài zhèlǐ zuò shénme?",vi:"Bạn làm gì ở đây?"},
{who:"小美",zh:"我在一家貿易公司上班，做業務。你呢？",py:"Wǒ zài yì jiā màoyì gōngsī shàngbān, zuò yèwù. Nǐ ne?",vi:"Tôi làm ở một công ty thương mại, làm kinh doanh. Còn bạn?"},
{who:"阿明",zh:"我是研究生，念資訊工程。",py:"Wǒ shì yánjiūshēng, niàn zīxùn gōngchéng.",vi:"Tôi là học viên cao học, học ngành công nghệ thông tin."},
{who:"小美",zh:"很高興認識你。",py:"Hěn gāoxìng rènshi nǐ.",vi:"Rất vui được làm quen với bạn."},
{who:"阿明",zh:"我也是。以後多聯絡！",py:"Wǒ yě shì. Yǐhòu duō liánluò!",vi:"Tôi cũng vậy. Sau này liên lạc nhiều nhé!"}],
keys:[
{zh:"我叫……，你可以叫我……",vi:"Tôi tên là…, bạn có thể gọi tôi là…"},
{zh:"我是……人，從……來的。",vi:"Tôi là người…, đến từ…"},
{zh:"你來臺灣多久了？",vi:"Bạn đến Đài Loan bao lâu rồi?"},
{zh:"差不多……了。",vi:"Khoảng… rồi."},
{zh:"我在……上班。",vi:"Tôi làm việc ở…"},
{zh:"很高興認識你。",vi:"Rất vui được làm quen với bạn."},
{zh:"以後多聯絡！",vi:"Sau này liên lạc nhiều nhé!"}],
vocab:[
{w:"介紹",py:"jièshào",vi:"giới thiệu",ex:"我來介紹一下我自己。"},
{w:"自我介紹",py:"zìwǒ jièshào",vi:"tự giới thiệu",ex:"請你做一個簡單的自我介紹。"},
{w:"國籍",py:"guójí",vi:"quốc tịch",ex:"表格上要填國籍。"},
{w:"從……來的",py:"cóng…lái de",vi:"đến từ…",ex:"我是從河內來的。"},
{w:"多久",py:"duōjiǔ",vi:"bao lâu",ex:"你學中文多久了？"},
{w:"差不多",py:"chàbùduō",vi:"khoảng, gần như",ex:"差不多兩年了。"},
{w:"上班",py:"shàngbān",vi:"đi làm",ex:"我每天九點上班。"},
{w:"公司",py:"gōngsī",vi:"công ty",ex:"這家公司在臺北。"},
{w:"業務",py:"yèwù",vi:"kinh doanh, sales",ex:"他做業務，常常出差。"},
{w:"研究生",py:"yánjiūshēng",vi:"học viên cao học",ex:"我是研究生，明年畢業。"},
{w:"認識",py:"rènshi",vi:"làm quen, biết",ex:"很高興認識你。"},
{w:"聯絡",py:"liánluò",vi:"liên lạc",ex:"我們用 LINE 聯絡吧。"}],
vocabNote:"越南學生常被問到「你叫什麼名字」，中文姓名的順序和越南一樣是姓在前，可以提醒學生說出「你可以叫我……」讓對方好稱呼。",
grammar:{pattern:"……，你呢？",note:"把剛剛被問的問題原樣丟回去，是最省力也最自然的接話方式。",
vi:"Dùng để hỏi ngược lại cùng một câu hỏi vừa được hỏi.",
ex:["我是越南人，你呢？","我來一年了，你呢？","我在貿易公司上班，你呢？","我喜歡吃辣的，你呢？"],
swap:"＿＿＿，你呢？（換成：我住在臺北／我念中文／我週末都在家）"},
listening:[
{t:"聽對話選圖片",d:"播放三段自我介紹，學生從照片中選出對應的人（國籍、身分不同）。"},
{t:"聽內容選答案",d:"小美來臺灣多久了？(A) 半年 (B) 一年 (C) 兩年 (D) 三年"},
{t:"聽完填表",d:"填寫：名字＿＿＿／國籍＿＿＿／工作或身分＿＿＿／來臺時間＿＿＿"},
{t:"判斷聽錯沒有",d:"對方說「我從河內來的」，另一個人回「喔，你是胡志明市人」——哪裡錯了？該怎麼糾正？"},
{t:"聽完重說一次",d:"聽完一段自我介紹後，用第三人稱把這個人介紹給別人。"}],
speaking:{q:["請你做三十秒的自我介紹。","你來臺灣多久了？來做什麼？","你的名字要怎麼念？希望別人怎麼叫你？","請你問對方三個問題。"],
model:"你好，我叫阮氏梅，你可以叫我小美。我是越南人，從河內來的。我來臺灣差不多一年了，現在在一家貿易公司上班。很高興認識你，你呢？"},
tasks:[
{n:"任務卡 A",d:"你在語言中心第一天上課，旁邊坐了一個不認識的同學。請你主動打招呼，介紹自己，並且問對方三件事。"},
{n:"任務卡 B",d:"你去朋友的聚會，朋友把你介紹給他的同事。對方問了你的工作，你要說明你在越南做什麼、現在在臺灣做什麼。"},
{n:"任務卡 C",d:"對方一直把你的名字念錯。請你有禮貌地糾正他，並且教他怎麼念。"}],
quiz:[
"看圖選詞：（自我介紹／打電話／點餐／問路）",
"聽音檔選答案：說話的人是哪一國人？",
"句子排序：叫／我／你／小美／可以",
"選出最自然的說法：(A) 我來臺灣一年了 (B) 我一年來臺灣了 (C) 我臺灣來一年了 (D) 一年我來臺灣了",
"填空：我是越南人，＿＿＿？（把問題問回去）",
"「差不多一年了」是什麼意思？(A) 剛好一年 (B) 大概一年 (C) 超過三年 (D) 還不到一個月",
"對方說「很高興認識你」，你可以回：＿＿＿",
"錄音完成任務：用三十秒介紹自己，要包含名字、國籍、來臺時間和工作。"],
selfcheck:["我會說出自己的名字，並告訴對方怎麼稱呼我。","我會說出我的國籍和從哪裡來。","我會說我來臺灣多久了。","我會說明我的工作或身分。","我會把問題問回去。","我能自己完成一段三十秒的自我介紹。"],
ladder:[
{lv:"A1",task:"說出名字和國籍",can:"你好，我叫小美，我是越南人。"},
{lv:"A2",task:"加上身分、工作和來臺時間",can:"我來臺灣一年了，在貿易公司上班。"},
{lv:"B1",task:"延伸說明經歷，並主動回問",can:"我本來在河內做行銷，來臺灣以後轉做業務。你呢？"},
{lv:"B2",task:"依場合調整自我介紹的深淺",can:"面試的時候我會多講工作經驗；朋友聚會就講興趣和生活，比較輕鬆。"}]
},
{
id:"invite",unit:"交友與日常聊天",no:2,
title:"怎麼邀請朋友一起吃飯？",viTitle:"Mời bạn đi ăn cơm thế nào?",
task:{zh:"學完這一課，你可以開口邀請朋友吃飯：提出邀請、約時間和地點、確認人數，並且在對方答應後把細節講清楚。",
vi:"Học xong bài này, bạn có thể mời bạn bè đi ăn: đưa ra lời mời, hẹn thời gian và địa điểm, xác nhận số người, và chốt chi tiết sau khi đối phương đồng ý."},
warmup:["你上一次跟朋友一起吃飯是什麼時候？","在臺灣，約吃飯通常提前多久說？","「改天一起吃飯」是真的邀請，還是客套話？","越南朋友約吃飯的方式跟臺灣一樣嗎？"],
media:"手機聊天畫面（約吃飯的訊息）、餐廳門口三五好友碰面的照片。",
dialog:[
{who:"小美",zh:"阿明，你這個週末有空嗎？",py:"Ā-Míng, nǐ zhège zhōumò yǒu kòng ma?",vi:"A Minh, cuối tuần này bạn có rảnh không?"},
{who:"阿明",zh:"星期六有空，星期天要加班。怎麼了？",py:"Xīngqíliù yǒu kòng, xīngqítiān yào jiābān. Zěnme le?",vi:"Thứ Bảy rảnh, Chủ nhật phải tăng ca. Có chuyện gì vậy?"},
{who:"小美",zh:"我想請你吃飯，謝謝你上次幫我搬家。",py:"Wǒ xiǎng qǐng nǐ chīfàn, xièxie nǐ shàng cì bāng wǒ bānjiā.",vi:"Mình muốn mời bạn đi ăn, cảm ơn bạn lần trước giúp mình chuyển nhà."},
{who:"阿明",zh:"不用這麼客氣啦！不過有飯吃我當然去。",py:"Búyòng zhème kèqì la! Búguò yǒu fàn chī wǒ dāngrán qù.",vi:"Không cần khách sáo vậy đâu! Nhưng có cơm ăn thì tất nhiên mình đi rồi."},
{who:"小美",zh:"那星期六晚上六點，你方便嗎？",py:"Nà xīngqíliù wǎnshang liù diǎn, nǐ fāngbiàn ma?",vi:"Vậy sáu giờ tối thứ Bảy, bạn tiện không?"},
{who:"阿明",zh:"六點有點趕，七點可以嗎？",py:"Liù diǎn yǒudiǎn gǎn, qī diǎn kěyǐ ma?",vi:"Sáu giờ hơi gấp, bảy giờ được không?"},
{who:"小美",zh:"沒問題，七點。你想吃什麼？",py:"Méi wèntí, qī diǎn. Nǐ xiǎng chī shénme?",vi:"Không vấn đề gì, bảy giờ. Bạn muốn ăn gì?"},
{who:"阿明",zh:"都可以，你決定就好。",py:"Dōu kěyǐ, nǐ juédìng jiù hǎo.",vi:"Gì cũng được, bạn quyết định là được."},
{who:"小美",zh:"那我訂捷運站附近那家越南餐廳，我請客。",py:"Nà wǒ dìng jiéyùn zhàn fùjìn nà jiā Yuènán cāntīng, wǒ qǐngkè.",vi:"Vậy mình đặt bàn quán Việt Nam gần ga tàu điện, mình mời."},
{who:"阿明",zh:"好啊！那我們星期六七點在捷運站出口見。",py:"Hǎo a! Nà wǒmen xīngqíliù qī diǎn zài jiéyùn zhàn chūkǒu jiàn.",vi:"Được thôi! Vậy bảy giờ thứ Bảy gặp ở cửa ga nhé."},
{who:"小美",zh:"好，訂好位我再傳訊息給你。",py:"Hǎo, dìng hǎo wèi wǒ zài chuán xùnxī gěi nǐ.",vi:"Được, đặt bàn xong mình nhắn tin cho bạn."}],
keys:[
{zh:"你這個週末有空嗎？",vi:"Cuối tuần này bạn có rảnh không?"},
{zh:"我想請你吃飯。",vi:"Mình muốn mời bạn đi ăn."},
{zh:"……你方便嗎？",vi:"… bạn có tiện không?"},
{zh:"七點可以嗎？",vi:"Bảy giờ được không?"},
{zh:"你想吃什麼？／都可以，你決定就好。",vi:"Bạn muốn ăn gì? / Gì cũng được, bạn quyết định."},
{zh:"我請客。",vi:"Mình mời (mình trả tiền)."},
{zh:"我們在……見。",vi:"Chúng ta gặp nhau ở…"},
{zh:"訂好位我再傳訊息給你。",vi:"Đặt bàn xong mình nhắn tin cho bạn."}],
vocab:[
{w:"有空",py:"yǒu kòng",vi:"rảnh, có thời gian",ex:"你明天有空嗎？"},
{w:"加班",py:"jiābān",vi:"tăng ca",ex:"我這個星期天要加班。"},
{w:"請客",py:"qǐngkè",vi:"mời, đãi khách",ex:"這次我請客，下次換你。"},
{w:"客氣",py:"kèqì",vi:"khách sáo",ex:"別這麼客氣。"},
{w:"方便",py:"fāngbiàn",vi:"tiện",ex:"下午三點你方便嗎？"},
{w:"趕",py:"gǎn",vi:"gấp, vội",ex:"六點下班，六點半到有點趕。"},
{w:"決定",py:"juédìng",vi:"quyết định",ex:"時間你決定就好。"},
{w:"訂位",py:"dìngwèi",vi:"đặt bàn",ex:"這家店要先訂位。"},
{w:"出口",py:"chūkǒu",vi:"lối ra",ex:"我們在二號出口見。"},
{w:"傳訊息",py:"chuán xùnxī",vi:"nhắn tin",ex:"我等一下傳訊息給你。"},
{w:"聚餐",py:"jùcān",vi:"buổi liên hoan, họp mặt ăn uống",ex:"下個月公司要聚餐。"},
{w:"改天",py:"gǎitiān",vi:"hôm khác",ex:"改天再約吧。"}],
vocabNote:"「改天一起吃飯」在臺灣很多時候只是客套，不一定是真的邀請。真的要約，通常會馬上給出具體的時間，例如「這個星期六晚上」。這一點值得跟學生講清楚。",
grammar:{pattern:"……，可以嗎？／……，你方便嗎？",note:"提出具體建議之後，用這兩句把決定權交給對方，比直接說「就這樣」客氣得多。",
vi:"Sau khi đưa ra đề nghị cụ thể, dùng hai mẫu câu này để nhường quyết định cho đối phương, lịch sự hơn nhiều.",
ex:["星期六晚上七點，可以嗎？","我們約在捷運站，你方便嗎？","改成明天，可以嗎？","我帶朋友一起去，你方便嗎？"],
swap:"＿＿＿，可以嗎？（換成：早一點／晚一點／換一家店／改成下星期）"},
listening:[
{t:"聽對話選圖片",d:"播放約時間的對話，學生從四張行事曆圖中選出正確的日期時間。"},
{t:"聽內容選答案",d:"他們最後約幾點？(A) 六點 (B) 六點半 (C) 七點 (D) 七點半"},
{t:"聽完填表",d:"填寫：日期＿＿＿／時間＿＿＿／地點＿＿＿／誰請客＿＿＿"},
{t:"判斷答應還是拒絕",d:"聽四段回覆，判斷對方是答應、還沒決定、還是委婉拒絕。"},
{t:"聽完重說一次",d:"聽完後把約定的細節完整複述一遍，確認沒有聽錯。"}],
speaking:{q:["你想約誰吃飯？為什麼？","你會約什麼時候、在哪裡？","對方說那個時間不行，你怎麼回？","請你完整說出一次邀請。"],
model:"阿明，你這個星期六晚上有空嗎？我想請你吃飯，謝謝你上次幫我。七點在捷運站附近那家越南餐廳，你方便嗎？訂好位我再傳訊息給你。"},
tasks:[
{n:"任務卡 A",d:"你想謝謝一個幫過你的朋友。請你邀請他吃飯，約好時間、地點，並說明是你請客。"},
{n:"任務卡 B",d:"你要約三個朋友一起吃飯，但每個人有空的時間都不一樣。請你想辦法喬出一個大家都可以的時間。"},
{n:"任務卡 C",d:"你已經約好了，但臨時要改時間。請你打電話說明原因，並提出新的時間。"}],
quiz:[
"看圖選詞：（請客／加班／訂位／聚餐）",
"聽音檔選答案：他們約在哪裡見面？",
"句子排序：有空／這個／你／嗎／週末",
"選出最自然的說法：(A) 你方便嗎七點 (B) 七點你方便嗎 (C) 方便七點你嗎 (D) 七點方便嗎你",
"填空：我想＿＿＿你吃飯。",
"「改天一起吃飯」通常是什麼意思？(A) 一定會約 (B) 常常只是客套 (C) 明天要吃飯 (D) 拒絕見面",
"對方說「都可以，你決定就好」，你接下來要做什麼？",
"錄音完成任務：邀請朋友這個星期六晚上七點吃飯，你請客。"],
selfcheck:["我會問對方有沒有空。","我會提出具體的時間和地點。","我會用「可以嗎／你方便嗎」把決定權交給對方。","我會說明誰請客。","對方不方便的時候，我會提出別的時間。","我能自己完成一次完整的邀請。"],
ladder:[
{lv:"A1",task:"提出簡單邀請和時間",can:"星期六一起吃飯，好嗎？"},
{lv:"A2",task:"約定時間、地點並確認",can:"星期六七點，在捷運站出口見，可以嗎？"},
{lv:"B1",task:"協調彼此的時間、說明原因",can:"我星期六要加班，星期天中午可以嗎？那天我比較有時間。"},
{lv:"B2",task:"安排多人聚餐並處理變動",can:"三個人裡面只有阿明星期六不行，我看要不要改成星期天中午，這樣大家都能到。"}]
},
{
id:"refuse",unit:"交友與日常聊天",no:3,
title:"如何自然地拒絕邀請？",viTitle:"Từ chối lời mời sao cho tự nhiên?",
task:{zh:"學完這一課，你可以婉轉地拒絕別人的邀請：先表示謝意、說明原因、表達可惜，並且主動提出下一次的時間，不讓對方覺得被拒絕。",
vi:"Học xong bài này, bạn có thể từ chối lời mời một cách khéo léo: cảm ơn trước, nêu lý do, bày tỏ tiếc nuối và chủ động hẹn lần sau."},
warmup:["你有沒有不好意思拒絕別人的經驗？","在越南，拒絕邀請的時候會說什麼？","直接說「我不要」會不會太直接？","被拒絕的時候，你希望對方怎麼說？"],
media:"手機訊息畫面（婉拒的對話）、兩個人在辦公室門口交談的照片。",
dialog:[
{who:"同事",zh:"小美，今天下班我們要去唱歌，你要不要一起來？",py:"Xiǎo-Měi, jīntiān xiàbān wǒmen yào qù chànggē, nǐ yào bú yào yìqǐ lái?",vi:"Tiểu Mai, tan làm hôm nay bọn mình đi hát, bạn có muốn đi cùng không?"},
{who:"小美",zh:"謝謝你們找我，可是今天真的不行。",py:"Xièxie nǐmen zhǎo wǒ, kěshì jīntiān zhēnde bùxíng.",vi:"Cảm ơn mọi người đã rủ, nhưng hôm nay thật sự không được."},
{who:"同事",zh:"怎麼了？很忙嗎？",py:"Zěnme le? Hěn máng ma?",vi:"Sao vậy? Bận lắm à?"},
{who:"小美",zh:"我姐姐從越南來，我要去機場接她。",py:"Wǒ jiějie cóng Yuènán lái, wǒ yào qù jīchǎng jiē tā.",vi:"Chị tôi từ Việt Nam sang, tôi phải ra sân bay đón chị ấy."},
{who:"同事",zh:"那沒辦法，家人比較重要。",py:"Nà méi bànfǎ, jiārén bǐjiào zhòngyào.",vi:"Vậy thì đành chịu, người nhà quan trọng hơn."},
{who:"小美",zh:"真可惜，我很想去。下次一定找我！",py:"Zhēn kěxí, wǒ hěn xiǎng qù. Xià cì yídìng zhǎo wǒ!",vi:"Tiếc thật, tôi rất muốn đi. Lần sau nhớ rủ tôi nhé!"},
{who:"同事",zh:"好啊，下個月我們還要辦一次。",py:"Hǎo a, xià ge yuè wǒmen hái yào bàn yí cì.",vi:"Được thôi, tháng sau bọn mình còn tổ chức một lần nữa."},
{who:"小美",zh:"太好了，下個月我一定到。",py:"Tài hǎo le, xià ge yuè wǒ yídìng dào.",vi:"Tuyệt quá, tháng sau tôi nhất định sẽ đến."},
{who:"同事",zh:"那你今天路上小心。",py:"Nà nǐ jīntiān lùshang xiǎoxīn.",vi:"Vậy hôm nay bạn đi đường cẩn thận nhé."},
{who:"小美",zh:"謝謝，你們玩得開心！",py:"Xièxie, nǐmen wán de kāixīn!",vi:"Cảm ơn, mọi người chơi vui vẻ nhé!"}],
keys:[
{zh:"謝謝你們找我，可是……",vi:"Cảm ơn mọi người đã rủ, nhưng…"},
{zh:"今天真的不行。",vi:"Hôm nay thật sự không được."},
{zh:"我已經跟別人約好了。",vi:"Tôi đã hẹn với người khác rồi."},
{zh:"真可惜，我很想去。",vi:"Tiếc thật, tôi rất muốn đi."},
{zh:"下次一定找我！",vi:"Lần sau nhất định rủ tôi nhé!"},
{zh:"改天我請你們。",vi:"Hôm khác tôi mời mọi người."},
{zh:"你們玩得開心！",vi:"Chúc mọi người chơi vui vẻ!"}],
vocab:[
{w:"拒絕",py:"jùjué",vi:"từ chối",ex:"我不好意思拒絕他。"},
{w:"不行",py:"bùxíng",vi:"không được",ex:"今天不行，明天可以。"},
{w:"可惜",py:"kěxí",vi:"tiếc",ex:"真可惜，我不能去。"},
{w:"約好",py:"yuē hǎo",vi:"đã hẹn",ex:"我跟朋友約好了。"},
{w:"沒辦法",py:"méi bànfǎ",vi:"đành chịu, không còn cách nào",ex:"那天要上班，沒辦法。"},
{w:"接",py:"jiē",vi:"đón",ex:"我要去機場接我姐姐。"},
{w:"重要",py:"zhòngyào",vi:"quan trọng",ex:"家人最重要。"},
{w:"下次",py:"xià cì",vi:"lần sau",ex:"下次一定找我。"},
{w:"辦",py:"bàn",vi:"tổ chức",ex:"下個月公司要辦活動。"},
{w:"不好意思",py:"bù hǎoyìsi",vi:"ngại, xin lỗi",ex:"不好意思，我那天有事。"},
{w:"臨時",py:"línshí",vi:"đột xuất",ex:"我臨時有事，不能去了。"},
{w:"另外",py:"lìngwài",vi:"khác, ngoài ra",ex:"我們另外找時間吧。"}],
vocabNote:"臺灣人拒絕的時候很少直接說「我不要」。常見的順序是：先謝謝 → 說原因 → 說可惜 → 主動約下一次。四個步驟走完，對方通常不會覺得被拒絕。",
grammar:{pattern:"謝謝……，可是……",note:"先接受對方的好意，再說出困難。「可是」前面那句話是關鍵，不能省略。",
vi:"Nhận lời tốt của đối phương trước, rồi mới nêu khó khăn. Vế trước chữ 「可是」 là mấu chốt, không được lược bỏ.",
ex:["謝謝你們找我，可是今天真的不行。","謝謝你的邀請，可是我已經跟別人約好了。","謝謝，可是我最近比較忙。","謝謝老闆，可是那天我要看醫生。"],
swap:"謝謝＿＿＿，可是＿＿＿。（換成：你的好意／這次機會 ＋ 我剛好有事／我人不太舒服）"},
listening:[
{t:"聽對話選圖片",d:"播放四段拒絕的理由，學生選出對應的圖片（機場、醫院、公司、家裡）。"},
{t:"聽內容選答案",d:"小美為什麼不能去？(A) 要加班 (B) 要接家人 (C) 不喜歡唱歌 (D) 沒有錢"},
{t:"聽完填表",d:"填寫：邀請什麼＿＿＿／拒絕原因＿＿＿／有沒有約下次＿＿＿"},
{t:"判斷客氣還是失禮",d:"聽四種回覆方式，判斷哪一種聽起來最舒服、哪一種太直接。"},
{t:"聽完重說一次",d:"聽完後，用自己的話把小美的拒絕重新說一遍。"}],
speaking:{q:["有人約你，可是你不能去，你會怎麼說？","你會說出真正的原因嗎？為什麼？","要怎麼讓對方知道你下次還想去？","請你完整拒絕一次邀請。"],
model:"謝謝你們找我，可是今天真的不行，我姐姐從越南來，我要去機場接她。真可惜，我很想去，下次一定找我！你們玩得開心。"},
tasks:[
{n:"任務卡 A",d:"同事約你下班去唱歌，但你已經跟家人約好了。請你婉轉拒絕，並主動約下一次。"},
{n:"任務卡 B",d:"朋友約你週末出去玩，你只是很累想休息，不想說真正的原因。請你想一個得體的說法。"},
{n:"任務卡 C",d:"你已經答應了，可是臨時有事去不了。請你打電話說明並道歉。"}],
quiz:[
"看圖選詞：（拒絕／邀請／請客／接機）",
"聽音檔選答案：說話的人有沒有答應？",
"句子排序：可是／找我／今天／謝謝／不行／你們／真的",
"選出最自然的說法：(A) 我不要去 (B) 謝謝你找我，可是今天真的不行 (C) 不行 (D) 我沒空",
"填空：真可惜，我很想去。＿＿＿一定找我！",
"拒絕的時候，下面哪一個步驟最容易被忘記？(A) 說謝謝 (B) 說原因 (C) 主動約下一次 (D) 說再見",
"朋友說「下個月我們還要辦一次」，你可以回：＿＿＿",
"錄音完成任務：婉拒同事今天的邀約，並約下個月。"],
selfcheck:["我會先謝謝對方再拒絕。","我會說出一個合理的原因。","我會表達可惜的心情。","我會主動提下一次。","我不會只說「不行」就結束對話。","我能完整、有禮貌地拒絕一次邀請。"],
ladder:[
{lv:"A1",task:"用簡單的話說不能去",can:"謝謝，今天不行。"},
{lv:"A2",task:"加上原因和下一次",can:"謝謝你找我，可是今天要接家人。下次一定找我！"},
{lv:"B1",task:"婉轉說明、不傷感情",can:"真可惜，我很想去，可是這個星期真的排不出時間，下個月我請你們。"},
{lv:"B2",task:"面對再三邀請仍能得體堅持",can:"我知道你們難得辦一次，可是那天我實在走不開。這樣好了，下次我來訂位。"}]
}
];
TC.push(
{
id:"drink",unit:"在臺灣生活",no:4,
title:"在飲料店點餐",viTitle:"Gọi đồ uống ở tiệm trà sữa",
task:{zh:"學完這一課，你可以在飲料店完成點餐：說出飲料名稱、大小杯、甜度和冰量，選擇內用或外帶，並且問價錢、付錢。",
vi:"Học xong bài này, bạn có thể gọi đồ uống ở tiệm: nói tên đồ uống, cỡ ly, độ ngọt, lượng đá, chọn uống tại chỗ hay mang đi, hỏi giá và thanh toán."},
warmup:["你平常喝什麼飲料？多久喝一次？","你知道「半糖、微糖、去冰」是什麼意思嗎？","在越南點飲料和在臺灣點飲料，哪裡不一樣？","你有沒有點錯過飲料？那時候你怎麼說？"],
media:"手搖飲料店的點餐櫃台、菜單牆、甜度冰量對照表、一杯珍珠奶茶。",
dialog:[
{who:"店員",zh:"您好，請問要喝什麼？",py:"Nín hǎo, qǐngwèn yào hē shénme?",vi:"Xin chào, anh/chị muốn uống gì ạ?"},
{who:"顧客",zh:"我要一杯珍珠奶茶。",py:"Wǒ yào yì bēi zhēnzhū nǎichá.",vi:"Tôi muốn một ly trà sữa trân châu."},
{who:"店員",zh:"大杯還是中杯？",py:"Dà bēi háishì zhōng bēi?",vi:"Ly lớn hay ly vừa ạ?"},
{who:"顧客",zh:"大杯。",py:"Dà bēi.",vi:"Ly lớn."},
{who:"店員",zh:"甜度、冰量呢？",py:"Tiándù, bīngliàng ne?",vi:"Độ ngọt và lượng đá thì sao ạ?"},
{who:"顧客",zh:"微糖、少冰。",py:"Wéi táng, shǎo bīng.",vi:"Ít đường, ít đá."},
{who:"店員",zh:"好的。內用還是外帶？",py:"Hǎo de. Nèiyòng háishì wàidài?",vi:"Vâng. Dùng tại chỗ hay mang đi ạ?"},
{who:"顧客",zh:"外帶，不用袋子，謝謝。",py:"Wàidài, búyòng dàizi, xièxie.",vi:"Mang đi, không cần túi, cảm ơn."},
{who:"店員",zh:"一共六十五元。",py:"Yígòng liùshíwǔ yuán.",vi:"Tổng cộng sáu mươi lăm đồng."},
{who:"顧客",zh:"可以刷卡嗎？",py:"Kěyǐ shuākǎ ma?",vi:"Tôi quẹt thẻ được không?"},
{who:"店員",zh:"可以。請稍等一下。",py:"Kěyǐ. Qǐng shāo děng yíxià.",vi:"Được ạ. Xin đợi một chút."}],
keys:[
{zh:"我要一杯……",vi:"Tôi muốn một ly…"},
{zh:"大杯／中杯",vi:"Ly lớn / ly vừa"},
{zh:"微糖、少冰",vi:"Ít đường, ít đá"},
{zh:"可以不要……嗎？",vi:"Có thể không cho… được không?"},
{zh:"內用／外帶",vi:"Dùng tại chỗ / mang đi"},
{zh:"一共多少錢？",vi:"Tổng cộng bao nhiêu tiền?"},
{zh:"可以刷卡嗎？",vi:"Quẹt thẻ được không?"},
{zh:"這樣就好，謝謝。",vi:"Vậy là được rồi, cảm ơn."}],
vocab:[
{w:"飲料",py:"yǐnliào",vi:"đồ uống",ex:"你想喝什麼飲料？"},
{w:"珍珠奶茶",py:"zhēnzhū nǎichá",vi:"trà sữa trân châu",ex:"我要一杯珍珠奶茶。"},
{w:"甜度",py:"tiándù",vi:"độ ngọt",ex:"甜度要怎麼調整？"},
{w:"冰量",py:"bīngliàng",vi:"lượng đá",ex:"冰量可以選正常冰或少冰。"},
{w:"微糖",py:"wéitáng",vi:"ít đường (khoảng 30%)",ex:"我要微糖，不要太甜。"},
{w:"半糖",py:"bàntáng",vi:"nửa đường (50%)",ex:"半糖對我來說剛剛好。"},
{w:"無糖",py:"wútáng",vi:"không đường",ex:"我最近都喝無糖的。"},
{w:"去冰",py:"qùbīng",vi:"bỏ đá",ex:"天氣冷，我要去冰。"},
{w:"大杯",py:"dàbēi",vi:"ly lớn",ex:"大杯比中杯多十五元。"},
{w:"外帶",py:"wàidài",vi:"mang đi",ex:"我要外帶，不用袋子。"},
{w:"內用",py:"nèiyòng",vi:"dùng tại chỗ",ex:"內用要用店裡的杯子。"},
{w:"刷卡",py:"shuākǎ",vi:"quẹt thẻ",ex:"這家店可以刷卡嗎？"}],
vocabNote:"臺灣手搖飲的甜度一般分：正常糖、少糖、半糖、微糖、無糖；冰量分：正常冰、少冰、微冰、去冰，天冷還可以點熱的。",
grammar:{pattern:"可以 + 動詞 + 嗎？",note:"用來禮貌地問「我能不能這樣做」，或請店員幫忙。",
vi:"Dùng để hỏi xin phép hoặc nhờ vả một cách lịch sự.",
ex:["可以刷卡嗎？","可以不要冰嗎？","可以幫我加熱嗎？","可以少一點糖嗎？"],
swap:"可以＿＿＿嗎？（換成：用現金／加珍珠／換大杯／再等一下）"},
listening:[
{t:"聽對話選圖片",d:"播放顧客點餐的句子，學生從四張飲料圖片中選出對的那一杯。"},
{t:"聽內容選答案",d:"顧客點的是什麼？(A) 中杯紅茶 (B) 大杯珍珠奶茶 (C) 大杯綠茶 (D) 中杯奶茶"},
{t:"聽訂單填甜度與冰量",d:"填表：飲料＿＿＿／大小＿＿＿／甜度＿＿＿／冰量＿＿＿"},
{t:"判斷店員有沒有聽錯",d:"顧客說「半糖去冰」，店員複誦「半糖少冰」——對不對？該怎麼糾正？"},
{t:"聽完重說一次",d:"聽完整段訂單後，用自己的話把訂單再說一遍。"}],
speaking:{q:["你想喝什麼？","甜度和冰量你要怎麼選？為什麼？","你還想加什麼？（珍珠／椰果／布丁）","請完整說出你的訂單。"],
model:"我要一杯大杯珍珠奶茶，微糖、少冰，不用袋子，謝謝。一共多少錢？"},
tasks:[
{n:"任務卡 A",d:"你要買兩杯飲料。\n第一杯：紅茶／無糖／正常冰\n第二杯：珍珠奶茶／微糖／少冰\n你只有現金，還要問總價。"},
{n:"任務卡 B",d:"你幫同事買飲料。同事說「不要太甜、不要冰」，可是你忘記他要大杯還是中杯。請你點餐並想辦法解決。"},
{n:"任務卡 C",d:"你點的是去冰，但拿到的飲料有冰。請你跟店員說明，並問可不可以換一杯。"}],
quiz:[
"看圖選詞：（珍珠奶茶／紅茶／果汁／咖啡）",
"聽音檔選答案：顧客要的甜度是？(A) 無糖 (B) 微糖 (C) 半糖 (D) 正常糖",
"句子排序：一杯／我要／珍珠奶茶／大杯的",
"選出最自然的說法：(A) 我要糖少 (B) 我要少糖 (C) 我糖要少 (D) 少我要糖",
"填空：可以＿＿＿嗎？（你想用信用卡付錢）",
"「去冰」是什麼意思？(A) 多一點冰 (B) 完全不要冰 (C) 熱的 (D) 一半的冰",
"店員問「內用還是外帶？」，你要帶走，你會說：＿＿＿",
"錄音完成任務：說出「大杯四季春、半糖、去冰、外帶」這張訂單。"],
selfcheck:["我會說出想買的飲料和大小杯。","我會選擇甜度和冰量並說出來。","我會說內用還是外帶。","我會詢問價錢、選擇付錢方式。","飲料做錯的時候，我能說明問題。","我能自己一個人完成點餐。"],
ladder:[
{lv:"A1",task:"說出飲料名稱、數量和大小杯",can:"我要一杯大杯的珍珠奶茶。"},
{lv:"A2",task:"說出甜度、冰量，並提出簡單需求",can:"微糖、少冰，不用袋子，謝謝。"},
{lv:"B1",task:"修改訂單或處理拿錯的情況",can:"不好意思，我點的是去冰，可是這杯有冰。"},
{lv:"B2",task:"說明問題並協調解決方式",can:"這杯跟我點的不一樣，可以幫我重做一杯嗎？如果不方便，能不能退錢？"}]
},
{
id:"pickup",unit:"在臺灣生活",no:5,
title:"在便利商店取貨",viTitle:"Nhận hàng ở cửa hàng tiện lợi",
task:{zh:"學完這一課，你可以到便利商店取網購的包裹：說明來取貨、提供取貨編號和證件、確認付款方式，並且處理「找不到包裹」的狀況。",
vi:"Học xong bài này, bạn có thể đến cửa hàng tiện lợi nhận hàng đặt online: nói rõ đến lấy hàng, cung cấp mã nhận hàng và giấy tờ, xác nhận cách thanh toán, và xử lý khi không tìm thấy bưu kiện."},
warmup:["你在臺灣網購過嗎？買什麼？","你知道「超商取貨付款」是什麼意思嗎？","取貨的時候要帶什麼？","如果店員說找不到你的包裹，你會怎麼辦？"],
media:"便利商店櫃台、手機上的取貨簡訊畫面、包裹上的條碼。",
dialog:[
{who:"顧客",zh:"你好，我要取貨。",py:"Nǐ hǎo, wǒ yào qǔhuò.",vi:"Xin chào, tôi muốn nhận hàng."},
{who:"店員",zh:"好的，請給我取貨編號。",py:"Hǎo de, qǐng gěi wǒ qǔhuò biānhào.",vi:"Vâng, cho tôi xin mã nhận hàng ạ."},
{who:"顧客",zh:"在這裡，簡訊上的號碼。",py:"Zài zhèlǐ, jiǎnxùn shàng de hàomǎ.",vi:"Ở đây ạ, số trên tin nhắn."},
{who:"店員",zh:"謝謝。請問是本人取貨嗎？要看一下證件。",py:"Xièxie. Qǐngwèn shì běnrén qǔhuò ma? Yào kàn yíxià zhèngjiàn.",vi:"Cảm ơn. Anh/chị tự nhận hàng phải không? Cho tôi xem giấy tờ ạ."},
{who:"顧客",zh:"是，這是我的居留證。",py:"Shì, zhè shì wǒ de jūliúzhèng.",vi:"Vâng, đây là thẻ cư trú của tôi."},
{who:"店員",zh:"好，這件是貨到付款，一共五百八十元。",py:"Hǎo, zhè jiàn shì huò dào fùkuǎn, yígòng wǔbǎi bāshí yuán.",vi:"Được, đơn này là thanh toán khi nhận hàng, tổng cộng năm trăm tám mươi đồng."},
{who:"顧客",zh:"我以為已經付過了。",py:"Wǒ yǐwéi yǐjīng fù guò le.",vi:"Tôi tưởng đã trả rồi."},
{who:"店員",zh:"您看一下簡訊，上面有寫「取貨付款」。",py:"Nín kàn yíxià jiǎnxùn, shàngmiàn yǒu xiě qǔhuò fùkuǎn.",vi:"Anh/chị xem tin nhắn, trên đó có ghi thanh toán khi nhận hàng."},
{who:"顧客",zh:"真的耶，不好意思。可以刷卡嗎？",py:"Zhēnde ye, bù hǎoyìsi. Kěyǐ shuākǎ ma?",vi:"Đúng thật, xin lỗi. Quẹt thẻ được không?"},
{who:"店員",zh:"取貨付款只能付現金喔。",py:"Qǔhuò fùkuǎn zhǐ néng fù xiànjīn ō.",vi:"Thanh toán khi nhận hàng chỉ trả tiền mặt thôi ạ."},
{who:"顧客",zh:"好，那我用現金。請給我發票，謝謝。",py:"Hǎo, nà wǒ yòng xiànjīn. Qǐng gěi wǒ fāpiào, xièxie.",vi:"Được, vậy tôi trả tiền mặt. Cho tôi hóa đơn, cảm ơn."}],
keys:[
{zh:"你好，我要取貨。",vi:"Xin chào, tôi muốn nhận hàng."},
{zh:"這是取貨編號。",vi:"Đây là mã nhận hàng."},
{zh:"這是我的居留證。",vi:"Đây là thẻ cư trú của tôi."},
{zh:"我以為已經付過了。",vi:"Tôi tưởng đã trả rồi."},
{zh:"可以刷卡嗎？／只能付現金嗎？",vi:"Quẹt thẻ được không? / Chỉ trả tiền mặt thôi ạ?"},
{zh:"請給我發票。",vi:"Cho tôi hóa đơn."},
{zh:"可以幫我再查一次嗎？",vi:"Có thể kiểm tra lại giúp tôi không?"}],
vocab:[
{w:"取貨",py:"qǔhuò",vi:"nhận hàng",ex:"我來取貨。"},
{w:"包裹",py:"bāoguǒ",vi:"bưu kiện",ex:"我的包裹到了嗎？"},
{w:"編號",py:"biānhào",vi:"mã số",ex:"取貨編號在簡訊上。"},
{w:"簡訊",py:"jiǎnxùn",vi:"tin nhắn",ex:"店家會傳簡訊通知你。"},
{w:"證件",py:"zhèngjiàn",vi:"giấy tờ tùy thân",ex:"取貨要帶證件。"},
{w:"居留證",py:"jūliúzhèng",vi:"thẻ cư trú",ex:"我用居留證取貨。"},
{w:"本人",py:"běnrén",vi:"chính chủ",ex:"要本人取貨才可以。"},
{w:"貨到付款",py:"huò dào fùkuǎn",vi:"thanh toán khi nhận hàng",ex:"這件是貨到付款。"},
{w:"現金",py:"xiànjīn",vi:"tiền mặt",ex:"只能付現金。"},
{w:"發票",py:"fāpiào",vi:"hóa đơn",ex:"請給我發票。"},
{w:"以為",py:"yǐwéi",vi:"tưởng (nhưng không đúng)",ex:"我以為已經付過了。"},
{w:"查",py:"chá",vi:"tra, kiểm tra",ex:"可以幫我查一下嗎？"}],
vocabNote:"「以為」是學生很容易搞混的詞：說「我以為……」表示後來發現不是那樣。如果事情確實如此，要用「我想」或「我覺得」。",
grammar:{pattern:"我以為……",note:"用來說明自己原本想錯了，後面通常接一個和事實不一樣的想法。是解釋誤會時最好用的一句。",
vi:"Dùng để nói mình đã hiểu nhầm; phía sau thường là điều không đúng với thực tế.",
ex:["我以為已經付過了。","我以為今天可以取貨。","我以為不用帶證件。","我以為店員會打電話給我。"],
swap:"我以為＿＿＿。（換成：包裹還沒到／可以刷卡／我朋友可以幫我拿）"},
listening:[
{t:"聽對話選圖片",d:"播放取貨對話，學生從四張圖中選出顧客拿出來的東西（手機簡訊／居留證／現金／發票）。"},
{t:"聽內容選答案",d:"這件包裹要付多少錢？(A) 已付清 (B) 380 元 (C) 580 元 (D) 850 元"},
{t:"聽完填表",d:"填寫：取貨編號＿＿＿／付款方式＿＿＿／要不要證件＿＿＿"},
{t:"判斷問題出在哪",d:"聽一段對話，判斷是店員找不到包裹、顧客沒帶證件、還是金額不對。"},
{t:"聽完重說一次",d:"聽完後把取貨流程用自己的話說一遍。"}],
speaking:{q:["你到便利商店取貨，第一句話會說什麼？","店員要看證件，你會怎麼回答？","店員說要付款，可是你以為付過了，你怎麼說？","請完整說出一次取貨過程。"],
model:"你好，我要取貨。這是取貨編號，在簡訊上。這是我的居留證。咦，我以為已經付過了……好，那我用現金。請給我發票，謝謝。"},
tasks:[
{n:"任務卡 A",d:"你去超商取一個網購的包裹，是貨到付款，金額 580 元。你身上只有 500 元現金和一張信用卡。請你想辦法解決。"},
{n:"任務卡 B",d:"店員說系統查不到你的包裹。請你說明簡訊上的資訊，並問可以怎麼處理。"},
{n:"任務卡 C",d:"你要幫室友取貨，可是你不是本人。請你跟店員說明狀況，問要準備什麼才可以代領。"}],
quiz:[
"看圖選詞：（包裹／發票／居留證／現金）",
"聽音檔選答案：顧客用什麼付錢？",
"句子排序：取貨／我／你好／要",
"選出最自然的說法：(A) 我要拿東西 (B) 你好，我要取貨 (C) 給我包裹 (D) 我的東西在哪裡",
"填空：我＿＿＿已經付過了。（表示想錯了）",
"「本人取貨」是什麼意思？(A) 誰都可以拿 (B) 要收件人自己來拿 (C) 店員送到家 (D) 要先付錢",
"店員說「只能付現金」，你身上沒現金，你會說：＿＿＿",
"錄音完成任務：完整說出一次超商取貨，包含編號、證件和付款。"],
selfcheck:["我會說出我要取貨。","我會提供取貨編號和證件。","我聽得懂「貨到付款」和「只能付現金」。","我會要發票。","包裹查不到的時候，我能說明狀況。","我能自己一個人完成取貨。"],
ladder:[
{lv:"A1",task:"說出來意並交出編號",can:"你好，我要取貨。這是編號。"},
{lv:"A2",task:"回應證件與付款要求",can:"這是我的居留證。我用現金付，請給我發票。"},
{lv:"B1",task:"處理付款方式或金額的疑問",can:"我以為已經付過了。如果只能付現金，我先去領錢再回來，可以嗎？"},
{lv:"B2",task:"處理包裹查無資料等突發狀況",can:"簡訊上寫昨天就到店了，可是系統查不到。可以幫我看一下有沒有放到別的架子，或是幫我跟店家確認？"}]
},
{
id:"clinic",unit:"在臺灣生活",no:6,
title:"看醫生怎麼說症狀？",viTitle:"Đi khám bệnh, mô tả triệu chứng thế nào?",
task:{zh:"學完這一課，你可以到診所看病：說明哪裡不舒服、症狀多久了、有沒有過敏，聽懂醫生的指示，並且問清楚吃藥的方式。",
vi:"Học xong bài này, bạn có thể đi khám ở phòng khám: nói chỗ khó chịu, bị bao lâu rồi, có dị ứng không, hiểu chỉ dẫn của bác sĩ và hỏi rõ cách uống thuốc."},
warmup:["你在臺灣看過醫生嗎？感覺怎麼樣？","看醫生要帶什麼？","你知道「健保卡」是什麼嗎？","身體不舒服的時候，你會先自己買藥還是先看醫生？"],
media:"診所櫃台、健保卡、藥袋上的服藥說明、量體溫的照片。",
dialog:[
{who:"醫生",zh:"哪裡不舒服？",py:"Nǎlǐ bù shūfú?",vi:"Anh/chị khó chịu ở đâu?"},
{who:"病人",zh:"我從前天開始喉嚨痛，還有一點發燒。",py:"Wǒ cóng qiántiān kāishǐ hóulóng tòng, hái yǒu yìdiǎn fāshāo.",vi:"Từ hôm kia tôi bị đau họng, còn hơi sốt."},
{who:"醫生",zh:"有咳嗽嗎？",py:"Yǒu késòu ma?",vi:"Có ho không?"},
{who:"病人",zh:"有，晚上比較嚴重，睡不好。",py:"Yǒu, wǎnshang bǐjiào yánzhòng, shuì bù hǎo.",vi:"Có, buổi tối nặng hơn, ngủ không ngon."},
{who:"醫生",zh:"我看一下喉嚨。嘴巴張開，啊——",py:"Wǒ kàn yíxià hóulóng. Zuǐba zhāng kāi, ā—",vi:"Để tôi xem họng. Há miệng ra, a—"},
{who:"病人",zh:"很痛，吞口水也會痛。",py:"Hěn tòng, tūn kǒushuǐ yě huì tòng.",vi:"Rất đau, nuốt nước bọt cũng đau."},
{who:"醫生",zh:"喉嚨發炎了。你對藥物過敏嗎？",py:"Hóulóng fāyán le. Nǐ duì yàowù guòmǐn ma?",vi:"Họng bị viêm rồi. Anh/chị có dị ứng thuốc không?"},
{who:"病人",zh:"沒有。請問這個藥怎麼吃？",py:"Méiyǒu. Qǐngwèn zhège yào zěnme chī?",vi:"Không. Xin hỏi thuốc này uống thế nào?"},
{who:"醫生",zh:"一天三次，飯後吃，吃三天。",py:"Yì tiān sān cì, fàn hòu chī, chī sān tiān.",vi:"Ngày ba lần, uống sau bữa ăn, uống ba ngày."},
{who:"病人",zh:"好。那我可以上班嗎？",py:"Hǎo. Nà wǒ kěyǐ shàngbān ma?",vi:"Vâng. Vậy tôi đi làm được không?"},
{who:"醫生",zh:"可以，但是要多喝水、多休息。三天沒好再回來。",py:"Kěyǐ, dànshì yào duō hē shuǐ, duō xiūxí. Sān tiān méi hǎo zài huílái.",vi:"Được, nhưng phải uống nhiều nước, nghỉ ngơi nhiều. Ba ngày không đỡ thì quay lại."}],
keys:[
{zh:"我……不舒服。",vi:"Tôi khó chịu ở…"},
{zh:"從……開始……",vi:"Từ… bắt đầu…"},
{zh:"晚上比較嚴重。",vi:"Buổi tối nặng hơn."},
{zh:"我對……過敏。／我沒有過敏。",vi:"Tôi dị ứng với… / Tôi không dị ứng."},
{zh:"這個藥怎麼吃？",vi:"Thuốc này uống thế nào?"},
{zh:"一天三次，飯後吃。",vi:"Ngày ba lần, uống sau bữa ăn."},
{zh:"我需要休息幾天？",vi:"Tôi cần nghỉ mấy ngày?"}],
vocab:[
{w:"不舒服",py:"bù shūfú",vi:"khó chịu, không khỏe",ex:"我今天很不舒服。"},
{w:"症狀",py:"zhèngzhuàng",vi:"triệu chứng",ex:"你的症狀有幾天了？"},
{w:"喉嚨痛",py:"hóulóng tòng",vi:"đau họng",ex:"我喉嚨痛，吞口水會痛。"},
{w:"發燒",py:"fāshāo",vi:"sốt",ex:"我有一點發燒。"},
{w:"咳嗽",py:"késòu",vi:"ho",ex:"晚上咳嗽比較嚴重。"},
{w:"發炎",py:"fāyán",vi:"viêm",ex:"醫生說我的喉嚨發炎了。"},
{w:"嚴重",py:"yánzhòng",vi:"nghiêm trọng, nặng",ex:"這兩天比較嚴重。"},
{w:"過敏",py:"guòmǐn",vi:"dị ứng",ex:"我對海鮮過敏。"},
{w:"藥",py:"yào",vi:"thuốc",ex:"這個藥飯後吃。"},
{w:"飯後",py:"fàn hòu",vi:"sau bữa ăn",ex:"一天三次，飯後吃。"},
{w:"健保卡",py:"jiànbǎokǎ",vi:"thẻ bảo hiểm y tế",ex:"看醫生要帶健保卡。"},
{w:"休息",py:"xiūxí",vi:"nghỉ ngơi",ex:"要多喝水、多休息。"}],
vocabNote:"在臺灣看小病通常是去「診所」，不是大醫院。帶健保卡，掛號費一般一百到兩百元，藥會由診所直接給。這一點對剛來的學生很重要。",
grammar:{pattern:"從……開始……",note:"用來說明症狀是什麼時候出現的。醫生一定會問，這是看病時最關鍵的一句。",
vi:"Dùng để nói triệu chứng bắt đầu từ khi nào. Bác sĩ chắc chắn sẽ hỏi câu này.",
ex:["我從前天開始喉嚨痛。","從昨天晚上開始頭痛。","從星期一開始咳嗽。","從吃了海鮮以後開始不舒服。"],
swap:"從＿＿＿開始＿＿＿。（換成：今天早上／三天前 ＋ 肚子痛／流鼻水／全身沒力氣）"},
listening:[
{t:"聽對話選圖片",d:"播放四段症狀描述，學生從人體圖上選出對應的部位。"},
{t:"聽內容選答案",d:"病人是什麼時候開始不舒服的？(A) 今天早上 (B) 昨天 (C) 前天 (D) 上個星期"},
{t:"聽藥袋說明填表",d:"填寫：一天幾次＿＿＿／飯前還是飯後＿＿＿／吃幾天＿＿＿"},
{t:"判斷該不該去看醫生",d:"聽四種情況，判斷哪一種可以先休息、哪一種要馬上就醫。"},
{t:"聽完重說一次",d:"聽完後幫病人向另一位醫生轉述他的症狀。"}],
speaking:{q:["你最近哪裡不舒服？","症狀是什麼時候開始的？","你對什麼東西過敏嗎？","請完整說出你的症狀，就像在跟醫生說話。"],
model:"醫生你好，我從前天開始喉嚨痛，還有一點發燒，晚上咳嗽比較嚴重，睡不好。我沒有藥物過敏。請問這個藥怎麼吃？"},
tasks:[
{n:"任務卡 A",d:"你喉嚨痛三天了，還有點發燒。請你去診所看醫生，說明症狀，並問藥怎麼吃。"},
{n:"任務卡 B",d:"你吃了海鮮以後身上起紅疹。請你說明發生的過程，並告訴醫生你可能對海鮮過敏。"},
{n:"任務卡 C",d:"你要請病假，需要診斷證明。請你跟醫生說明用途並提出要求。"}],
quiz:[
"看圖選詞：（發燒／咳嗽／喉嚨痛／肚子痛）",
"聽音檔選答案：醫生說一天吃幾次？",
"句子排序：開始／我／喉嚨痛／從前天",
"選出最自然的說法：(A) 我痛喉嚨 (B) 我喉嚨痛 (C) 喉嚨我痛 (D) 痛我喉嚨",
"填空：我對海鮮＿＿＿。",
"「飯後吃」是什麼意思？(A) 吃飯以前吃 (B) 吃飯以後吃 (C) 不能吃飯 (D) 跟飯一起吃",
"醫生問「有咳嗽嗎？」，你晚上會咳，你會說：＿＿＿",
"錄音完成任務：向醫生說明你從三天前開始頭痛、想吐。"],
selfcheck:["我會說出哪裡不舒服。","我會說症狀從什麼時候開始。","我會回答有沒有過敏。","我聽得懂醫生說的吃藥方式。","我會問我需不需要休息。","我能自己一個人去看醫生。"],
ladder:[
{lv:"A1",task:"說出不舒服的部位",can:"我喉嚨痛，有一點發燒。"},
{lv:"A2",task:"加上時間、頻率和程度",can:"我從前天開始喉嚨痛，晚上咳嗽比較嚴重。"},
{lv:"B1",task:"完整描述病程並提問",can:"一開始只是喉嚨癢，後來越來越痛，吞口水也會痛。這個藥會不會想睡？"},
{lv:"B2",task:"說明用藥史、過敏並協調處置",can:"我之前吃這類的藥會過敏，可以換一種嗎？另外我需要一張診斷證明請假。"}]
}
);
TC.push(
{
id:"mrt",unit:"旅遊與交通",no:7,
title:"搭捷運與詢問方向",viTitle:"Đi tàu điện ngầm và hỏi đường",
task:{zh:"學完這一課，你可以自己搭捷運：問怎麼去某個地方、確認要坐哪一條線、在哪裡換車、從哪個出口出去，並且在坐錯的時候問人。",
vi:"Học xong bài này, bạn có thể tự đi tàu điện: hỏi đường đến một nơi, xác nhận tuyến nào, đổi tàu ở đâu, ra cửa nào, và hỏi người khác khi đi nhầm."},
warmup:["你在臺灣搭過捷運嗎？","你有沒有坐錯過車？那時候怎麼辦？","「幾號出口」為什麼重要？","在越南你平常怎麼移動？跟臺灣有什麼不同？"],
media:"捷運站內的路線圖、售票機、出口指示牌、悠遊卡。",
dialog:[
{who:"小美",zh:"不好意思，請問到臺北車站要怎麼走？",py:"Bù hǎoyìsi, qǐngwèn dào Táiběi chēzhàn yào zěnme zǒu?",vi:"Xin lỗi, cho hỏi đến ga Đài Bắc đi thế nào ạ?"},
{who:"路人",zh:"你搭捷運嗎？在這裡搭紅線就可以了。",py:"Nǐ dā jiéyùn ma? Zài zhèlǐ dā hóng xiàn jiù kěyǐ le.",vi:"Bạn đi tàu điện à? Ở đây bắt tuyến đỏ là được."},
{who:"小美",zh:"要坐幾站？",py:"Yào zuò jǐ zhàn?",vi:"Phải đi mấy trạm ạ?"},
{who:"路人",zh:"三站，不用換車。",py:"Sān zhàn, búyòng huànchē.",vi:"Ba trạm, không cần đổi tàu."},
{who:"小美",zh:"那我要從哪個出口出去？",py:"Nà wǒ yào cóng nǎge chūkǒu chūqù?",vi:"Vậy tôi ra cửa nào ạ?"},
{who:"路人",zh:"看你要去哪裡。去補習班的話，走 M6 出口比較近。",py:"Kàn nǐ yào qù nǎlǐ. Qù bǔxíbān dehuà, zǒu M6 chūkǒu bǐjiào jìn.",vi:"Tùy bạn muốn đi đâu. Nếu đến trung tâm luyện thi thì ra cửa M6 gần hơn."},
{who:"小美",zh:"謝謝！請問悠遊卡在哪裡加值？",py:"Xièxie! Qǐngwèn Yōuyóukǎ zài nǎlǐ jiāzhí?",vi:"Cảm ơn! Cho hỏi thẻ EasyCard nạp tiền ở đâu ạ?"},
{who:"路人",zh:"那邊的機器就可以，也可以在便利商店加。",py:"Nàbiān de jīqì jiù kěyǐ, yě kěyǐ zài biànlì shāngdiàn jiā.",vi:"Máy ở đằng kia là được, cũng có thể nạp ở cửa hàng tiện lợi."},
{who:"小美",zh:"太好了。如果坐過站怎麼辦？",py:"Tài hǎo le. Rúguǒ zuò guò zhàn zěnme bàn?",vi:"Tuyệt quá. Nếu đi quá trạm thì làm sao?"},
{who:"路人",zh:"下車走到對面月台，坐回來就好，不用再付錢。",py:"Xiàchē zǒu dào duìmiàn yuètái, zuò huílái jiù hǎo, búyòng zài fùqián.",vi:"Xuống tàu đi sang ke đối diện, đi ngược lại là được, không phải trả thêm tiền."},
{who:"小美",zh:"謝謝你，幫了我大忙。",py:"Xièxie nǐ, bāng le wǒ dà máng.",vi:"Cảm ơn bạn, giúp tôi rất nhiều."}],
keys:[
{zh:"請問到……要怎麼走？",vi:"Cho hỏi đến… đi thế nào?"},
{zh:"要坐幾站？",vi:"Phải đi mấy trạm?"},
{zh:"要在哪裡換車？",vi:"Đổi tàu ở đâu?"},
{zh:"我要從哪個出口出去？",vi:"Tôi ra cửa nào?"},
{zh:"悠遊卡在哪裡加值？",vi:"Thẻ EasyCard nạp tiền ở đâu?"},
{zh:"我好像坐過站了。",vi:"Hình như tôi đi quá trạm rồi."},
{zh:"謝謝你，幫了我大忙。",vi:"Cảm ơn bạn, giúp tôi rất nhiều."}],
vocab:[
{w:"捷運",py:"jiéyùn",vi:"tàu điện ngầm (MRT)",ex:"我每天搭捷運上班。"},
{w:"線",py:"xiàn",vi:"tuyến",ex:"你要搭紅線。"},
{w:"站",py:"zhàn",vi:"trạm, ga",ex:"再坐三站就到了。"},
{w:"換車",py:"huànchē",vi:"đổi tàu/xe",ex:"要在中正紀念堂換車。"},
{w:"出口",py:"chūkǒu",vi:"lối ra",ex:"走 M6 出口比較近。"},
{w:"月台",py:"yuètái",vi:"ke ga, sân ga",ex:"對面的月台是反方向。"},
{w:"悠遊卡",py:"Yōuyóukǎ",vi:"thẻ EasyCard",ex:"用悠遊卡比較方便。"},
{w:"加值",py:"jiāzhí",vi:"nạp tiền",ex:"我要加值五百塊。"},
{w:"坐過站",py:"zuò guò zhàn",vi:"đi quá trạm",ex:"我剛剛坐過站了。"},
{w:"方向",py:"fāngxiàng",vi:"hướng",ex:"你坐反方向了。"},
{w:"轉乘",py:"zhuǎnchéng",vi:"chuyển tuyến",ex:"這一站可以轉乘藍線。"},
{w:"班次",py:"bāncì",vi:"chuyến",ex:"下班車還要等六分鐘。"}],
vocabNote:"臺北捷運各線有顏色也有編號，臺灣人日常多半說顏色（紅線、藍線）。出口編號很重要，同一站不同出口可能差好幾百公尺。",
grammar:{pattern:"要……才……／……就好了",note:"「要……才……」說明必須先做什麼；「……就好了」表示這樣做就夠了，是問路時最常聽到的兩個回答。",
vi:"「要…才…」nói điều kiện bắt buộc; 「…就好了」nghĩa là làm vậy là đủ. Đây là hai câu trả lời hay gặp nhất khi hỏi đường.",
ex:["要在中正紀念堂換車才到得了。","搭紅線就好了，不用換車。","要走 M6 出口才近。","坐回來就好，不用再付錢。"],
swap:"＿＿＿就好了。（換成：搭公車／走過去／在這裡下車／用悠遊卡）"},
listening:[
{t:"聽對話選路線",d:"播放問路對話，學生在捷運路線圖上畫出正確路線。"},
{t:"聽內容選答案",d:"要坐幾站？(A) 兩站 (B) 三站 (C) 五站 (D) 六站"},
{t:"聽完填表",d:"填寫：搭哪一線＿＿＿／坐幾站＿＿＿／換不換車＿＿＿／哪個出口＿＿＿"},
{t:"判斷方向對不對",d:"聽車站廣播，判斷這班車是不是你要坐的方向。"},
{t:"聽完重說一次",d:"聽完後把路線指示轉述給另一個人聽。"}],
speaking:{q:["你要怎麼從你家到臺北車站？","如果坐過站了，你會怎麼做？","你怎麼問陌生人路？","請你完整說出一段問路的對話。"],
model:"不好意思，請問到臺北車站要怎麼走？要坐幾站？需要換車嗎？那我要從哪個出口出去？謝謝你，幫了我大忙。"},
tasks:[
{n:"任務卡 A",d:"你要從現在的位置去臺北車站，你不知道路。請你問路，並確認：搭哪一線、坐幾站、要不要換車、哪個出口。"},
{n:"任務卡 B",d:"你的悠遊卡餘額不足，出不了站。請你向站務人員說明並問怎麼處理。"},
{n:"任務卡 C",d:"朋友要來找你，請你用電話告訴他怎麼搭捷運到你家附近，包含換車和出口。"}],
quiz:[
"看圖選詞：（月台／出口／售票機／悠遊卡）",
"聽音檔選答案：說話的人要在哪一站換車？",
"句子排序：怎麼走／請問／臺北車站／到／要",
"選出最自然的說法：(A) 我要出去哪個出口 (B) 我要從哪個出口出去 (C) 哪個出口我出去 (D) 出去哪個出口我要",
"填空：搭紅線＿＿＿，不用換車。",
"「坐過站」是什麼意思？(A) 坐錯線 (B) 坐過頭了 (C) 沒位子坐 (D) 站著坐車",
"你發現自己坐反方向了，你會說：＿＿＿",
"錄音完成任務：問路到某個地方，並確認出口編號。"],
selfcheck:["我會問怎麼到某個地方。","我聽得懂要坐幾站、要不要換車。","我會問出口編號。","我會加值悠遊卡。","坐錯車的時候我知道怎麼問人。","我能自己一個人搭捷運到陌生的地方。"],
ladder:[
{lv:"A1",task:"問到某地怎麼走",can:"請問到臺北車站要怎麼走？"},
{lv:"A2",task:"確認路線細節",can:"要坐幾站？要換車嗎？從哪個出口出去？"},
{lv:"B1",task:"處理坐錯車或卡片問題",can:"我好像坐過站了，請問要在哪裡換到反方向？"},
{lv:"B2",task:"把複雜路線說給別人聽",can:"你先搭紅線到中正紀念堂，換綠線坐兩站，出來走三號出口，再走大概五分鐘就到了。"}]
},
{
id:"train",unit:"旅遊與交通",no:8,
title:"購買火車票",viTitle:"Mua vé tàu hỏa",
task:{zh:"學完這一課，你可以在火車站買票：說出目的地、日期、時間和張數，選擇車種和座位，聽懂月台與發車時間，並且處理改票或退票。",
vi:"Học xong bài này, bạn có thể mua vé ở ga tàu: nói điểm đến, ngày, giờ, số vé, chọn loại tàu và chỗ ngồi, hiểu ke ga và giờ khởi hành, xử lý đổi vé hoặc trả vé."},
warmup:["你搭過臺灣的火車嗎？去哪裡？","你知道自強號、莒光號差在哪裡嗎？","買票要說哪些資訊？","如果趕不上車，票還能用嗎？"],
media:"火車站售票窗口、時刻表看板、車票正面、月台號碼牌。",
dialog:[
{who:"旅客",zh:"你好，我要買到花蓮的票。",py:"Nǐ hǎo, wǒ yào mǎi dào Huālián de piào.",vi:"Xin chào, tôi muốn mua vé đi Hoa Liên."},
{who:"售票員",zh:"什麼時候的？",py:"Shénme shíhòu de?",vi:"Vé lúc nào ạ?"},
{who:"旅客",zh:"這個星期六早上，兩張。",py:"Zhège xīngqíliù zǎoshang, liǎng zhāng.",vi:"Sáng thứ Bảy này, hai vé."},
{who:"售票員",zh:"自強號八點十分，還有位子。可以嗎？",py:"Zìqiánghào bā diǎn shí fēn, hái yǒu wèizi. Kěyǐ ma?",vi:"Tàu Tự Cường 8 giờ 10, còn chỗ. Được không ạ?"},
{who:"旅客",zh:"可以。有靠窗的位子嗎？",py:"Kěyǐ. Yǒu kào chuāng de wèizi ma?",vi:"Được. Có chỗ cạnh cửa sổ không ạ?"},
{who:"售票員",zh:"有，兩個連在一起的。單程還是來回？",py:"Yǒu, liǎng ge lián zài yìqǐ de. Dānchéng háishì láihuí?",vi:"Có, hai chỗ liền nhau. Một chiều hay khứ hồi ạ?"},
{who:"旅客",zh:"來回，回程星期天下午。",py:"Láihuí, huíchéng xīngqítiān xiàwǔ.",vi:"Khứ hồi, chiều về Chủ nhật buổi chiều."},
{who:"售票員",zh:"一共一千四百四十元。",py:"Yígòng yìqiān sìbǎi sìshí yuán.",vi:"Tổng cộng một nghìn bốn trăm bốn mươi đồng."},
{who:"旅客",zh:"請問在幾號月台？",py:"Qǐngwèn zài jǐ hào yuètái?",vi:"Cho hỏi ở ke số mấy ạ?"},
{who:"售票員",zh:"第三月台，當天請提早十分鐘到。",py:"Dì-sān yuètái, dāngtiān qǐng tízǎo shí fēnzhōng dào.",vi:"Ke số ba, hôm đó xin đến sớm mười phút."},
{who:"旅客",zh:"好。如果那天不能去，可以退票嗎？",py:"Hǎo. Rúguǒ nà tiān bù néng qù, kěyǐ tuìpiào ma?",vi:"Vâng. Nếu hôm đó không đi được, có thể trả vé không?"},
{who:"售票員",zh:"可以，開車前退票要收一點手續費。",py:"Kěyǐ, kāichē qián tuìpiào yào shōu yìdiǎn shǒuxùfèi.",vi:"Được, trả vé trước giờ tàu chạy sẽ thu một chút phí."}],
keys:[
{zh:"我要買到……的票。",vi:"Tôi muốn mua vé đi…"},
{zh:"……，兩張。",vi:"…, hai vé."},
{zh:"有靠窗的位子嗎？",vi:"Có chỗ cạnh cửa sổ không?"},
{zh:"單程／來回",vi:"Một chiều / khứ hồi"},
{zh:"請問在幾號月台？",vi:"Cho hỏi ở ke số mấy?"},
{zh:"可以改票嗎？／可以退票嗎？",vi:"Đổi vé được không? / Trả vé được không?"},
{zh:"下一班是幾點？",vi:"Chuyến sau mấy giờ?"}],
vocab:[
{w:"車票",py:"chēpiào",vi:"vé xe/tàu",ex:"我的車票不見了。"},
{w:"自強號",py:"Zìqiánghào",vi:"tàu Tự Cường (loại nhanh nhất của TRA)",ex:"自強號比較快也比較貴。"},
{w:"單程",py:"dānchéng",vi:"một chiều",ex:"我只要單程票。"},
{w:"來回",py:"láihuí",vi:"khứ hồi",ex:"買來回票比較划算。"},
{w:"靠窗",py:"kào chuāng",vi:"cạnh cửa sổ",ex:"我想坐靠窗的位子。"},
{w:"座位",py:"zuòwèi",vi:"chỗ ngồi",ex:"這班車還有座位嗎？"},
{w:"月台",py:"yuètái",vi:"ke ga",ex:"在第三月台上車。"},
{w:"發車",py:"fāchē",vi:"khởi hành",ex:"八點十分發車。"},
{w:"誤點",py:"wùdiǎn",vi:"trễ giờ",ex:"這班車誤點二十分鐘。"},
{w:"退票",py:"tuìpiào",vi:"trả vé",ex:"開車前可以退票。"},
{w:"改票",py:"gǎipiào",vi:"đổi vé",ex:"我想改成下午的班次。"},
{w:"手續費",py:"shǒuxùfèi",vi:"phí thủ tục",ex:"退票要收手續費。"}],
vocabNote:"臺鐵常見車種由快到慢大致是：自強號、莒光號、區間車。訂票可以用臺鐵網站或 APP，超商也可以取票，這對學生很實用。",
grammar:{pattern:"如果……，可以……嗎？",note:"先假設一個狀況，再問對方能不能處理。買票、訂房、請假都用得到。",
vi:"Giả định một tình huống rồi hỏi đối phương có xử lý được không. Dùng khi mua vé, đặt phòng, xin nghỉ.",
ex:["如果那天不能去，可以退票嗎？","如果我想早一點回來，可以改票嗎？","如果車誤點，可以換下一班嗎？","如果我遲到了，可以搭下一班嗎？"],
swap:"如果＿＿＿，可以＿＿＿嗎？（換成：位子不夠／臨時有事 ＋ 加開一張／改時間）"},
listening:[
{t:"聽對話選車票",d:"播放買票對話，學生從四張車票圖中選出正確的日期、時間和車種。"},
{t:"聽內容選答案",d:"這班車幾點發車？(A) 8:00 (B) 8:10 (C) 8:40 (D) 9:10"},
{t:"聽完填表",d:"填寫：目的地＿＿＿／日期＿＿＿／車種＿＿＿／張數＿＿＿／月台＿＿＿"},
{t:"聽廣播判斷狀況",d:"聽車站廣播，判斷是誤點、月台變更、還是取消班次。"},
{t:"聽完重說一次",d:"聽完後把購票資訊完整複述一次。"}],
speaking:{q:["你想去哪裡？什麼時候去？","你要買單程還是來回？為什麼？","你想坐什麼位子？","請完整說出你的購票需求。"],
model:"你好，我要買到花蓮的票，這個星期六早上，兩張。有靠窗的位子嗎？來回，回程星期天下午。請問在幾號月台？"},
tasks:[
{n:"任務卡 A",d:"你要買週六早上到花蓮的票，兩張，來回，想坐靠窗。請完成購票並問清楚月台。"},
{n:"任務卡 B",d:"你買好的票時間不對，你要改成下午的班次。請你說明並詢問手續費。"},
{n:"任務卡 C",d:"你的火車誤點三十分鐘，你會趕不上接下來的行程。請你向站務人員說明並問可以怎麼辦。"}],
quiz:[
"看圖選詞：（車票／月台／時刻表／售票窗口）",
"聽音檔選答案：旅客買了幾張票？",
"句子排序：的票／我要／到花蓮／買",
"選出最自然的說法：(A) 我要票花蓮 (B) 我要買到花蓮的票 (C) 花蓮票我買 (D) 買花蓮我要票",
"填空：如果那天不能去，可以＿＿＿嗎？",
"「來回票」是什麼意思？(A) 只去 (B) 去和回都有 (C) 可以換人用 (D) 站票",
"售票員問「單程還是來回？」，你當天要回來，你會說：＿＿＿",
"錄音完成任務：買星期六早上到臺南的自強號，一張，靠走道。"],
selfcheck:["我會說出目的地、日期和時間。","我會說要幾張、單程還是來回。","我會指定座位。","我聽得懂月台和發車時間。","我會問改票和退票。","我能自己一個人買到火車票。"],
ladder:[
{lv:"A1",task:"說出目的地和張數",can:"我要買到花蓮的票，兩張。"},
{lv:"A2",task:"加上時間、車種和座位需求",can:"星期六早上的自強號，兩張，要靠窗的。"},
{lv:"B1",task:"處理改票、退票與時間調整",can:"我想把回程改成星期天晚上，請問要多少手續費？"},
{lv:"B2",task:"處理誤點等突發狀況並爭取方案",can:"這班車誤點，我趕不上接駁車了。可以幫我改搭下一班，或是看看有沒有別的路線？"}]
},
{
id:"hotel",unit:"旅遊與交通",no:9,
title:"飯店入住與反映問題",viTitle:"Nhận phòng khách sạn và phản ánh vấn đề",
task:{zh:"學完這一課，你可以完成飯店入住：報訂房資料、出示證件、問早餐和退房時間，並且在房間有問題的時候向櫃台反映、要求處理。",
vi:"Học xong bài này, bạn có thể nhận phòng khách sạn: báo thông tin đặt phòng, xuất trình giấy tờ, hỏi bữa sáng và giờ trả phòng, và phản ánh khi phòng có vấn đề."},
warmup:["你住過臺灣的飯店或民宿嗎？","入住的時候要準備什麼？","房間有問題你會直接說嗎？還是忍耐？","在越南和臺灣，退房時間一樣嗎？"],
media:"飯店櫃台、房卡、早餐券、房間內冷氣或熱水器的照片。",
dialog:[
{who:"旅客",zh:"你好，我有訂房，姓阮。",py:"Nǐ hǎo, wǒ yǒu dìngfáng, xìng Ruǎn.",vi:"Xin chào, tôi có đặt phòng, họ Nguyễn."},
{who:"櫃台",zh:"阮小姐您好，兩晚雙人房，對嗎？",py:"Ruǎn xiǎojiě nín hǎo, liǎng wǎn shuāngrénfáng, duì ma?",vi:"Chào cô Nguyễn, phòng đôi hai đêm, đúng không ạ?"},
{who:"旅客",zh:"對。請問可以提早入住嗎？",py:"Duì. Qǐngwèn kěyǐ tízǎo rùzhù ma?",vi:"Đúng ạ. Cho hỏi có thể nhận phòng sớm không?"},
{who:"櫃台",zh:"現在還在整理，大概一點以後可以。行李可以先寄放。",py:"Xiànzài hái zài zhěnglǐ, dàgài yì diǎn yǐhòu kěyǐ. Xínglǐ kěyǐ xiān jìfàng.",vi:"Bây giờ đang dọn, khoảng sau một giờ được ạ. Hành lý có thể gửi trước."},
{who:"旅客",zh:"好。請問早餐幾點到幾點？",py:"Hǎo. Qǐngwèn zǎocān jǐ diǎn dào jǐ diǎn?",vi:"Vâng. Cho hỏi bữa sáng từ mấy giờ đến mấy giờ?"},
{who:"櫃台",zh:"七點到十點，在二樓。退房是中午十二點。",py:"Qī diǎn dào shí diǎn, zài èr lóu. Tuìfáng shì zhōngwǔ shí'èr diǎn.",vi:"Từ bảy giờ đến mười giờ, ở tầng hai. Trả phòng là mười hai giờ trưa."},
{who:"旅客",zh:"（晚上打電話）不好意思，房間的熱水好像壞了。",py:"Bù hǎoyìsi, fángjiān de rèshuǐ hǎoxiàng huài le.",vi:"Xin lỗi, nước nóng trong phòng hình như hỏng rồi."},
{who:"櫃台",zh:"很抱歉，我馬上請人上去看。",py:"Hěn bàoqiàn, wǒ mǎshàng qǐng rén shàngqù kàn.",vi:"Rất xin lỗi, tôi sẽ cho người lên xem ngay."},
{who:"旅客",zh:"另外，冷氣的聲音很大，晚上很吵。",py:"Lìngwài, lěngqì de shēngyīn hěn dà, wǎnshang hěn chǎo.",vi:"Ngoài ra, điều hòa kêu rất to, buổi tối rất ồn."},
{who:"櫃台",zh:"真不好意思。我們還有一間空房，要幫您換房間嗎？",py:"Zhēn bù hǎoyìsi. Wǒmen hái yǒu yì jiān kòngfáng, yào bāng nín huàn fángjiān ma?",vi:"Thật xin lỗi. Chúng tôi còn một phòng trống, có cần đổi phòng cho quý khách không?"},
{who:"旅客",zh:"那太好了，麻煩你。",py:"Nà tài hǎo le, máfan nǐ.",vi:"Vậy thì tốt quá, làm phiền bạn."},
{who:"櫃台",zh:"沒問題，我請人幫您搬行李。",py:"Méi wèntí, wǒ qǐng rén bāng nín bān xínglǐ.",vi:"Không vấn đề gì, tôi sẽ cho người giúp quý khách chuyển hành lý."}],
keys:[
{zh:"我有訂房，姓……",vi:"Tôi có đặt phòng, họ…"},
{zh:"可以提早入住嗎？",vi:"Có thể nhận phòng sớm không?"},
{zh:"行李可以先寄放嗎？",vi:"Hành lý gửi trước được không?"},
{zh:"早餐幾點到幾點？",vi:"Bữa sáng từ mấy giờ đến mấy giờ?"},
{zh:"退房是幾點？",vi:"Trả phòng lúc mấy giờ?"},
{zh:"房間的……好像壞了。",vi:"… trong phòng hình như hỏng rồi."},
{zh:"可以幫我換房間嗎？",vi:"Có thể đổi phòng giúp tôi không?"}],
vocab:[
{w:"訂房",py:"dìngfáng",vi:"đặt phòng",ex:"我上個星期就訂房了。"},
{w:"入住",py:"rùzhù",vi:"nhận phòng",ex:"三點以後才能入住。"},
{w:"退房",py:"tuìfáng",vi:"trả phòng",ex:"退房是中午十二點。"},
{w:"雙人房",py:"shuāngrénfáng",vi:"phòng đôi",ex:"我要一間雙人房。"},
{w:"寄放",py:"jìfàng",vi:"gửi (đồ)",ex:"行李可以寄放在櫃台。"},
{w:"房卡",py:"fángkǎ",vi:"thẻ phòng",ex:"房卡不見了怎麼辦？"},
{w:"熱水",py:"rèshuǐ",vi:"nước nóng",ex:"浴室沒有熱水。"},
{w:"冷氣",py:"lěngqì",vi:"điều hòa",ex:"冷氣不冷。"},
{w:"吵",py:"chǎo",vi:"ồn",ex:"隔壁很吵，我睡不著。"},
{w:"壞",py:"huài",vi:"hỏng",ex:"電視好像壞了。"},
{w:"換房間",py:"huàn fángjiān",vi:"đổi phòng",ex:"可以幫我換房間嗎？"},
{w:"抱歉",py:"bàoqiàn",vi:"xin lỗi (trang trọng)",ex:"很抱歉，造成您的不便。"}],
vocabNote:"臺灣飯店一般下午三點入住、隔天中午十二點退房。反映問題時用「好像」會比直接說「壞了」客氣，也留給對方確認的空間。",
grammar:{pattern:"……好像……了",note:"用來委婉指出問題。不把話說死，聽起來像是在提醒而不是抱怨，對方比較好接。",
vi:"Dùng để nêu vấn đề một cách nhẹ nhàng, nghe như nhắc nhở chứ không phải phàn nàn.",
ex:["房間的熱水好像壞了。","冷氣好像不太冷。","門好像關不起來。","隔壁好像在施工，有點吵。"],
swap:"＿＿＿好像＿＿＿了。（換成：燈／電視／馬桶 ＋ 不會亮／沒有訊號／堵住）"},
listening:[
{t:"聽對話選圖片",d:"播放四段反映問題的對話，學生從圖片中選出壞掉的設備。"},
{t:"聽內容選答案",d:"早餐幾點開始？(A) 六點 (B) 七點 (C) 八點 (D) 十點"},
{t:"聽完填表",d:"填寫：房型＿＿＿／住幾晚＿＿＿／早餐時間＿＿＿／退房時間＿＿＿"},
{t:"判斷櫃台怎麼處理",d:"聽四段回覆，判斷櫃台是要派人修、換房間、還是無法處理。"},
{t:"聽完重說一次",d:"聽完後把房間的問題向另一位同事轉述。"}],
speaking:{q:["你到飯店會先說什麼？","你會問哪些事情？","房間的冷氣很吵，你會怎麼說？","請完整說出一次入住加反映問題。"],
model:"你好，我有訂房，姓阮，兩晚雙人房。請問可以提早入住嗎？早餐幾點到幾點？……不好意思，房間的熱水好像壞了，冷氣也很吵，可以幫我換房間嗎？"},
tasks:[
{n:"任務卡 A",d:"你比入住時間早三個小時到飯店。請你辦理入住，並詢問行李可不可以先寄放。"},
{n:"任務卡 B",d:"你的房間熱水不熱、冷氣很吵。請你打電話到櫃台反映，並要求換房間。"},
{n:"任務卡 C",d:"你想延後退房兩個小時。請你詢問可不可以，以及需不需要加錢。"}],
quiz:[
"看圖選詞：（房卡／行李／冷氣／早餐）",
"聽音檔選答案：客人反映的是什麼問題？",
"句子排序：訂房／我／姓阮／有",
"選出最自然的說法：(A) 熱水壞 (B) 房間的熱水好像壞了 (C) 熱水沒有好 (D) 壞熱水了",
"填空：可以幫我＿＿＿房間嗎？",
"「寄放行李」是什麼意思？(A) 把行李寄回家 (B) 暫時放在飯店 (C) 丟掉行李 (D) 買新行李",
"櫃台說「三點以後才能入住」，現在是十二點，你會說：＿＿＿",
"錄音完成任務：辦理入住並反映房間的燈壞了。"],
selfcheck:["我會報訂房資料辦理入住。","我會問早餐和退房時間。","我會請飯店寄放行李。","我會用「好像」委婉反映問題。","我會要求換房間或請人來修。","我能自己一個人完成入住和反映問題。"],
ladder:[
{lv:"A1",task:"報上姓名與訂房",can:"你好，我有訂房，姓阮。"},
{lv:"A2",task:"詢問基本服務資訊",can:"早餐幾點到幾點？退房是幾點？"},
{lv:"B1",task:"具體描述房間問題並提出要求",can:"房間的熱水好像壞了，可以請人上來看一下嗎？"},
{lv:"B2",task:"協調補償或替代方案",can:"昨晚冷氣太吵我幾乎沒睡。可以幫我換一間安靜的房間嗎？或者這一晚能不能有些折扣？"}]
},
{
id:"firstday",unit:"工作與職場",no:10,
title:"第一天上班",viTitle:"Ngày đầu tiên đi làm",
task:{zh:"學完這一課，你可以度過上班第一天：跟同事自我介紹、問清楚上下班時間和吃飯時間、知道東西放在哪裡，並且在不懂的時候開口請教。",
vi:"Học xong bài này, bạn có thể vượt qua ngày làm đầu tiên: tự giới thiệu với đồng nghiệp, hỏi rõ giờ làm và giờ ăn, biết đồ để ở đâu, và biết hỏi khi chưa hiểu."},
warmup:["你上班第一天最緊張什麼？","第一天要問哪些事情才不會出錯？","不懂的時候你會馬上問，還是先自己想？","在越南的公司，新人第一天通常做什麼？"],
media:"辦公室座位、打卡機、茶水間、員工識別證。",
dialog:[
{who:"主管",zh:"大家好，這位是新來的同事阮小姐。",py:"Dàjiā hǎo, zhè wèi shì xīn lái de tóngshì Ruǎn xiǎojiě.",vi:"Chào mọi người, đây là đồng nghiệp mới, cô Nguyễn."},
{who:"小美",zh:"大家好，我叫阮氏梅，叫我小美就可以了。",py:"Dàjiā hǎo, wǒ jiào Ruǎn Shì Méi, jiào wǒ Xiǎo-Měi jiù kěyǐ le.",vi:"Chào mọi người, tôi tên Nguyễn Thị Mai, gọi tôi là Tiểu Mai là được."},
{who:"小美",zh:"我剛來，很多不懂的地方，請大家多多指教。",py:"Wǒ gāng lái, hěn duō bù dǒng de dìfāng, qǐng dàjiā duōduō zhǐjiào.",vi:"Tôi mới đến, còn nhiều chỗ chưa hiểu, mong mọi người chỉ bảo thêm."},
{who:"同事",zh:"別緊張，有問題隨時問我。你的位子在這裡。",py:"Bié jǐnzhāng, yǒu wèntí suíshí wèn wǒ. Nǐ de wèizi zài zhèlǐ.",vi:"Đừng lo lắng, có gì cứ hỏi tôi. Chỗ ngồi của bạn ở đây."},
{who:"小美",zh:"謝謝。請問幾點上班？要打卡嗎？",py:"Xièxie. Qǐngwèn jǐ diǎn shàngbān? Yào dǎkǎ ma?",vi:"Cảm ơn. Cho hỏi mấy giờ vào làm? Có phải chấm công không?"},
{who:"同事",zh:"九點上班，六點下班，進出都要刷識別證。",py:"Jiǔ diǎn shàngbān, liù diǎn xiàbān, jìnchū dōu yào shuā shíbiézhèng.",vi:"Chín giờ vào làm, sáu giờ tan, ra vào đều phải quẹt thẻ nhân viên."},
{who:"小美",zh:"午休是幾點到幾點？",py:"Wǔxiū shì jǐ diǎn dào jǐ diǎn?",vi:"Nghỉ trưa từ mấy giờ đến mấy giờ?"},
{who:"同事",zh:"十二點到一點。茶水間在那邊，冰箱可以放午餐。",py:"Shí'èr diǎn dào yì diǎn. Cháshuǐjiān zài nàbiān, bīngxiāng kěyǐ fàng wǔcān.",vi:"Mười hai giờ đến một giờ. Phòng nước ở đằng kia, tủ lạnh có thể để cơm trưa."},
{who:"小美",zh:"了解。如果有事情要請假，要跟誰說？",py:"Liǎojiě. Rúguǒ yǒu shìqíng yào qǐngjià, yào gēn shéi shuō?",vi:"Tôi hiểu rồi. Nếu có việc cần xin nghỉ thì nói với ai ạ?"},
{who:"同事",zh:"先跟主管講，再在系統上送假單。",py:"Xiān gēn zhǔguǎn jiǎng, zài zài xìtǒng shàng sòng jiàdān.",vi:"Nói với quản lý trước, rồi gửi đơn nghỉ trên hệ thống."},
{who:"小美",zh:"我記下來了，謝謝你這麼詳細。",py:"Wǒ jì xiàlái le, xièxie nǐ zhème xiángxì.",vi:"Tôi ghi lại rồi, cảm ơn bạn đã nói kỹ như vậy."}],
keys:[
{zh:"我剛來，請大家多多指教。",vi:"Tôi mới đến, mong mọi người chỉ bảo."},
{zh:"請問幾點上班／下班？",vi:"Cho hỏi mấy giờ vào làm / tan làm?"},
{zh:"午休是幾點到幾點？",vi:"Nghỉ trưa từ mấy giờ đến mấy giờ?"},
{zh:"要打卡嗎？",vi:"Có phải chấm công không?"},
{zh:"這個要跟誰說？",vi:"Việc này phải nói với ai?"},
{zh:"不好意思，我可以問一個問題嗎？",vi:"Xin lỗi, tôi hỏi một câu được không?"},
{zh:"我記下來了。",vi:"Tôi ghi lại rồi."}],
vocab:[
{w:"同事",py:"tóngshì",vi:"đồng nghiệp",ex:"她是我的同事。"},
{w:"主管",py:"zhǔguǎn",vi:"quản lý, cấp trên",ex:"這件事要先跟主管說。"},
{w:"指教",py:"zhǐjiào",vi:"chỉ bảo",ex:"請大家多多指教。"},
{w:"打卡",py:"dǎkǎ",vi:"chấm công",ex:"上班要打卡。"},
{w:"識別證",py:"shíbiézhèng",vi:"thẻ nhân viên",ex:"進出都要刷識別證。"},
{w:"午休",py:"wǔxiū",vi:"nghỉ trưa",ex:"午休一個小時。"},
{w:"茶水間",py:"cháshuǐjiān",vi:"phòng nước, pantry",ex:"茶水間有微波爐。"},
{w:"請假",py:"qǐngjià",vi:"xin nghỉ",ex:"我明天要請假。"},
{w:"假單",py:"jiàdān",vi:"đơn xin nghỉ",ex:"記得在系統上送假單。"},
{w:"系統",py:"xìtǒng",vi:"hệ thống",ex:"資料要輸入系統。"},
{w:"了解",py:"liǎojiě",vi:"hiểu rồi",ex:"了解，我知道怎麼做了。"},
{w:"詳細",py:"xiángxì",vi:"chi tiết, kỹ",ex:"謝謝你說得這麼詳細。"}],
vocabNote:"「請大家多多指教」是臺灣職場第一天幾乎一定會說的一句話，越南學生說出來會讓同事印象很好。回應通常是「不會不會」「有問題隨時問」。",
grammar:{pattern:"不好意思，我可以……嗎？",note:"職場上開口打斷別人、提出請求時最安全的開頭。先說「不好意思」，對方比較不會覺得被打擾。",
vi:"Cách mở lời an toàn nhất khi cần ngắt lời hoặc nhờ vả ở nơi làm việc.",
ex:["不好意思，我可以問一個問題嗎？","不好意思，我可以看一下上次的資料嗎？","不好意思，我可以晚十分鐘再交嗎？","不好意思，我可以先請教你一件事嗎？"],
swap:"不好意思，我可以＿＿＿嗎？（換成：借一下印表機／請你再說一次／中午出去一下）"},
listening:[
{t:"聽對話選圖片",d:"播放同事介紹環境的內容，學生在辦公室平面圖上找出位置。"},
{t:"聽內容選答案",d:"午休是幾點到幾點？(A) 11-12 (B) 12-1 (C) 12-2 (D) 1-2"},
{t:"聽完填表",d:"填寫：上班時間＿＿＿／下班時間＿＿＿／午休＿＿＿／請假流程＿＿＿"},
{t:"判斷該問誰",d:"聽四種狀況，判斷應該問主管、問同事、還是自己查系統。"},
{t:"聽完重說一次",d:"聽完後把公司的規定講給另一位新人聽。"}],
speaking:{q:["請你向新同事自我介紹。","第一天你會問哪三件事？","不懂的時候你會怎麼開口？","請完整說出你的第一天。"],
model:"大家好，我叫阮氏梅，叫我小美就可以了。我剛來，很多不懂的地方，請大家多多指教。不好意思，我可以問一下幾點上班、午休是幾點到幾點嗎？"},
tasks:[
{n:"任務卡 A",d:"今天是你上班第一天。請你向同事自我介紹，並問清楚上下班時間、午休時間和打卡方式。"},
{n:"任務卡 B",d:"你不知道文件要交給誰、也不知道用哪個系統。請你開口請教同事。"},
{n:"任務卡 C",d:"同事說得很快，你沒聽懂。請你有禮貌地請他再說一次或說慢一點。"}],
quiz:[
"看圖選詞：（打卡／識別證／茶水間／主管）",
"聽音檔選答案：新人要先跟誰說才能請假？",
"句子排序：多多指教／請／大家／我剛來",
"選出最自然的說法：(A) 我問問題可以嗎 (B) 不好意思，我可以問一個問題嗎 (C) 問題我要問 (D) 給我問問題",
"填空：午休是幾點＿＿＿幾點？",
"「請大家多多指教」通常什麼時候說？(A) 離職的時候 (B) 第一天報到 (C) 生氣的時候 (D) 領薪水的時候",
"同事說「有問題隨時問我」，你可以回：＿＿＿",
"錄音完成任務：向新同事自我介紹並問三個問題。"],
selfcheck:["我會向同事自我介紹。","我會說「請大家多多指教」。","我會問上下班和午休時間。","我知道請假要先跟誰說。","不懂的時候我會開口問。","我能自己度過上班第一天。"],
ladder:[
{lv:"A1",task:"自我介紹並打招呼",can:"大家好，我叫小美，請多多指教。"},
{lv:"A2",task:"詢問上班的基本規定",can:"請問幾點上班？午休是幾點到幾點？要打卡嗎？"},
{lv:"B1",task:"主動確認流程與負責人",can:"如果要請假，是先跟主管講，還是直接在系統上送假單？"},
{lv:"B2",task:"在不確定時得體地確認與複述",can:"我想確認一下我理解得對不對：文件先給你看過，再送主管簽，這樣嗎？"}]
},
{
id:"leave",unit:"工作與職場",no:11,
title:"向主管請假",viTitle:"Xin nghỉ phép với cấp trên",
task:{zh:"學完這一課，你可以向主管請假：說明日期和原因、交代工作怎麼安排、提出補班或代理的方式，並且處理主管不同意時的協調。",
vi:"Học xong bài này, bạn có thể xin nghỉ với quản lý: nêu ngày và lý do, bàn giao công việc, đề xuất người thay hoặc làm bù, và thương lượng khi quản lý chưa đồng ý."},
warmup:["你請過假嗎？怎麼跟主管說？","請假要提前多久說？","請假的時候需要說明原因嗎？","越南和臺灣的請假習慣一樣嗎？"],
media:"請假系統畫面、行事曆上圈起來的日期、辦公室裡兩人談話的照片。",
dialog:[
{who:"小美",zh:"經理，不好意思，可以耽誤你幾分鐘嗎？",py:"Jīnglǐ, bù hǎoyìsi, kěyǐ dānwù nǐ jǐ fēnzhōng ma?",vi:"Giám đốc, xin lỗi, tôi làm phiền anh vài phút được không?"},
{who:"經理",zh:"可以，什麼事？",py:"Kěyǐ, shénme shì?",vi:"Được, có việc gì?"},
{who:"小美",zh:"我想請下星期五一天的假。",py:"Wǒ xiǎng qǐng xià xīngqíwǔ yì tiān de jià.",vi:"Tôi muốn xin nghỉ một ngày thứ Sáu tuần sau."},
{who:"經理",zh:"是有什麼事嗎？",py:"Shì yǒu shénme shì ma?",vi:"Có việc gì à?"},
{who:"小美",zh:"我媽媽從越南來，我要去機場接她。",py:"Wǒ māma cóng Yuènán lái, wǒ yào qù jīchǎng jiē tā.",vi:"Mẹ tôi từ Việt Nam sang, tôi phải ra sân bay đón mẹ."},
{who:"經理",zh:"星期五那天不是要交報告嗎？",py:"Xīngqíwǔ nà tiān bú shì yào jiāo bàogào ma?",vi:"Thứ Sáu hôm đó không phải phải nộp báo cáo sao?"},
{who:"小美",zh:"我會星期四先做完，星期四下班前交給你。",py:"Wǒ huì xīngqísì xiān zuò wán, xīngqísì xiàbān qián jiāo gěi nǐ.",vi:"Tôi sẽ làm xong trước vào thứ Năm, nộp cho anh trước giờ tan làm thứ Năm."},
{who:"經理",zh:"那客戶如果打電話來呢？",py:"Nà kèhù rúguǒ dǎ diànhuà lái ne?",vi:"Vậy nếu khách hàng gọi đến thì sao?"},
{who:"小美",zh:"我已經跟阿明說好，那天請他幫我接。",py:"Wǒ yǐjīng gēn Ā-Míng shuō hǎo, nà tiān qǐng tā bāng wǒ jiē.",vi:"Tôi đã nói với A Minh rồi, hôm đó nhờ anh ấy nghe giúp."},
{who:"經理",zh:"好，那沒問題。記得在系統上送假單。",py:"Hǎo, nà méi wèntí. Jìde zài xìtǒng shàng sòng jiàdān.",vi:"Được, vậy không vấn đề gì. Nhớ gửi đơn nghỉ trên hệ thống."},
{who:"小美",zh:"好的，我馬上送。謝謝經理。",py:"Hǎo de, wǒ mǎshàng sòng. Xièxie jīnglǐ.",vi:"Vâng, tôi gửi ngay. Cảm ơn giám đốc."},
{who:"經理",zh:"不客氣。回來以後跟我說一下報告的狀況。",py:"Bú kèqì. Huílái yǐhòu gēn wǒ shuō yíxià bàogào de zhuàngkuàng.",vi:"Không có gì. Sau khi quay lại nói với tôi tình hình báo cáo nhé."}],
keys:[
{zh:"可以耽誤你幾分鐘嗎？",vi:"Tôi làm phiền anh/chị vài phút được không?"},
{zh:"我想請……的假。",vi:"Tôi muốn xin nghỉ…"},
{zh:"因為……，所以我需要請假。",vi:"Vì… nên tôi cần xin nghỉ."},
{zh:"我會先把……做完。",vi:"Tôi sẽ làm xong… trước."},
{zh:"那天請……幫我代理。",vi:"Hôm đó nhờ… làm thay tôi."},
{zh:"我馬上在系統上送假單。",vi:"Tôi sẽ gửi đơn nghỉ trên hệ thống ngay."},
{zh:"如果不方便，我可以改時間。",vi:"Nếu không tiện, tôi có thể đổi thời gian."}],
vocab:[
{w:"請假",py:"qǐngjià",vi:"xin nghỉ",ex:"我下星期要請假一天。"},
{w:"耽誤",py:"dānwù",vi:"làm mất thời gian, làm phiền",ex:"可以耽誤你五分鐘嗎？"},
{w:"經理",py:"jīnglǐ",vi:"giám đốc, quản lý",ex:"這件事要跟經理報告。"},
{w:"報告",py:"bàogào",vi:"báo cáo",ex:"報告星期五要交。"},
{w:"客戶",py:"kèhù",vi:"khách hàng",ex:"客戶下午會來。"},
{w:"代理",py:"dàilǐ",vi:"làm thay",ex:"那天請阿明代理我的工作。"},
{w:"交",py:"jiāo",vi:"nộp",ex:"我星期四就交。"},
{w:"事假",py:"shìjià",vi:"nghỉ việc riêng",ex:"我要請一天事假。"},
{w:"病假",py:"bìngjià",vi:"nghỉ ốm",ex:"發燒的話可以請病假。"},
{w:"補",py:"bǔ",vi:"bù lại",ex:"我可以週末補上。"},
{w:"狀況",py:"zhuàngkuàng",vi:"tình hình",ex:"回來跟我說一下狀況。"},
{w:"提前",py:"tíqián",vi:"trước, sớm hơn",ex:"請假要提前三天說。"}],
vocabNote:"臺灣職場請假通常要提前告知，而且主管最在意的往往不是原因，而是「你的工作誰接」。學生只要主動說明交接方式，成功率會高很多。",
grammar:{pattern:"我會先……，再……",note:"用來說明你已經把事情安排好了。請假時講出這一句，主管的顧慮就少一半。",
vi:"Dùng để cho thấy bạn đã sắp xếp công việc. Nói câu này khi xin nghỉ sẽ giảm bớt lo lắng của cấp trên.",
ex:["我會先把報告做完，再請假。","我會先交接給阿明，再去機場。","我會先處理客戶的問題，再下班。","我會先送假單，再跟同事說一聲。"],
swap:"我會先＿＿＿，再＿＿＿。（換成：把資料整理好／回覆客戶 ＋ 出發／休假）"},
listening:[
{t:"聽對話選日期",d:"播放請假對話，學生在行事曆上圈出請假的日期。"},
{t:"聽內容選答案",d:"小美為什麼請假？(A) 生病 (B) 接家人 (C) 出國旅行 (D) 搬家"},
{t:"聽完填表",d:"填寫：請假日期＿＿＿／假別＿＿＿／原因＿＿＿／誰代理＿＿＿"},
{t:"判斷主管同意了沒",d:"聽四段回覆，判斷主管是同意、要再確認、還是希望改時間。"},
{t:"聽完重說一次",d:"聽完後幫小美向另一位同事說明交接事項。"}],
speaking:{q:["你要請哪一天的假？為什麼？","你的工作那天誰接？","主管說那天很忙，你怎麼回？","請完整說出一次請假。"],
model:"經理，不好意思，可以耽誤你幾分鐘嗎？我想請下星期五一天的假，我媽媽從越南來，我要去接她。報告我會星期四先做完交給你，客戶的電話我已經請阿明幫忙接了。"},
tasks:[
{n:"任務卡 A",d:"你要請下星期五一天事假去機場接家人，但那天要交報告。請你向主管請假並說明安排。"},
{n:"任務卡 B",d:"你早上發燒起不來，需要當天請病假。請你打電話跟主管說明。"},
{n:"任務卡 C",d:"主管說那天人手不夠，希望你改時間。請你協調出一個雙方都可以的方案。"}],
quiz:[
"看圖選詞：（假單／報告／客戶／行事曆）",
"聽音檔選答案：她請的是哪一種假？",
"句子排序：一天／我想／的假／請下星期五",
"選出最自然的說法：(A) 我要休息明天 (B) 我想請明天一天的假 (C) 明天我不來 (D) 給我假明天",
"填空：我會先把報告做完，＿＿＿請假。",
"主管最在意的通常是什麼？(A) 你的原因 (B) 你的工作誰接 (C) 你去哪裡 (D) 你請幾天",
"主管說「那天很忙」，你想協調，你會說：＿＿＿",
"錄音完成任務：向主管請下週三的事假，並說明交接。"],
selfcheck:["我會有禮貌地開口找主管。","我會說清楚請假的日期和原因。","我會說明工作怎麼安排。","我知道要送假單。","主管有疑慮的時候，我會提出解決方式。","我能自己完成一次請假。"],
ladder:[
{lv:"A1",task:"說出要請假的日期",can:"我想請下星期五的假。"},
{lv:"A2",task:"加上原因與假別",can:"我媽媽從越南來，我想請一天事假。"},
{lv:"B1",task:"主動說明工作交接",can:"報告我星期四先交，客戶的電話請阿明幫忙接。"},
{lv:"B2",task:"面對阻力時協調替代方案",can:"我知道那天人手比較緊。如果不方便，我可以改成下午半天，或是那天在家先把急件處理掉。"}]
},
{
id:"report",unit:"工作與職場",no:12,
title:"回報工作進度",viTitle:"Báo cáo tiến độ công việc",
task:{zh:"學完這一課，你可以向主管回報進度：說出完成到哪裡、還剩什麼、遇到什麼困難、預計什麼時候好，並且在做不完的時候提早開口。",
vi:"Học xong bài này, bạn có thể báo cáo tiến độ: đã làm đến đâu, còn lại gì, gặp khó khăn gì, dự kiến khi nào xong, và biết lên tiếng sớm khi không kịp."},
warmup:["主管問「進度怎麼樣？」你會怎麼回答？","做不完的時候，你會提早說還是等主管問？","回報進度要說多細？","在越南的公司，回報方式一樣嗎？"],
media:"專案進度表、電腦螢幕上的表格、會議室裡簡短報告的照片。",
dialog:[
{who:"經理",zh:"小美，那份客戶名單整理得怎麼樣了？",py:"Xiǎo-Měi, nà fèn kèhù míngdān zhěnglǐ de zěnmeyàng le?",vi:"Tiểu Mai, danh sách khách hàng đó sắp xếp đến đâu rồi?"},
{who:"小美",zh:"已經完成八成，剩下南部的部分。",py:"Yǐjīng wánchéng bā chéng, shèngxià nánbù de bùfèn.",vi:"Đã hoàn thành tám phần mười, còn lại phần miền Nam."},
{who:"經理",zh:"大概什麼時候可以好？",py:"Dàgài shénme shíhòu kěyǐ hǎo?",vi:"Khoảng khi nào xong?"},
{who:"小美",zh:"如果順利，明天中午以前可以交。",py:"Rúguǒ shùnlì, míngtiān zhōngwǔ yǐqián kěyǐ jiāo.",vi:"Nếu thuận lợi, trước trưa mai có thể nộp."},
{who:"經理",zh:"有遇到什麼問題嗎？",py:"Yǒu yù dào shénme wèntí ma?",vi:"Có gặp vấn đề gì không?"},
{who:"小美",zh:"有一些客戶的電話是舊的，我打不通。",py:"Yǒu yìxiē kèhù de diànhuà shì jiù de, wǒ dǎ bù tōng.",vi:"Có một số khách hàng dùng số cũ, tôi gọi không được."},
{who:"經理",zh:"那你打算怎麼處理？",py:"Nà nǐ dǎsuàn zěnme chǔlǐ?",vi:"Vậy bạn định xử lý thế nào?"},
{who:"小美",zh:"我想先寄email確認，如果三天沒回，就標記起來。",py:"Wǒ xiǎng xiān jì email quèrèn, rúguǒ sān tiān méi huí, jiù biāojì qǐlái.",vi:"Tôi định gửi email xác nhận trước, nếu ba ngày không hồi âm thì đánh dấu lại."},
{who:"經理",zh:"可以。不過下星期一要用，你確定來得及嗎？",py:"Kěyǐ. Búguò xià xīngqíyī yào yòng, nǐ quèdìng láidejí ma?",vi:"Được. Nhưng thứ Hai tuần sau phải dùng, bạn chắc kịp chứ?"},
{who:"小美",zh:"如果南部的資料明天還拿不到，我會馬上跟你說。",py:"Rúguǒ nánbù de zīliào míngtiān hái ná bú dào, wǒ huì mǎshàng gēn nǐ shuō.",vi:"Nếu ngày mai vẫn chưa lấy được dữ liệu miền Nam, tôi sẽ báo anh ngay."},
{who:"經理",zh:"好，有狀況早點講，不要拖到最後一天。",py:"Hǎo, yǒu zhuàngkuàng zǎodiǎn jiǎng, bú yào tuō dào zuìhòu yì tiān.",vi:"Được, có vấn đề thì nói sớm, đừng để đến ngày cuối."},
{who:"小美",zh:"我知道了，謝謝經理。",py:"Wǒ zhīdào le, xièxie jīnglǐ.",vi:"Tôi hiểu rồi, cảm ơn giám đốc."}],
keys:[
{zh:"已經完成……，剩下……",vi:"Đã hoàn thành…, còn lại…"},
{zh:"大概……以前可以好。",vi:"Khoảng trước… là xong."},
{zh:"我遇到一個問題……",vi:"Tôi gặp một vấn đề…"},
{zh:"我打算……",vi:"Tôi định…"},
{zh:"如果……，我會馬上跟你說。",vi:"Nếu…, tôi sẽ báo anh/chị ngay."},
{zh:"可能會晚一點，因為……",vi:"Có thể sẽ muộn một chút, vì…"},
{zh:"需要你幫我決定一件事。",vi:"Tôi cần anh/chị quyết định giúp một việc."}],
vocab:[
{w:"進度",py:"jìndù",vi:"tiến độ",ex:"進度怎麼樣了？"},
{w:"完成",py:"wánchéng",vi:"hoàn thành",ex:"已經完成一半了。"},
{w:"剩下",py:"shèngxià",vi:"còn lại",ex:"剩下最後兩個。"},
{w:"順利",py:"shùnlì",vi:"thuận lợi",ex:"如果順利，明天就好。"},
{w:"來得及",py:"láidejí",vi:"kịp",ex:"這樣還來得及嗎？"},
{w:"打不通",py:"dǎ bù tōng",vi:"gọi không được",ex:"這個號碼打不通。"},
{w:"處理",py:"chǔlǐ",vi:"xử lý",ex:"這件事我來處理。"},
{w:"確認",py:"quèrèn",vi:"xác nhận",ex:"我先寄信確認。"},
{w:"資料",py:"zīliào",vi:"dữ liệu, tài liệu",ex:"資料還沒拿到。"},
{w:"拖",py:"tuō",vi:"kéo dài, trì hoãn",ex:"不要拖到最後一天。"},
{w:"名單",py:"míngdān",vi:"danh sách",ex:"客戶名單整理好了。"},
{w:"標記",py:"biāojì",vi:"đánh dấu",ex:"打不通的先標記起來。"}],
vocabNote:"臺灣職場回報進度有一個不成文的原則：壞消息要早講。學生常常想「等我做好再說」，結果反而讓主管措手不及。這一課的重點就是練習「提早說」。",
grammar:{pattern:"已經……，剩下……",note:"回報進度最實用的句型：先講做完的，再講沒做完的。主管一聽就知道狀況。",
vi:"Mẫu câu thực dụng nhất khi báo cáo: nói phần đã xong trước, phần còn lại sau.",
ex:["已經完成八成，剩下南部的部分。","已經聯絡二十家，剩下五家。","已經寫好初稿，剩下校對。","已經處理完急件，剩下的明天做。"],
swap:"已經＿＿＿，剩下＿＿＿。（換成：整理好資料／開完會 ＋ 排版／寫紀錄）"},
listening:[
{t:"聽對話選進度",d:"播放回報內容，學生從四個進度條圖中選出正確的完成比例。"},
{t:"聽內容選答案",d:"小美遇到什麼問題？(A) 電腦壞了 (B) 電話打不通 (C) 同事請假 (D) 資料弄丟了"},
{t:"聽完填表",d:"填寫：完成多少＿＿＿／剩下什麼＿＿＿／預計何時交＿＿＿／有什麼困難＿＿＿"},
{t:"判斷來不來得及",d:"聽四段回報，判斷哪一個需要主管馬上介入。"},
{t:"聽完重說一次",d:"聽完後用三句話把進度轉述給另一位主管。"}],
speaking:{q:["你手上的工作做到哪裡了？","還剩下什麼？","你遇到什麼困難？打算怎麼處理？","請完整回報一次進度。"],
model:"經理，客戶名單已經完成八成，剩下南部的部分。如果順利，明天中午以前可以交。有一些客戶的電話打不通，我打算先寄信確認，如果三天沒回就標記起來。如果明天還拿不到資料，我會馬上跟你說。"},
tasks:[
{n:"任務卡 A",d:"主管問你名單整理得怎麼樣。請你回報：完成八成、剩南部、明天中午交、有電話打不通的問題。"},
{n:"任務卡 B",d:"你發現一定做不完了，但期限是後天。請你提早跟主管說明，並提出兩個可能的做法。"},
{n:"任務卡 C",d:"你需要主管決定一件事才能繼續。請你說明卡在哪裡，並請他做決定。"}],
quiz:[
"看圖選詞：（進度／名單／資料／會議）",
"聽音檔選答案：她預計什麼時候交？",
"句子排序：剩下／已經／南部的部分／完成八成",
"選出最自然的說法：(A) 我做八成了差不多 (B) 已經完成八成，剩下南部的部分 (C) 八成完成南部剩 (D) 南部剩下八成完成",
"填空：如果明天還拿不到，我會＿＿＿跟你說。",
"回報進度最重要的原則是什麼？(A) 只講好消息 (B) 壞消息要早講 (C) 等做完再說 (D) 越詳細越好",
"主管問「有遇到什麼問題嗎？」，你有困難，你會說：＿＿＿",
"錄音完成任務：回報一份報告完成一半、預計後天交、缺一份資料。"],
selfcheck:["我會說出完成到哪裡。","我會說還剩下什麼。","我會說預計什麼時候完成。","我會說明遇到的困難和我的打算。","做不完的時候我會提早說。","我能自己完整回報一次工作進度。"],
ladder:[
{lv:"A1",task:"說出做完了沒有",can:"還沒好，明天可以。"},
{lv:"A2",task:"說出完成比例與預計時間",can:"已經完成八成，明天中午以前可以交。"},
{lv:"B1",task:"說明困難並提出處理方式",can:"有些電話打不通，我打算先寄信確認，三天沒回就標記起來。"},
{lv:"B2",task:"預警風險並提出替代方案",can:"如果明天資料還沒到，這份就趕不上星期一。要不要先用現有的版本開會，南部的部分之後補？"}]
}
);
/* 主題課程 第 13–18 課
   全部原創，與任何課本無關。越南文為初稿待校對；音檔一律由 Quinn 錄製。
   角色一律用身分稱呼，不用人名（等 Quinn 給名字後再統一加入）。 */
TC.push(
{
id:"restaurant",unit:"在臺灣生活",no:13,
title:"在餐廳點餐",viTitle:"Gọi món ở nhà hàng",
task:{zh:"學完這一課，你可以在餐廳完成點餐：說人數、看懂菜單、點菜和飲料、說明忌口或不要什麼、加點、要求打包，並且結帳。",
vi:"Học xong bài này, bạn có thể gọi món ở nhà hàng: nói số người, đọc thực đơn, gọi món và đồ uống, nói món kiêng, gọi thêm, xin gói mang về và thanh toán."},
warmup:["你在臺灣最常吃什麼？","你有不吃的東西嗎？（不吃牛、不吃辣、素食）","看不懂菜單的時候你會怎麼辦？","在越南和在臺灣點餐，哪裡不一樣？"],
media:"餐廳菜單、桌上的點菜單、結帳櫃台、打包盒。",
dialog:[
{who:"服務生",zh:"歡迎光臨，請問幾位？",py:"Huānyíng guānglín, qǐngwèn jǐ wèi?",vi:"Chào quý khách, xin hỏi mấy người ạ?"},
{who:"顧客",zh:"兩位，謝謝。",py:"Liǎng wèi, xièxie.",vi:"Hai người, cảm ơn."},
{who:"服務生",zh:"這邊請。這是菜單，先看一下。",py:"Zhèbiān qǐng. Zhè shì càidān, xiān kàn yíxià.",vi:"Mời bên này. Đây là thực đơn, xem qua trước ạ."},
{who:"顧客",zh:"不好意思，請問有什麼推薦的？",py:"Bù hǎoyìsi, qǐngwèn yǒu shénme tuījiàn de?",vi:"Xin lỗi, cho hỏi có món nào ngon giới thiệu không ạ?"},
{who:"服務生",zh:"我們的滷肉飯和酸辣湯很多人點。",py:"Wǒmen de lǔròufàn hé suānlàtāng hěn duō rén diǎn.",vi:"Cơm thịt kho và canh chua cay của quán rất nhiều người gọi."},
{who:"顧客",zh:"那我要一碗滷肉飯。不過我不吃牛肉。",py:"Nà wǒ yào yì wǎn lǔròufàn. Búguò wǒ bù chī niúròu.",vi:"Vậy tôi lấy một tô cơm thịt kho. Nhưng tôi không ăn thịt bò."},
{who:"服務生",zh:"沒問題，滷肉飯是豬肉。要加湯嗎？",py:"Méi wèntí, lǔròufàn shì zhūròu. Yào jiā tāng ma?",vi:"Không sao, cơm thịt kho là thịt heo. Có thêm canh không ạ?"},
{who:"顧客",zh:"好，一碗酸辣湯，可以不要太辣嗎？",py:"Hǎo, yì wǎn suānlàtāng, kěyǐ bú yào tài là ma?",vi:"Được, một tô canh chua cay, có thể đừng cay quá không ạ?"},
{who:"服務生",zh:"可以，幫你調成小辣。飲料要嗎？",py:"Kěyǐ, bāng nǐ tiáo chéng xiǎo là. Yǐnliào yào ma?",vi:"Được, tôi chỉnh thành ít cay. Có lấy đồ uống không ạ?"},
{who:"顧客",zh:"兩杯冰紅茶。等一下吃不完可以打包嗎？",py:"Liǎng bēi bīng hóngchá. Děng yíxià chī bù wán kěyǐ dǎbāo ma?",vi:"Hai ly trà đen đá. Lát nữa ăn không hết có gói mang về được không?"},
{who:"服務生",zh:"可以，跟我說一聲就好。",py:"Kěyǐ, gēn wǒ shuō yì shēng jiù hǎo.",vi:"Được ạ, chỉ cần nói với tôi một tiếng."},
{who:"顧客",zh:"謝謝。我們是分開付還是一起結？等一下再說吧。",py:"Xièxie. Wǒmen shì fēnkāi fù háishì yìqǐ jié? Děng yíxià zài shuō ba.",vi:"Cảm ơn. Chúng tôi trả riêng hay trả chung? Lát nữa nói sau nhé."}],
keys:[
{zh:"兩位／三位，謝謝。",vi:"Hai người / ba người, cảm ơn."},
{zh:"請問有什麼推薦的？",vi:"Cho hỏi có món nào ngon giới thiệu không?"},
{zh:"我不吃……",vi:"Tôi không ăn…"},
{zh:"可以不要太辣嗎？",vi:"Có thể đừng cay quá không?"},
{zh:"我要加點一份……",vi:"Tôi muốn gọi thêm một phần…"},
{zh:"可以打包嗎？",vi:"Gói mang về được không?"},
{zh:"買單／結帳，謝謝。",vi:"Tính tiền, cảm ơn."},
{zh:"分開付可以嗎？",vi:"Trả riêng được không?"}],
vocab:[
{w:"菜單",py:"càidān",vi:"thực đơn",ex:"服務生給我們菜單。"},
{w:"推薦",py:"tuījiàn",vi:"giới thiệu, gợi ý",ex:"請問有什麼推薦的？"},
{w:"點菜",py:"diǎncài",vi:"gọi món",ex:"我們可以點菜了嗎？"},
{w:"加點",py:"jiādiǎn",vi:"gọi thêm",ex:"我想加點一碗湯。"},
{w:"份",py:"fèn",vi:"phần",ex:"再來一份炒飯。"},
{w:"小辣",py:"xiǎo là",vi:"ít cay",ex:"我要小辣就好。"},
{w:"忌口",py:"jìkǒu",vi:"kiêng ăn",ex:"你有什麼忌口的嗎？"},
{w:"素食",py:"sùshí",vi:"đồ chay",ex:"請問有素食嗎？"},
{w:"打包",py:"dǎbāo",vi:"gói mang về",ex:"吃不完可以打包。"},
{w:"結帳",py:"jiézhàng",vi:"thanh toán",ex:"我們要結帳，謝謝。"},
{w:"分開付",py:"fēnkāi fù",vi:"trả riêng",ex:"我們分開付可以嗎？"},
{w:"服務生",py:"fúwùshēng",vi:"nhân viên phục vụ",ex:"我叫一下服務生。"}],
vocabNote:"臺灣餐廳常見的三句：進門「幾位？」、點完「還需要什麼嗎？」、結帳「一起還是分開？」。另外「買單」和「結帳」都通，小吃店多說「算帳」。",
grammar:{pattern:"可以不要 + ……嗎？",note:"最實用的一句客氣要求。用來拿掉不想要的東西，不會讓對方覺得挑剔。",
vi:"Câu đề nghị lịch sự hữu dụng nhất, dùng để bỏ thứ mình không muốn.",
ex:["可以不要太辣嗎？","可以不要放香菜嗎？","可以不要加冰塊嗎？","可以不要味精嗎？"],
swap:"可以不要＿＿＿＿嗎？（換成：放蔥／太鹹／太甜／太油）"},
listening:[
{t:"聽對話選餐點",d:"播放點餐內容，學生從四張餐點圖中選出顧客點的東西。"},
{t:"聽內容選答案",d:"顧客為什麼不點牛肉麵？(A) 太貴 (B) 不吃牛肉 (C) 賣完了 (D) 太辣"},
{t:"聽完填單",d:"填寫點菜單：主餐＿＿＿／湯＿＿＿／飲料＿＿＿／辣度＿＿＿／幾份＿＿＿"},
{t:"判斷服務生說了什麼",d:"聽四句服務生的話，判斷是在問人數、問辣度、問內用外帶、還是在說賣完了。"},
{t:"聽完重說一次",d:"聽完後把整桌的訂單完整複述一遍。"}],
speaking:{q:["你今天想吃什麼？","你有不吃的東西嗎？怎麼跟服務生說？","菜太辣了，你會怎麼講？","請完整點一次餐，兩個人份。"],
model:"你好，兩位。請問有什麼推薦的？那我要一碗滷肉飯，不過我不吃牛肉。再來一碗酸辣湯，可以不要太辣嗎？兩杯冰紅茶，謝謝。"},
tasks:[
{n:"任務卡 A",d:"你和朋友兩個人去吃飯。你不吃牛肉，朋友不吃辣。請你點兩份主餐、一份湯、兩杯飲料。"},
{n:"任務卡 B",d:"上桌的菜跟你點的不一樣。請你有禮貌地說明，並請服務生處理。"},
{n:"任務卡 C",d:"吃完還剩很多。請你請服務生打包，並且問可不可以分開付。"}],
quiz:[
"看圖選詞：（菜單／打包／結帳／素食）",
"聽音檔選答案：顧客點了幾碗飯？",
"句子排序：不要／可以／嗎／太辣",
"選出最自然的說法：(A) 我要不辣 (B) 可以不要太辣嗎 (C) 辣不要我 (D) 不辣給我",
"填空：請問有什麼＿＿＿＿的？",
"「打包」是什麼意思？(A) 幫忙提東西 (B) 把吃不完的帶走 (C) 換一份 (D) 買單",
"服務生問「幾位？」，你們三個人，你會說：＿＿＿",
"錄音完成任務：點兩份主餐，說明不吃牛肉、要小辣。"],
selfcheck:["我會說幾位、會看菜單。","我會問有什麼推薦的。","我會說我不吃什麼。","我會請對方調整辣度或去掉某樣東西。","我會加點、打包、結帳。","我能自己一個人在餐廳點餐。"],
ladder:[
{lv:"A1",task:"說人數和點一份餐",can:"兩位。我要一碗滷肉飯。"},
{lv:"A2",task:"加上飲料、辣度與忌口",can:"我不吃牛肉，酸辣湯可以不要太辣嗎？"},
{lv:"B1",task:"詢問推薦、加點、處理打包結帳",can:"請問有什麼推薦的？我們再加點一份，吃不完的可以打包嗎？"},
{lv:"B2",task:"處理上錯菜並協調解決",can:"不好意思，我點的是小辣，可是這碗好像是大辣。可以幫我換一碗嗎？如果不方便，能不能換別的？"}]
},
{
id:"renthouse",unit:"在臺灣生活",no:14,
title:"租房子：看房與談條件",viTitle:"Thuê nhà: đi xem phòng và thương lượng điều kiện",
task:{zh:"學完這一課，你可以去看房子：問租金包不包水電網路、押金幾個月、可不可以開伙、什麼時候可以搬進來，並且在簽約前把條件問清楚。",
vi:"Học xong bài này, bạn có thể đi xem phòng: hỏi tiền thuê có bao gồm điện nước mạng không, đặt cọc mấy tháng, có được nấu ăn không, khi nào dọn vào, và hỏi rõ điều kiện trước khi ký hợp đồng."},
warmup:["你現在住哪裡？租的還是學校宿舍？","看房子的時候你最在意什麼？","「押金兩個月」是什麼意思？","在越南租房子跟在臺灣有什麼不一樣？"],
media:"租屋網站頁面、套房內部照片、水電表、租賃契約書。",
dialog:[
{who:"房客",zh:"你好，我看到網路上的租屋廣告，想約看房。",py:"Nǐ hǎo, wǒ kàn dào wǎnglù shàng de zūwū guǎnggào, xiǎng yuē kàn fáng.",vi:"Xin chào, tôi thấy tin cho thuê trên mạng, muốn hẹn xem phòng."},
{who:"房東",zh:"好啊，你什麼時候方便？",py:"Hǎo a, nǐ shénme shíhòu fāngbiàn?",vi:"Được, khi nào bạn tiện?"},
{who:"房客",zh:"這個星期六下午可以嗎？",py:"Zhège xīngqíliù xiàwǔ kěyǐ ma?",vi:"Chiều thứ Bảy này được không ạ?"},
{who:"房東",zh:"可以。這間是套房，有獨立衛浴。",py:"Kěyǐ. Zhè jiān shì tàofáng, yǒu dúlì wèiyù.",vi:"Được. Phòng này là phòng khép kín, có nhà tắm riêng."},
{who:"房客",zh:"請問房租一個月多少？包水電嗎？",py:"Qǐngwèn fángzū yí ge yuè duōshǎo? Bāo shuǐdiàn ma?",vi:"Cho hỏi tiền thuê một tháng bao nhiêu? Có bao điện nước không?"},
{who:"房東",zh:"一個月八千，包水和網路，電費另外算。",py:"Yí ge yuè bāqiān, bāo shuǐ hé wǎnglù, diànfèi lìngwài suàn.",vi:"Tám nghìn một tháng, bao nước và mạng, tiền điện tính riêng."},
{who:"房客",zh:"押金要幾個月？",py:"Yājīn yào jǐ ge yuè?",vi:"Đặt cọc mấy tháng ạ?"},
{who:"房東",zh:"押兩個月，退租的時候退還。",py:"Yā liǎng ge yuè, tuìzū de shíhòu tuìhuán.",vi:"Cọc hai tháng, khi trả phòng sẽ hoàn lại."},
{who:"房客",zh:"可以開伙嗎？我常常自己煮。",py:"Kěyǐ kāihuǒ ma? Wǒ chángcháng zìjǐ zhǔ.",vi:"Có được nấu ăn không? Tôi hay tự nấu."},
{who:"房東",zh:"可以，但是不要用明火，用電磁爐就好。",py:"Kěyǐ, dànshì bú yào yòng mínghuǒ, yòng diàncílú jiù hǎo.",vi:"Được, nhưng đừng dùng lửa, dùng bếp từ thôi."},
{who:"房客",zh:"了解。最快什麼時候可以搬進來？",py:"Liǎojiě. Zuì kuài shénme shíhòu kěyǐ bān jìnlái?",vi:"Tôi hiểu rồi. Sớm nhất khi nào có thể dọn vào?"},
{who:"房東",zh:"下個月一號。簽約那天帶居留證和押金就可以。",py:"Xià ge yuè yī hào. Qiānyuē nà tiān dài jūliúzhèng hé yājīn jiù kěyǐ.",vi:"Ngày một tháng sau. Hôm ký hợp đồng mang thẻ cư trú và tiền cọc là được."}],
keys:[
{zh:"我想約看房。",vi:"Tôi muốn hẹn xem phòng."},
{zh:"房租一個月多少？",vi:"Tiền thuê một tháng bao nhiêu?"},
{zh:"包水電網路嗎？",vi:"Có bao điện nước mạng không?"},
{zh:"押金要幾個月？",vi:"Đặt cọc mấy tháng?"},
{zh:"可以開伙嗎？",vi:"Có được nấu ăn không?"},
{zh:"最快什麼時候可以搬進來？",vi:"Sớm nhất khi nào dọn vào được?"},
{zh:"合約要簽多久？",vi:"Hợp đồng ký bao lâu?"},
{zh:"東西壞了誰負責修？",vi:"Đồ hỏng thì ai chịu trách nhiệm sửa?"}],
vocab:[
{w:"租屋",py:"zūwū",vi:"thuê nhà",ex:"我在租屋網站上找房子。"},
{w:"看房",py:"kàn fáng",vi:"xem phòng",ex:"星期六下午去看房。"},
{w:"套房",py:"tàofáng",vi:"phòng khép kín",ex:"這間套房有獨立衛浴。"},
{w:"房租",py:"fángzū",vi:"tiền thuê nhà",ex:"房租一個月八千。"},
{w:"押金",py:"yājīn",vi:"tiền đặt cọc",ex:"押金押兩個月。"},
{w:"水電",py:"shuǐdiàn",vi:"điện nước",ex:"房租包不包水電？"},
{w:"另外算",py:"lìngwài suàn",vi:"tính riêng",ex:"電費另外算。"},
{w:"開伙",py:"kāihuǒ",vi:"nấu ăn (trong phòng)",ex:"這裡可以開伙嗎？"},
{w:"簽約",py:"qiānyuē",vi:"ký hợp đồng",ex:"下星期簽約。"},
{w:"合約",py:"héyuē",vi:"hợp đồng",ex:"合約要簽一年。"},
{w:"退租",py:"tuìzū",vi:"trả phòng, chấm dứt thuê",ex:"退租的時候退押金。"},
{w:"搬進來",py:"bān jìnlái",vi:"dọn vào",ex:"下個月一號搬進來。"}],
vocabNote:"臺灣租屋常見說法：押金通常「押二付一」（押兩個月、先付一個月）。「包水電」要問清楚是包全部還是只包水；電費常常另外算，夏天冷氣會差很多。簽約前建議把口頭講好的條件寫進合約。",
grammar:{pattern:"包 + N 嗎？／…… 另外算",note:"問租金裡面「含不含」某項費用。這一組是租屋談條件時最容易吃虧的地方，一定要問清楚。",
vi:"Hỏi tiền thuê đã bao gồm khoản nào chưa. Đây là chỗ dễ thiệt nhất khi thuê nhà, phải hỏi rõ.",
ex:["房租包水電嗎？","包網路嗎？","電費另外算。","管理費另外算，一個月五百。"],
swap:"包＿＿＿＿嗎？（換成：網路／第四台／管理費／停車位）"},
listening:[
{t:"聽對話選房子",d:"播放看房對話，學生從四張房型圖中選出符合條件的那一間。"},
{t:"聽內容選答案",d:"押金要押幾個月？(A) 一個月 (B) 兩個月 (C) 三個月 (D) 不用押"},
{t:"聽完填表",d:"填寫：房租＿＿＿／包什麼＿＿＿／押金＿＿＿／可否開伙＿＿＿／何時可入住＿＿＿"},
{t:"判斷划不划算",d:"聽兩間房子的條件，比較哪一間實際花費比較低。"},
{t:"聽完重說一次",d:"聽完後把這間房子的條件說給室友聽。"}],
speaking:{q:["你想找什麼樣的房子？","你最在意哪三個條件？","房東說電費另外算，你會再問什麼？","請完整問一次看房該問的問題。"],
model:"你好，我看到網路上的廣告，想約看房。請問房租一個月多少？包水電網路嗎？押金要幾個月？可以開伙嗎？最快什麼時候可以搬進來？"},
tasks:[
{n:"任務卡 A",d:"你要租一間套房，預算一個月九千以內，需要可以開伙。請你打電話約看房，並問清楚五個條件。"},
{n:"任務卡 B",d:"房東說房租八千「包水電」，但你發現電費要另外算。請你把這件事問清楚，並請他寫進合約。"},
{n:"任務卡 C",d:"你要退租了，房東說押金要扣一部分。請你問清楚扣什麼、扣多少，並表達你的看法。"}],
quiz:[
"看圖選詞：（套房／押金／合約／水電）",
"聽音檔選答案：這間房子房租多少？",
"句子排序：多少／房租／一個月",
"選出最自然的說法：(A) 水電包嗎房租 (B) 房租包水電嗎 (C) 包房租水電嗎 (D) 房租水電包嗎",
"填空：押金要＿＿＿＿個月？",
"「押二付一」是什麼意思？(A) 押金兩個月、先付一個月房租 (B) 住兩個月付一個月 (C) 兩個人付一份 (D) 押金打折",
"房東說「電費另外算」，你想知道大概多少，你會說：＿＿＿",
"錄音完成任務：約看房並問租金、押金、可否開伙。"],
selfcheck:["我會打電話約看房。","我會問房租和押金。","我會問包不包水電網路。","我會問可不可以開伙、什麼時候能搬。","我知道簽約前要把條件問清楚。","我能自己一個人去看房並談條件。"],
ladder:[
{lv:"A1",task:"問租金和地點",can:"請問房租一個月多少？"},
{lv:"A2",task:"問押金、包不包水電、何時可搬",can:"押金幾個月？包水電嗎？什麼時候可以搬進來？"},
{lv:"B1",task:"比較條件並提出需求",can:"如果電費另外算，那夏天大概要多少？我需要可以開伙的。"},
{lv:"B2",task:"協商合約條件與退租爭議",can:"我們口頭說好包網路，可以請你寫進合約嗎？退租的時候押金什麼情況會扣，也想先講清楚。"}]
}
);
TC.push(
{
id:"bank",unit:"在臺灣安頓下來",no:15,
title:"去銀行開戶與匯錢回越南",viTitle:"Mở tài khoản ngân hàng và gửi tiền về Việt Nam",
task:{zh:"學完這一課，你可以到銀行辦事：說明要開戶、聽懂行員問的問題、設定密碼與提款卡，並且辦理匯款回越南、問清楚手續費和到帳時間。",
vi:"Học xong bài này, bạn có thể đến ngân hàng: nói rõ muốn mở tài khoản, hiểu câu hỏi của giao dịch viên, làm thẻ và mật khẩu, và chuyển tiền về Việt Nam, hỏi rõ phí và thời gian tiền tới."},
warmup:["你在臺灣有銀行帳戶嗎？在哪一家？","你都怎麼把錢寄回越南？","匯款和「跑腿代匯」有什麼不同？","你知道匯款要準備什麼資料嗎？"],
media:"銀行櫃台、號碼牌、開戶申請書、提款卡、匯款單。",
dialog:[
{who:"顧客",zh:"你好，我要開戶。",py:"Nǐ hǎo, wǒ yào kāihù.",vi:"Xin chào, tôi muốn mở tài khoản."},
{who:"行員",zh:"好的，請問您有帶居留證和護照嗎？",py:"Hǎo de, qǐngwèn nín yǒu dài jūliúzhèng hé hùzhào ma?",vi:"Vâng, xin hỏi anh/chị có mang thẻ cư trú và hộ chiếu không ạ?"},
{who:"顧客",zh:"都帶了。還需要印章嗎？",py:"Dōu dài le. Hái xūyào yìnzhāng ma?",vi:"Đều mang rồi. Còn cần con dấu không ạ?"},
{who:"行員",zh:"有印章比較方便，沒有的話可以簽名。",py:"Yǒu yìnzhāng bǐjiào fāngbiàn, méiyǒu dehuà kěyǐ qiānmíng.",vi:"Có con dấu thì tiện hơn, không có thì có thể ký tên."},
{who:"顧客",zh:"我要辦提款卡和網路銀行。",py:"Wǒ yào bàn tíkuǎnkǎ hé wǎnglù yínháng.",vi:"Tôi muốn làm thẻ rút tiền và ngân hàng trực tuyến."},
{who:"行員",zh:"沒問題。請在這裡填表，密碼設六位數字。",py:"Méi wèntí. Qǐng zài zhèlǐ tián biǎo, mìmǎ shè liù wèi shùzì.",vi:"Không vấn đề gì. Xin điền vào đây, mật khẩu đặt sáu chữ số."},
{who:"顧客",zh:"好。另外我想問，匯錢回越南要怎麼辦？",py:"Hǎo. Lìngwài wǒ xiǎng wèn, huì qián huí Yuènán yào zěnme bàn?",vi:"Vâng. Ngoài ra tôi muốn hỏi, gửi tiền về Việt Nam thì làm thế nào?"},
{who:"行員",zh:"要填匯款單，需要對方的帳號、姓名和銀行資料。",py:"Yào tián huìkuǎndān, xūyào duìfāng de zhànghào, xìngmíng hé yínháng zīliào.",vi:"Phải điền phiếu chuyển tiền, cần số tài khoản, tên và thông tin ngân hàng của người nhận."},
{who:"顧客",zh:"手續費大概多少？",py:"Shǒuxùfèi dàgài duōshǎo?",vi:"Phí khoảng bao nhiêu ạ?"},
{who:"行員",zh:"這個要看金額和幣別，我幫您查一下。",py:"Zhège yào kàn jīn'é hé bìbié, wǒ bāng nín chá yíxià.",vi:"Cái này tùy số tiền và loại tiền, để tôi tra giúp anh/chị."},
{who:"顧客",zh:"謝謝。大概幾天會到？",py:"Xièxie. Dàgài jǐ tiān huì dào?",vi:"Cảm ơn. Khoảng mấy ngày thì tới?"},
{who:"行員",zh:"通常兩到三個工作天，遇到假日會慢一點。",py:"Tōngcháng liǎng dào sān ge gōngzuò tiān, yù dào jiàrì huì màn yìdiǎn.",vi:"Thường hai đến ba ngày làm việc, gặp ngày lễ sẽ chậm hơn."}],
keys:[
{zh:"我要開戶。",vi:"Tôi muốn mở tài khoản."},
{zh:"我帶了居留證和護照。",vi:"Tôi mang thẻ cư trú và hộ chiếu."},
{zh:"我要辦提款卡和網路銀行。",vi:"Tôi muốn làm thẻ rút tiền và ngân hàng trực tuyến."},
{zh:"我想匯錢回越南。",vi:"Tôi muốn gửi tiền về Việt Nam."},
{zh:"手續費大概多少？",vi:"Phí khoảng bao nhiêu?"},
{zh:"大概幾天會到？",vi:"Khoảng mấy ngày thì tới?"},
{zh:"匯率今天是多少？",vi:"Hôm nay tỷ giá bao nhiêu?"},
{zh:"可以幫我查一下餘額嗎？",vi:"Kiểm tra số dư giúp tôi được không?"}],
vocab:[
{w:"開戶",py:"kāihù",vi:"mở tài khoản",ex:"我今天要去銀行開戶。"},
{w:"帳號",py:"zhànghào",vi:"số tài khoản",ex:"請給我你的帳號。"},
{w:"印章",py:"yìnzhāng",vi:"con dấu",ex:"開戶最好帶印章。"},
{w:"提款卡",py:"tíkuǎnkǎ",vi:"thẻ rút tiền",ex:"提款卡一個星期後寄到。"},
{w:"密碼",py:"mìmǎ",vi:"mật khẩu",ex:"密碼設六位數字。"},
{w:"網路銀行",py:"wǎnglù yínháng",vi:"ngân hàng trực tuyến",ex:"用網路銀行轉帳比較快。"},
{w:"匯款",py:"huìkuǎn",vi:"chuyển tiền",ex:"我要匯款回越南。"},
{w:"匯款單",py:"huìkuǎndān",vi:"phiếu chuyển tiền",ex:"請先填匯款單。"},
{w:"手續費",py:"shǒuxùfèi",vi:"phí dịch vụ",ex:"匯款要收手續費。"},
{w:"匯率",py:"huìlǜ",vi:"tỷ giá",ex:"今天的匯率比較好。"},
{w:"餘額",py:"yú'é",vi:"số dư",ex:"我想查一下餘額。"},
{w:"工作天",py:"gōngzuò tiān",vi:"ngày làm việc",ex:"兩到三個工作天會到。"}],
vocabNote:"各家銀行對外國人開戶要求的證件不完全一樣，多半會要居留證加第二證件（護照），有些還會問在學或在職證明。手續費、匯率、到帳天數也各家不同——這一課教的是「怎麼問」，實際規定請學生到分行再確認。",
grammar:{pattern:"大概 + 多少／幾天／幾點？",note:"問一個估計值而不是精確數字。對方還沒查之前，用「大概」問比較自然，也不會給人壓力。",
vi:"Dùng để hỏi con số ước chừng thay vì chính xác, nghe tự nhiên và không tạo áp lực.",
ex:["手續費大概多少？","大概幾天會到？","大概要等多久？","大概幾點關門？"],
swap:"大概＿＿＿＿？（換成：多少錢／幾個人／幾號到／要多久）"},
listening:[
{t:"聽對話選證件",d:"播放行員的話，學生從圖片中選出要準備的證件。"},
{t:"聽內容選答案",d:"匯款大概幾天會到？(A) 當天 (B) 兩到三個工作天 (C) 一個星期 (D) 一個月"},
{t:"聽完填匯款單",d:"填寫：收款人姓名＿＿＿／帳號＿＿＿／金額＿＿＿／幣別＿＿＿"},
{t:"聽數字",d:"聽行員報出的金額、手續費和匯率，寫下正確數字。"},
{t:"聽完重說一次",d:"聽完後把開戶要帶的東西講給朋友聽。"}],
speaking:{q:["你要去銀行辦什麼？","開戶要帶什麼？","你想問行員哪三個問題？","請完整說一次開戶加匯款的需求。"],
model:"你好，我要開戶。我帶了居留證和護照。我要辦提款卡和網路銀行。另外我想問，匯錢回越南要怎麼辦？手續費大概多少？大概幾天會到？"},
tasks:[
{n:"任務卡 A",d:"你剛到臺灣，要開第一個銀行帳戶，還要辦提款卡和網路銀行。請你到櫃台說明並回答行員的問題。"},
{n:"任務卡 B",d:"你要匯三萬元回越南給家人。請你問清楚需要什麼資料、手續費多少、幾天會到。"},
{n:"任務卡 C",d:"你的提款卡在提款機被吃掉了。請你到銀行說明狀況並問怎麼處理。"}],
quiz:[
"看圖選詞：（提款卡／印章／匯款單／號碼牌）",
"聽音檔選答案：行員說要帶哪兩種證件？",
"句子排序：開戶／我／要",
"選出最自然的說法：(A) 多少大概手續費 (B) 手續費大概多少 (C) 大概手續費多少錢有 (D) 手續費多少大概",
"填空：大概＿＿＿＿天會到？",
"「工作天」是什麼意思？(A) 包含週末 (B) 不含週末和假日 (C) 只有星期一 (D) 上班時間",
"你想知道今天的匯率，你會問：＿＿＿",
"錄音完成任務：說明要開戶、辦提款卡，並詢問匯款手續費。"],
selfcheck:["我會說我要開戶。","我知道要帶哪些證件。","我會辦提款卡和網路銀行。","我會辦匯款回越南。","我會問手續費、匯率和到帳時間。","我能自己一個人去銀行辦事。"],
ladder:[
{lv:"A1",task:"說明來意並交出證件",can:"你好，我要開戶。這是我的居留證。"},
{lv:"A2",task:"回答行員問題並辦卡",can:"我帶了護照和居留證，我要辦提款卡和網路銀行。"},
{lv:"B1",task:"辦理匯款並問清楚細節",can:"我想匯錢回越南，需要哪些資料？手續費大概多少？幾天會到？"},
{lv:"B2",task:"比較方案並處理問題",can:"如果分兩次匯，手續費會不會比較划算？上次那筆到現在還沒入帳，可以幫我查一下嗎？"}]
},
{
id:"simcard",unit:"在臺灣安頓下來",no:16,
title:"辦手機門號與網路",viTitle:"Đăng ký số điện thoại và mạng",
task:{zh:"學完這一課，你可以到電信門市辦門號：說明要預付卡還是月租、比較方案和網路流量、問合約綁幾個月、辦網路報停或攜碼。",
vi:"Học xong bài này, bạn có thể đến cửa hàng viễn thông: nói rõ muốn thẻ trả trước hay trả sau, so sánh gói cước và dung lượng, hỏi hợp đồng ràng buộc mấy tháng, tạm ngưng hoặc chuyển mạng giữ số."},
warmup:["你現在用哪一家電信？","你一個月大概用多少網路？","預付卡和月租，哪一個適合你？","在越南辦門號跟在臺灣有什麼不同？"],
media:"電信門市櫃台、資費方案看板、SIM 卡、手機設定畫面。",
dialog:[
{who:"顧客",zh:"你好，我想辦門號。",py:"Nǐ hǎo, wǒ xiǎng bàn ménhào.",vi:"Xin chào, tôi muốn đăng ký số điện thoại."},
{who:"店員",zh:"好的，請問要預付卡還是月租型？",py:"Hǎo de, qǐngwèn yào yùfùkǎ háishì yuèzū xíng?",vi:"Vâng, xin hỏi muốn thẻ trả trước hay gói trả sau ạ?"},
{who:"顧客",zh:"差在哪裡？",py:"Chā zài nǎlǐ?",vi:"Khác nhau ở đâu ạ?"},
{who:"店員",zh:"預付卡用完再儲值，月租要綁約，但比較便宜。",py:"Yùfùkǎ yòng wán zài chúzhí, yuèzū yào bǎngyuē, dànshì bǐjiào piányí.",vi:"Thẻ trả trước dùng hết thì nạp lại, gói trả sau phải ràng buộc hợp đồng nhưng rẻ hơn."},
{who:"顧客",zh:"月租要綁幾個月？",py:"Yuèzū yào bǎng jǐ ge yuè?",vi:"Gói trả sau ràng buộc mấy tháng?"},
{who:"店員",zh:"通常綁二十四個月，提前解約要付違約金。",py:"Tōngcháng bǎng èrshísì ge yuè, tíqián jiěyuē yào fù wéiyuējīn.",vi:"Thường ràng buộc hai mươi bốn tháng, hủy sớm phải trả phí phạt."},
{who:"顧客",zh:"我還不確定會待多久，那先辦預付卡好了。",py:"Wǒ hái bú quèdìng huì dāi duōjiǔ, nà xiān bàn yùfùkǎ hǎo le.",vi:"Tôi chưa chắc ở bao lâu, vậy làm thẻ trả trước trước vậy."},
{who:"店員",zh:"沒問題。請給我護照和居留證。",py:"Méi wèntí. Qǐng gěi wǒ hùzhào hé jūliúzhèng.",vi:"Không vấn đề gì. Cho tôi xin hộ chiếu và thẻ cư trú."},
{who:"顧客",zh:"網路有吃到飽的嗎？",py:"Wǎnglù yǒu chī dào bǎo de ma?",vi:"Mạng có gói không giới hạn không ạ?"},
{who:"店員",zh:"有，三十天吃到飽，也有十五天的。",py:"Yǒu, sānshí tiān chī dào bǎo, yě yǒu shíwǔ tiān de.",vi:"Có, gói ba mươi ngày không giới hạn, cũng có gói mười lăm ngày."},
{who:"顧客",zh:"那我要三十天的。以後可以改成月租嗎？",py:"Nà wǒ yào sānshí tiān de. Yǐhòu kěyǐ gǎi chéng yuèzū ma?",vi:"Vậy tôi lấy gói ba mươi ngày. Sau này đổi sang trả sau được không?"},
{who:"店員",zh:"可以，號碼可以留著，帶證件來辦就好。",py:"Kěyǐ, hàomǎ kěyǐ liú zhe, dài zhèngjiàn lái bàn jiù hǎo.",vi:"Được, số có thể giữ lại, mang giấy tờ đến làm là được."}],
keys:[
{zh:"我想辦門號。",vi:"Tôi muốn đăng ký số điện thoại."},
{zh:"預付卡還是月租？差在哪裡？",vi:"Trả trước hay trả sau? Khác nhau ở đâu?"},
{zh:"要綁幾個月？",vi:"Ràng buộc mấy tháng?"},
{zh:"有吃到飽的嗎？",vi:"Có gói không giới hạn không?"},
{zh:"一個月多少錢？",vi:"Một tháng bao nhiêu tiền?"},
{zh:"提前解約要付違約金嗎？",vi:"Hủy sớm có phải trả phí phạt không?"},
{zh:"號碼可以留著嗎？",vi:"Có giữ được số không?"},
{zh:"可以幫我設定嗎？",vi:"Cài đặt giúp tôi được không?"}],
vocab:[
{w:"門號",py:"ménhào",vi:"số điện thoại (thuê bao)",ex:"我下午要去辦門號。"},
{w:"預付卡",py:"yùfùkǎ",vi:"thẻ trả trước",ex:"預付卡用完再儲值。"},
{w:"月租",py:"yuèzū",vi:"gói cước trả sau",ex:"月租一個月五百九。"},
{w:"儲值",py:"chúzhí",vi:"nạp tiền",ex:"我要儲值三百塊。"},
{w:"綁約",py:"bǎngyuē",vi:"ràng buộc hợp đồng",ex:"月租要綁約兩年。"},
{w:"違約金",py:"wéiyuējīn",vi:"phí phạt hủy hợp đồng",ex:"提前解約要付違約金。"},
{w:"吃到飽",py:"chī dào bǎo",vi:"không giới hạn (data)",ex:"我用吃到飽的方案。"},
{w:"流量",py:"liúliàng",vi:"dung lượng",ex:"這個月流量快用完了。"},
{w:"方案",py:"fāng'àn",vi:"gói cước",ex:"哪一個方案比較划算？"},
{w:"訊號",py:"xùnhào",vi:"sóng, tín hiệu",ex:"這裡訊號不太好。"},
{w:"設定",py:"shèdìng",vi:"cài đặt",ex:"可以幫我設定嗎？"},
{w:"解約",py:"jiěyuē",vi:"hủy hợp đồng",ex:"我想提前解約。"}],
vocabNote:"外國人辦門號各家電信要求不同，一般會要護照加居留證兩種證件，居留證效期太短有時候只能辦預付卡。資費方案變動很快——這一課重點是「怎麼比較、怎麼問」，實際方案請學生到門市確認。",
grammar:{pattern:"A 還是 B？差在哪裡？",note:"先問二選一，再追問差別。這一組問句在辦任何手續時都好用，可以問出對方不會主動說的資訊。",
vi:"Hỏi chọn A hay B, rồi hỏi thêm khác nhau chỗ nào. Rất hữu dụng khi làm bất kỳ thủ tục nào.",
ex:["預付卡還是月租？差在哪裡？","單程還是來回？差多少？","內用還是外帶？價錢一樣嗎？","一年約還是兩年約？差在哪裡？"],
swap:"＿＿＿＿還是＿＿＿＿？差在哪裡？（換成：這個方案／那個方案、大杯／中杯、新的／二手的）"},
listening:[
{t:"聽對話選方案",d:"播放店員介紹的兩個方案，學生從表格中選出符合顧客需求的那一個。"},
{t:"聽內容選答案",d:"月租通常要綁幾個月？(A) 六個月 (B) 十二個月 (C) 二十四個月 (D) 不用綁"},
{t:"聽完填表",d:"填寫：方案＿＿＿／月租多少＿＿＿／綁約幾個月＿＿＿／有無吃到飽＿＿＿"},
{t:"聽數字",d:"聽店員報出的月租金額、流量和天數，寫下正確數字。"},
{t:"聽完重說一次",d:"聽完後把兩個方案的差別說給朋友聽，並建議他選哪一個。"}],
speaking:{q:["你會選預付卡還是月租？為什麼？","你一個月大概用多少網路？","你想問店員哪三個問題？","請完整說一次你要辦的門號需求。"],
model:"你好，我想辦門號。請問預付卡還是月租，差在哪裡？月租要綁幾個月？有吃到飽的嗎？我還不確定會待多久，那先辦預付卡好了。"},
tasks:[
{n:"任務卡 A",d:"你剛到臺灣，只確定會待一年。請你到門市問清楚兩種方案的差別，選一個並說明理由。"},
{n:"任務卡 B",d:"你的網路這個月用超過了，速度變很慢。請你到門市說明狀況並問可以怎麼處理。"},
{n:"任務卡 C",d:"你要回越南三個月，想暫停門號但保留號碼。請你說明需求並問費用。"}],
quiz:[
"看圖選詞：（SIM 卡／儲值／方案／訊號）",
"聽音檔選答案：顧客最後選了哪一種？",
"句子排序：辦／我／門號／想",
"選出最自然的說法：(A) 綁幾個月要 (B) 要綁幾個月 (C) 幾個月綁要 (D) 要幾個月綁",
"填空：預付卡還是月租？＿＿＿＿在哪裡？",
"「吃到飽」是什麼意思？(A) 免費吃飯 (B) 網路用不完 (C) 可以退錢 (D) 不用付月租",
"店員說「要綁二十四個月」，你不確定會待那麼久，你會說：＿＿＿",
"錄音完成任務：說明要辦預付卡、要吃到飽，並問以後能不能改月租。"],
selfcheck:["我會說我要辦門號。","我聽得懂預付卡和月租的差別。","我會問綁約和違約金。","我會問網路方案和流量。","我會問號碼能不能保留。","我能自己一個人去門市辦門號。"],
ladder:[
{lv:"A1",task:"說出來意並交證件",can:"我想辦門號。這是我的護照和居留證。"},
{lv:"A2",task:"選方案並問基本條件",can:"我要預付卡，有吃到飽的嗎？一個月多少錢？"},
{lv:"B1",task:"比較方案、問綁約與違約金",can:"月租要綁幾個月？如果我提前解約，違約金怎麼算？"},
{lv:"B2",task:"依自己的情況談出最適合的方案",can:"我大概只會待一年，綁兩年不划算。有沒有一年約，或是先用預付卡之後再攜碼的做法？"}]
}
);
TC.push(
{
id:"garbage",unit:"在臺灣安頓下來",no:17,
title:"垃圾分類與倒垃圾",viTitle:"Phân loại rác và đi đổ rác",
task:{zh:"學完這一課，你可以自己處理垃圾：聽懂垃圾車的音樂、分辨一般垃圾、資源回收和廚餘，問鄰居垃圾車幾點來、在哪裡停，並且處理大型垃圾。",
vi:"Học xong bài này, bạn có thể tự xử lý rác: nhận ra nhạc xe rác, phân biệt rác thường, rác tái chế và rác thực phẩm, hỏi hàng xóm xe rác mấy giờ đến và dừng ở đâu, và xử lý rác cồng kềnh."},
warmup:["你住的地方垃圾怎麼丟？","你聽過垃圾車的音樂嗎？是什麼歌？","越南的垃圾是怎麼收的？跟臺灣一樣嗎？","你知道什麼是「廚餘」嗎？"],
media:"垃圾車、資源回收車、專用垃圾袋、廚餘桶、回收分類標示。",
dialog:[
{who:"新住戶",zh:"不好意思，請問垃圾車幾點會來？",py:"Bù hǎoyìsi, qǐngwèn lèsè chē jǐ diǎn huì lái?",vi:"Xin lỗi, cho hỏi xe rác mấy giờ đến ạ?"},
{who:"鄰居",zh:"平常晚上七點半左右，星期三和星期日不收。",py:"Píngcháng wǎnshang qī diǎn bàn zuǒyòu, xīngqísān hé xīngqírì bù shōu.",vi:"Thường khoảng bảy giờ rưỡi tối, thứ Tư và Chủ nhật không thu."},
{who:"新住戶",zh:"停在哪裡？",py:"Tíng zài nǎlǐ?",vi:"Dừng ở đâu ạ?"},
{who:"鄰居",zh:"就在巷口那個轉角，聽到音樂就可以下去了。",py:"Jiù zài xiàngkǒu nàge zhuǎnjiǎo, tīng dào yīnyuè jiù kěyǐ xiàqù le.",vi:"Ngay góc đầu ngõ, nghe thấy nhạc là xuống được rồi."},
{who:"新住戶",zh:"垃圾要分類嗎？",py:"Lèsè yào fēnlèi ma?",vi:"Rác có phải phân loại không ạ?"},
{who:"鄰居",zh:"要。一般垃圾丟垃圾車，回收放旁邊那台回收車。",py:"Yào. Yìbān lèsè diū lèsè chē, huíshōu fàng pángbiān nà tái huíshōu chē.",vi:"Phải. Rác thường bỏ xe rác, đồ tái chế để xe tái chế bên cạnh."},
{who:"新住戶",zh:"廚餘呢？",py:"Chúyú ne?",vi:"Còn rác thực phẩm ạ?"},
{who:"鄰居",zh:"廚餘另外倒，車上有桶子，會有人跟你說。",py:"Chúyú lìngwài dào, chē shàng yǒu tǒngzi, huì yǒu rén gēn nǐ shuō.",vi:"Rác thực phẩm đổ riêng, trên xe có thùng, sẽ có người chỉ cho bạn."},
{who:"新住戶",zh:"那垃圾袋可以隨便用嗎？",py:"Nà lèsè dài kěyǐ suíbiàn yòng ma?",vi:"Vậy túi rác dùng loại nào cũng được à?"},
{who:"鄰居",zh:"我們這裡要用專用垃圾袋，超商就有賣。",py:"Wǒmen zhèlǐ yào yòng zhuānyòng lèsè dài, chāoshāng jiù yǒu mài.",vi:"Ở đây phải dùng túi rác chuyên dụng, cửa hàng tiện lợi có bán."},
{who:"新住戶",zh:"了解。那舊的桌子這種大東西怎麼辦？",py:"Liǎojiě. Nà jiù de zhuōzi zhè zhǒng dà dōngxi zěnme bàn?",vi:"Tôi hiểu rồi. Vậy đồ lớn như bàn cũ thì làm sao?"},
{who:"鄰居",zh:"那要打電話跟清潔隊約時間，不能直接丟。",py:"Nà yào dǎ diànhuà gēn qīngjiéduì yuē shíjiān, bù néng zhíjiē diū.",vi:"Cái đó phải gọi điện hẹn với đội vệ sinh, không được vứt thẳng."},
{who:"新住戶",zh:"太好了，謝謝你，不然我完全不知道怎麼弄。",py:"Tài hǎo le, xièxie nǐ, bùrán wǒ wánquán bù zhīdào zěnme nòng.",vi:"Tuyệt quá, cảm ơn bạn, không thì tôi hoàn toàn không biết làm thế nào."}],
keys:[
{zh:"垃圾車幾點會來？",vi:"Xe rác mấy giờ đến?"},
{zh:"停在哪裡？",vi:"Dừng ở đâu?"},
{zh:"垃圾要分類嗎？",vi:"Rác có phải phân loại không?"},
{zh:"這個算回收還是一般垃圾？",vi:"Cái này tính là tái chế hay rác thường?"},
{zh:"廚餘要另外倒。",vi:"Rác thực phẩm phải đổ riêng."},
{zh:"要用專用垃圾袋嗎？",vi:"Có phải dùng túi rác chuyên dụng không?"},
{zh:"大型垃圾怎麼辦？",vi:"Rác cồng kềnh thì làm sao?"},
{zh:"今天有收垃圾嗎？",vi:"Hôm nay có thu rác không?"}],
vocab:[
{w:"垃圾",py:"lèsè",vi:"rác",ex:"垃圾要拿下去丟。"},
{w:"垃圾車",py:"lèsè chē",vi:"xe rác",ex:"垃圾車七點半來。"},
{w:"分類",py:"fēnlèi",vi:"phân loại",ex:"垃圾一定要分類。"},
{w:"回收",py:"huíshōu",vi:"tái chế",ex:"寶特瓶要回收。"},
{w:"廚餘",py:"chúyú",vi:"rác thực phẩm",ex:"廚餘要另外倒。"},
{w:"垃圾袋",py:"lèsè dài",vi:"túi rác",ex:"這裡要用專用垃圾袋。"},
{w:"專用",py:"zhuānyòng",vi:"chuyên dụng",ex:"專用垃圾袋超商有賣。"},
{w:"巷口",py:"xiàngkǒu",vi:"đầu ngõ",ex:"垃圾車停在巷口。"},
{w:"清潔隊",py:"qīngjiéduì",vi:"đội vệ sinh",ex:"大型垃圾要跟清潔隊約。"},
{w:"大型垃圾",py:"dàxíng lèsè",vi:"rác cồng kềnh",ex:"舊沙發算大型垃圾。"},
{w:"寶特瓶",py:"bǎotèpíng",vi:"chai nhựa",ex:"寶特瓶要壓扁再回收。"},
{w:"隨便",py:"suíbiàn",vi:"tùy tiện",ex:"垃圾不可以隨便丟。"}],
vocabNote:"臺灣是「垃圾不落地」——垃圾要親手交給垃圾車，不是放在路邊。垃圾車會放音樂（常見的是〈少女的祈禱〉和〈給愛麗絲〉），資源回收車通常跟在後面。有些縣市（例如臺北市、新北市）規定要用專用垃圾袋，有些縣市不用；收運時間和休息日各里不同，請學生問鄰居或查所在區公所。",
grammar:{pattern:"這個算 A 還是 B？",note:"分不清楚類別的時候用。「算」比「是」軟，表示「歸在哪一類」，問人時不會顯得笨。",
vi:"Dùng khi không phân biệt được loại. Chữ 「算」 nhẹ hơn 「是」, nghĩa là xếp vào loại nào.",
ex:["這個算回收還是一般垃圾？","這個算廚餘嗎？","便當盒算回收嗎？","這算大型垃圾嗎？"],
swap:"這個算＿＿＿＿還是＿＿＿＿？（換成：紙類／塑膠、生廚餘／熟廚餘、可回收／不可回收）"},
listening:[
{t:"聽音樂認垃圾車",d:"播放垃圾車音樂片段，學生判斷垃圾車來了還是回收車來了。"},
{t:"聽內容選答案",d:"垃圾車星期幾不收？(A) 星期一和四 (B) 星期三和日 (C) 週末 (D) 每天都收"},
{t:"聽完填表",d:"填寫：垃圾車時間＿＿＿／停靠地點＿＿＿／不收的日子＿＿＿／要不要專用袋＿＿＿"},
{t:"分類判斷",d:"聽出六樣東西，判斷各屬於一般垃圾、資源回收、還是廚餘。"},
{t:"聽完重說一次",d:"聽完後把倒垃圾的規則講給剛搬來的室友聽。"}],
speaking:{q:["你住的地方垃圾車幾點來？","一般垃圾和回收有什麼不一樣？","你不確定某樣東西怎麼分類，你會怎麼問？","請完整說明你們那裡的倒垃圾規則。"],
model:"我們這裡垃圾車晚上七點半左右來，停在巷口。垃圾要分類，一般垃圾丟垃圾車，回收放旁邊那台車，廚餘另外倒。我們這裡要用專用垃圾袋，超商就有賣。"},
tasks:[
{n:"任務卡 A",d:"你剛搬到新的地方，完全不知道垃圾怎麼丟。請你問鄰居時間、地點、要不要分類、要不要專用袋。"},
{n:"任務卡 B",d:"你手上有便當盒、寶特瓶、剩菜和舊電池。請你說明每一樣該怎麼分。"},
{n:"任務卡 C",d:"你要丟一張舊書桌。請你打電話給清潔隊說明並約時間。"}],
quiz:[
"看圖選詞：（垃圾車／廚餘／寶特瓶／專用垃圾袋）",
"聽音檔選答案：垃圾車停在哪裡？",
"句子排序：幾點／垃圾車／來／會",
"選出最自然的說法：(A) 這個算回收還是一般垃圾 (B) 這個回收一般垃圾算 (C) 算這個回收還是垃圾一般 (D) 回收還是一般垃圾這個算",
"填空：廚餘要＿＿＿＿倒。",
"「垃圾不落地」是什麼意思？(A) 垃圾要放地上 (B) 要親手交給垃圾車 (C) 垃圾丟到樓下 (D) 不用分類",
"你不知道便當盒算不算回收，你會問：＿＿＿",
"錄音完成任務：向剛搬來的朋友說明倒垃圾的時間、地點和分類。"],
selfcheck:["我知道垃圾車幾點來、停哪裡。","我分得出一般垃圾、回收和廚餘。","我知道要不要用專用垃圾袋。","我會問別人某樣東西怎麼分類。","我知道大型垃圾要另外約。","我能自己一個人處理家裡的垃圾。"],
ladder:[
{lv:"A1",task:"問時間和地點",can:"垃圾車幾點來？停在哪裡？"},
{lv:"A2",task:"問分類規則並照做",can:"垃圾要分類嗎？廚餘要另外倒嗎？"},
{lv:"B1",task:"判斷分類並向人說明",can:"便當盒洗乾淨算回收，剩菜是廚餘，要分開。"},
{lv:"B2",task:"處理大型垃圾與例外狀況",can:"這張舊書桌算大型垃圾，我打電話跟清潔隊約時間。如果那天沒空，可以改約嗎？"}]
},
{
id:"arc",unit:"在臺灣安頓下來",no:18,
title:"居留證延期",viTitle:"Gia hạn thẻ cư trú (ARC)",
task:{zh:"學完這一課，你可以辦居留證延期：知道什麼時候要辦、準備哪些文件、到移民署抽號碼牌、聽懂承辦人的問題，並且處理文件不齊的狀況。",
vi:"Học xong bài này, bạn có thể gia hạn thẻ cư trú: biết khi nào phải làm, chuẩn bị giấy tờ gì, lấy số ở Sở Di dân, hiểu câu hỏi của cán bộ, và xử lý khi thiếu giấy tờ."},
warmup:["你的居留證什麼時候到期？","你辦過延期嗎？順利嗎？","居留證過期會怎麼樣？","你知道要提前多久辦嗎？"],
media:"移民署服務站、號碼牌、居留證正反面、申請表、證件照。",
dialog:[
{who:"申請人",zh:"你好，我要辦居留證延期。",py:"Nǐ hǎo, wǒ yào bàn jūliúzhèng yánqí.",vi:"Xin chào, tôi muốn gia hạn thẻ cư trú."},
{who:"承辦人",zh:"好，請問您的居留證什麼時候到期？",py:"Hǎo, qǐngwèn nín de jūliúzhèng shénme shíhòu dàoqí?",vi:"Vâng, xin hỏi thẻ cư trú của anh/chị hết hạn khi nào?"},
{who:"申請人",zh:"下個月十五號。",py:"Xià ge yuè shíwǔ hào.",vi:"Ngày mười lăm tháng sau."},
{who:"承辦人",zh:"還在期限內，可以辦。文件都帶了嗎？",py:"Hái zài qīxiàn nèi, kěyǐ bàn. Wénjiàn dōu dài le ma?",vi:"Vẫn còn trong thời hạn, làm được. Giấy tờ mang đủ chưa ạ?"},
{who:"申請人",zh:"護照、居留證、照片，還有在學證明。",py:"Hùzhào, jūliúzhèng, zhàopiàn, hái yǒu zàixué zhèngmíng.",vi:"Hộ chiếu, thẻ cư trú, ảnh, và giấy chứng nhận đang học."},
{who:"承辦人",zh:"照片是兩年內的嗎？要白底、脫帽。",py:"Zhàopiàn shì liǎng nián nèi de ma? Yào bái dǐ, tuōmào.",vi:"Ảnh chụp trong hai năm chứ ạ? Phải nền trắng, không đội mũ."},
{who:"申請人",zh:"是上個月拍的。請問住址沒有換也要證明嗎？",py:"Shì shàng ge yuè pāi de. Qǐngwèn zhùzhǐ méiyǒu huàn yě yào zhèngmíng ma?",vi:"Chụp tháng trước ạ. Cho hỏi địa chỉ không đổi có cần giấy chứng minh không?"},
{who:"承辦人",zh:"住址沒變就不用。請先填這張申請表。",py:"Zhùzhǐ méi biàn jiù búyòng. Qǐng xiān tián zhè zhāng shēnqǐngbiǎo.",vi:"Địa chỉ không đổi thì không cần. Xin điền vào đơn này trước."},
{who:"申請人",zh:"規費多少？",py:"Guīfèi duōshǎo?",vi:"Lệ phí bao nhiêu ạ?"},
{who:"承辦人",zh:"看您要延幾年，一年一千元。",py:"Kàn nín yào yán jǐ nián, yì nián yìqiān yuán.",vi:"Tùy anh/chị gia hạn mấy năm, một năm một nghìn đồng."},
{who:"申請人",zh:"我延一年就好。大概多久可以拿到？",py:"Wǒ yán yì nián jiù hǎo. Dàgài duōjiǔ kěyǐ ná dào?",vi:"Tôi gia hạn một năm thôi. Khoảng bao lâu thì lấy được ạ?"},
{who:"承辦人",zh:"會用郵寄的，過幾天寄到您登記的地址。",py:"Huì yòng yóujì de, guò jǐ tiān jì dào nín dēngjì de dìzhǐ.",vi:"Sẽ gửi bưu điện, vài ngày nữa gửi tới địa chỉ đã đăng ký."}],
keys:[
{zh:"我要辦居留證延期。",vi:"Tôi muốn gia hạn thẻ cư trú."},
{zh:"我的居留證……到期。",vi:"Thẻ cư trú của tôi hết hạn ngày…"},
{zh:"要準備哪些文件？",vi:"Cần chuẩn bị những giấy tờ gì?"},
{zh:"這樣可以嗎？",vi:"Như vậy được không?"},
{zh:"規費多少？",vi:"Lệ phí bao nhiêu?"},
{zh:"大概多久可以拿到？",vi:"Khoảng bao lâu thì lấy được?"},
{zh:"我少帶了……，可以補嗎？",vi:"Tôi thiếu…, bổ sung sau được không?"},
{zh:"需要重新拍照嗎？",vi:"Có cần chụp lại ảnh không?"}],
vocab:[
{w:"居留證",py:"jūliúzhèng",vi:"thẻ cư trú",ex:"我的居留證下個月到期。"},
{w:"延期",py:"yánqí",vi:"gia hạn",ex:"我要辦延期。"},
{w:"到期",py:"dàoqí",vi:"hết hạn",ex:"護照什麼時候到期？"},
{w:"期限",py:"qīxiàn",vi:"thời hạn",ex:"還在期限內，可以辦。"},
{w:"文件",py:"wénjiàn",vi:"giấy tờ",ex:"文件都帶齊了嗎？"},
{w:"申請表",py:"shēnqǐngbiǎo",vi:"đơn xin",ex:"請先填申請表。"},
{w:"在學證明",py:"zàixué zhèngmíng",vi:"giấy chứng nhận đang học",ex:"學生要附在學證明。"},
{w:"證件照",py:"zhèngjiànzhào",vi:"ảnh thẻ",ex:"證件照要白底脫帽。"},
{w:"規費",py:"guīfèi",vi:"lệ phí",ex:"延一年規費一千元。"},
{w:"移民署",py:"yímínshǔ",vi:"Sở Di dân",ex:"要去移民署辦。"},
{w:"承辦人",py:"chéngbànrén",vi:"cán bộ tiếp nhận",ex:"承辦人會核對文件。"},
{w:"補件",py:"bǔjiàn",vi:"bổ sung giấy tờ",ex:"少帶的可以之後補件。"}],
vocabNote:"依移民署規定，外國人申請延期居留應於居留期限屆滿前三個月內提出。常見文件包含：申請表、二年內證件照一張、護照與居留證正本及影本、原居留目的相關證明（例如在學證明或在職證明）、現居住地證明（住址未變更可免附）。規費依核發效期計算，一年一千元、二年兩千元，依此類推（僑生減半）。規定可能調整，實際以移民署公告為準。",
grammar:{pattern:"要準備哪些 + N？",note:"辦任何手續前最該問的一句。用「哪些」表示要一份清單，比問「要什麼」更清楚。",
vi:"Câu nên hỏi nhất trước khi làm bất kỳ thủ tục nào. Dùng 「哪些」 để xin một danh sách.",
ex:["要準備哪些文件？","要準備哪些證件？","要準備哪些資料？","要帶哪些東西？"],
swap:"要準備哪些＿＿＿＿？（換成：表格／證明／影本／照片）"},
listening:[
{t:"聽對話選文件",d:"播放承辦人說的話，學生從圖片中勾出要準備的文件。"},
{t:"聽內容選答案",d:"延期一年的規費是多少？(A) 500 元 (B) 1,000 元 (C) 2,000 元 (D) 免費"},
{t:"聽完填表",d:"填寫：到期日＿＿＿／延幾年＿＿＿／規費＿＿＿／缺什麼文件＿＿＿"},
{t:"判斷可不可以辦",d:"聽四個人的狀況，判斷誰現在可以辦、誰太早、誰已經過期。"},
{t:"聽完重說一次",d:"聽完後把要準備的文件清單複述一遍。"}],
speaking:{q:["你的居留證什麼時候到期？","延期要準備什麼？","如果少帶一份文件，你會怎麼說？","請完整說一次辦延期的過程。"],
model:"你好，我要辦居留證延期。我的居留證下個月十五號到期。我帶了護照、居留證、照片和在學證明。請問還要準備什麼？規費多少？大概多久可以拿到？"},
tasks:[
{n:"任務卡 A",d:"你的居留證兩個月後到期。請你到移民署辦延期，說明狀況並確認要準備的文件。"},
{n:"任務卡 B",d:"你到現場才發現忘記帶在學證明。請你說明狀況，問可不可以補件或改天再來。"},
{n:"任務卡 C",d:"你的照片是三年前拍的。承辦人說不行。請你問哪裡可以拍、今天還能不能辦完。"}],
quiz:[
"看圖選詞：（居留證／申請表／證件照／號碼牌）",
"聽音檔選答案：這個人要延幾年？",
"句子排序：延期／我／居留證／要辦",
"選出最自然的說法：(A) 哪些文件要準備 (B) 要準備哪些文件 (C) 準備要哪些文件 (D) 文件要哪些準備",
"填空：我的居留證下個月十五號＿＿＿＿。",
"依移民署規定，延期應在居留期限屆滿前多久內提出？(A) 一個月 (B) 三個月 (C) 半年 (D) 一年",
"你忘記帶在學證明，你會說：＿＿＿",
"錄音完成任務：說明要延期一年，並列出你帶了哪些文件。"],
selfcheck:["我知道居留證什麼時候到期。","我知道要提前多久辦延期。","我會列出要準備的文件。","我會回答承辦人的問題。","文件不齊的時候我會問怎麼補。","我能自己一個人去移民署辦延期。"],
ladder:[
{lv:"A1",task:"說出來意和到期日",can:"我要辦延期。我的居留證下個月到期。"},
{lv:"A2",task:"回答文件與年限的問題",can:"我帶了護照、居留證和照片。我延一年。"},
{lv:"B1",task:"確認規定並處理缺件",can:"照片要兩年內的嗎？我少帶在學證明，可以之後補件嗎？"},
{lv:"B2",task:"說明特殊情況並問替代方案",can:"我下個月要換工作，居留原因會變。這樣是先延期還是直接辦變更比較好？"}]
}
);
