/* QNA CHINESE — 教師後台介面越南文字典
   VI_V962／963 第一批＋第二批：側邊選單、分頁、按鈕、表格欄位、狀態、常見提示。
   M = 整句完全相同才換；R = 帶數字的句型，用規則換。
   還沒收錄的句子會維持中文，不會變成空白或亂碼。
   有翻得不好的地方直接跟我說哪一句，我改這個檔案就好，不用動 teacher.html。 */
window.QNA_VI = {
  wave: 5,
  R: [
    ["^共 ?(\\d+(?:\\.\\d+)?) ?堂$", "Tổng cộng $1 buổi"],
    ["^共 ?(\\d+) ?筆$", "Tổng cộng $1 mục"],
    ["^共 ?(\\d+) ?題$", "Tổng cộng $1 câu"],
    ["^共 ?(\\d+) ?課$", "Tổng cộng $1 bài"],
    ["^(\\d+(?:\\.\\d+)?) ?小時$", "$1 giờ"],
    ["^(\\d+(?:\\.\\d+)?) ?堂$", "$1 buổi"],
    ["^(\\d+) ?題$", "$1 câu"],
    ["^(\\d+) ?課$", "$1 bài"],
    ["^(\\d+) ?筆$", "$1 mục"],
    ["^(\\d+) ?份$", "$1 bài"],
    ["^(\\d+) ?位$", "$1 người"],
    ["^(\\d+) ?人$", "$1 người"],
    ["^(\\d+) ?次$", "$1 lần"],
    ["^(\\d+) ?天$", "$1 ngày"],
    ["^(\\d+) ?個生詞$", "$1 từ vựng"],
    ["^(\\d+) ?位學生$", "$1 học viên"],
    ["^還剩 ?(\\d+) ?堂$", "Còn $1 buổi"],
    ["^逾期 ?(\\d+) ?天$", "Quá hạn $1 ngày"],
    ["^還有 ?(\\d+) ?天$", "Còn $1 ngày"],
    ["^已交 ?(\\d+)/(\\d+)$", "Đã nộp $1/$2"],
    ["^儲存失敗：([\\s\\S]*)$", "Lưu thất bại: $1"],
    ["^刪除失敗：([\\s\\S]*)$", "Xoá thất bại: $1"],
    ["^上傳失敗：([\\s\\S]*)$", "Tải lên thất bại: $1"],
    ["^下載失敗：([\\s\\S]*)$", "Tải xuống thất bại: $1"],
    ["^匯出失敗：([\\s\\S]*)$", "Xuất thất bại: $1"],
    ["^載入失敗：([\\s\\S]*)$", "Tải dữ liệu thất bại: $1"],
    ["^讀取失敗：([\\s\\S]*)$", "Đọc dữ liệu thất bại: $1"],
    ["^失敗：([\\s\\S]*)$", "Thất bại: $1"],
    ["^寄送失敗：([\\s\\S]*)$", "Gửi thất bại: $1"],
    ["^尚欠 ?(.+)$", "Còn nợ $1"],
    ["^欠 ?(.+)$", "Nợ $1"],
    ["^預繳 ?(.+)$", "Trả trước $1"],
    ["^應收 ?(.+)$", "Phải thu $1"],
    ["^已收 ?(.+)$", "Đã thu $1"],
    ["^本月收入（(.+)）$", "Thu nhập tháng này ($1)"],
    ["^最新 ?(\\d+) ?筆$", "$1 mục mới nhất"],
    ["^最近 ?(\\d+) ?筆，共 ?(\\d+) ?筆$", "$1 mục gần nhất, tổng $2 mục"],
    ["^還剩 ?(\\d+) ?堂$", "Còn $1 buổi"],
    ["^(\\d+) ?/ ?(\\d+)$", "$1 / $2"],
    /* VI_V966 首頁那幾句是拼出來的（中間夾 <b> 數字），所以要一段一段對 */
    ["^早安，(.+)，今天先做這些。$", "Chào buổi sáng, $1, hôm nay làm mấy việc này nhé."],
    ["^午安，(.+)，今天先做這些。$", "Chào buổi chiều, $1, hôm nay làm mấy việc này nhé."],
    ["^晚安，(.+)，今天先做這些。$", "Chào buổi tối, $1, hôm nay làm mấy việc này nhé."],
    ["^資料更新於 (.+)（週日）$", "Dữ liệu cập nhật lúc $1 (Chủ nhật)"],
    ["^資料更新於 (.+)（週一）$", "Dữ liệu cập nhật lúc $1 (Thứ 2)"],
    ["^資料更新於 (.+)（週二）$", "Dữ liệu cập nhật lúc $1 (Thứ 3)"],
    ["^資料更新於 (.+)（週三）$", "Dữ liệu cập nhật lúc $1 (Thứ 4)"],
    ["^資料更新於 (.+)（週四）$", "Dữ liệu cập nhật lúc $1 (Thứ 5)"],
    ["^資料更新於 (.+)（週五）$", "Dữ liệu cập nhật lúc $1 (Thứ 6)"],
    ["^資料更新於 (.+)（週六）$", "Dữ liệu cập nhật lúc $1 (Thứ 7)"],
    ["^最久的一份已經等了 (\\d+) 天$", "Bài chờ lâu nhất đã chờ $1 ngày"],
    ["^還沒收 (.+)$", "Chưa thu $1"],
    ["^已處理 (.+)$", "Đã xử lý $1"],
    ["^上課 (.+)$", "Buổi học $1"],
    ["^，在未來 ?(\\d+) ?天裡還沒點名、也還沒排過的那幾堂，實際建成$", ", trong $1 ngày tới, những buổi đã đặt giờ cố định nhưng chưa điểm danh và chưa xếp lịch sẽ được tạo thành"]
  ],
  M: {
    /* ── 側邊選單 ── */
    "今日總覽": "Tổng quan hôm nay",
    "學生": "Học viên",
    "課表": "Lịch học",
    "教材與課程": "Giáo trình & bài học",
    "批改・成績": "Chấm bài · Điểm số",
    "課堂活動": "Hoạt động lớp học",
    "留學業務": "Dịch vụ du học",
    "收費・財務": "Thu phí · Tài chính",
    "回覆範本": "Mẫu câu trả lời",
    "使用說明": "Hướng dẫn sử dụng",
    "設定": "Cài đặt",
    "⚙️ 設定": "⚙️ Cài đặt",
    "登出": "Đăng xuất",
    "登入": "Đăng nhập",
    "教　學": "GIẢNG DẠY",
    "業　務": "NGHIỆP VỤ",
    "其　他": "KHÁC",
    "主管理員後台": "Trang quản trị chính",
    "教師管理": "Quản lý giáo viên",
    "華語線上作業簿": "Vở bài tập tiếng Trung trực tuyến",

    /* ── 通用按鈕 ── */
    "儲存": "Lưu",
    "💾 儲存": "💾 Lưu",
    "儲存中…": "Đang lưu…",
    "已儲存": "Đã lưu",
    "儲存失敗": "Lưu thất bại",
    "儲存失敗，請重試": "Lưu thất bại, vui lòng thử lại",
    "取消": "Huỷ",
    "關閉": "Đóng",
    "刪除": "Xoá",
    "已刪除": "Đã xoá",
    "刪除失敗": "Xoá thất bại",
    "移除": "Gỡ bỏ",
    "已移除": "Đã gỡ bỏ",
    "新增": "Thêm mới",
    "編輯": "Sửa",
    "✏️ 編輯": "✏️ Sửa",
    "✏️ 修改": "✏️ Chỉnh sửa",
    "完成": "Hoàn thành",
    "已完成": "Đã hoàn thành",
    "標記完成": "Đánh dấu hoàn thành",
    "失敗": "Thất bại",
    "建立": "Tạo",
    "＋ 建立": "＋ Tạo",
    "建立中…": "Đang tạo…",
    "已建立": "Đã tạo",
    "建立失敗": "Tạo thất bại",
    "更新失敗": "Cập nhật thất bại",
    "已更新": "Đã cập nhật",
    "預覽": "Xem trước",
    "👁 預覽": "👁 Xem trước",
    "處理中…": "Đang xử lý…",
    "載入中…": "Đang tải…",
    "上傳中…": "Đang tải lên…",
    "上傳中…（檔案大時請稍候）": "Đang tải lên… (tệp lớn thì vui lòng đợi một lát)",
    "↻ 重新整理": "↻ Tải lại",
    "⬇ 下載": "⬇ Tải xuống",
    "⬆ 上傳圖片": "⬆ Tải ảnh lên",
    "⬆ 上傳音檔": "⬆ Tải tệp âm thanh lên",
    "⬆ 上傳 PDF": "⬆ Tải PDF lên",
    "⬇ 匯出 Excel": "⬇ Xuất Excel",
    "⬇ 下載完整備份": "⬇ Tải bản sao lưu đầy đủ",
    "全選 / 取消": "Chọn tất cả / Bỏ chọn",
    "✔ 全選在學中": "✔ Chọn tất cả học viên đang học",
    "✕ 清除": "✕ Xoá trắng",
    "▾ 全部展開": "▾ Mở tất cả",
    "已選": "Đã chọn",
    "還沒選人": "Chưa chọn ai",
    "選填": "Không bắt buộc",
    "可以不填": "Có thể để trống",
    "全部": "Tất cả",
    "其他": "Khác",
    "列表": "Danh sách",
    "🖨 列印 / 存成 PDF": "🖨 In / Lưu thành PDF",
    "🖨 列印／PDF": "🖨 In / PDF",
    "列印時這排按鈕不會印出來": "Khi in, hàng nút này sẽ không hiện ra",
    "語言": "Ngôn ngữ",
    "字體": "Font chữ",
    "中文 ＋ Tiếng Việt": "中文 ＋ Tiếng Việt",
    "⋯ 更多": "⋯ Xem thêm",
    "沒有權限": "Không có quyền",
    "這個功能只有主管理員可以用": "Chức năng này chỉ quản trị viên chính mới dùng được",
    "只有主管理員可以用": "Chỉ quản trị viên chính mới dùng được",
    "主管理員": "Quản trị viên chính",
    "老師": "Giáo viên",
    "存不起來": "Không lưu được",
    "未連 Storage": "Chưa kết nối Storage",
    "複製失敗，請手動選取": "Sao chép thất bại, vui lòng tự bôi đen để copy",
    "匯出元件還在載入，請過幾秒再按一次": "Công cụ xuất đang tải, vui lòng bấm lại sau vài giây",

    /* ── 學生・班級 ── */
    "姓名": "Họ tên",
    "姓名 *": "Họ tên *",
    "請填姓名": "Vui lòng nhập họ tên",
    "找不到這位學生": "Không tìm thấy học viên này",
    "還沒有學生": "Chưa có học viên",
    "全部學生": "Tất cả học viên",
    "位學生": "học viên",
    "團班": "Lớp nhóm",
    "一對一": "Học 1 kèm 1",
    "🧑‍🏫 一對一": "🧑‍🏫 Học 1 kèm 1",
    "👥 團班（尚未分班）": "👥 Lớp nhóm (chưa xếp lớp)",
    "班級": "Lớp",
    "課程型態": "Hình thức lớp",
    "國籍": "Quốc tịch",
    "電話": "Điện thoại",
    "電話／Zalo／LINE": "Điện thoại / Zalo / LINE",
    "聯絡方式": "Thông tin liên hệ",
    "基本資料": "Thông tin cơ bản",
    "📋 基本資料": "📋 Thông tin cơ bản",
    "備註": "Ghi chú",
    "換頭像": "Đổi ảnh đại diện",
    "← 回學生列表": "← Về danh sách học viên",
    "去學生頁": "Đến trang học viên",
    "合併帳戶": "Tài khoản gộp",
    "主管理員還沒有把學生分配給你。": "Quản trị viên chính chưa phân học viên cho bạn.",

    /* ── 就學狀態 ── */
    "在學中": "Đang học",
    "試學": "Học thử",
    "休學": "Tạm nghỉ học",
    "已結案": "Đã đóng hồ sơ",
    "預約": "Đặt lịch",
    "預約中": "Đang đặt lịch",
    "預約・詢問中": "Đang tư vấn / đặt lịch",

    /* ── 上課 ── */
    "上課": "Buổi học",
    "上課記錄": "Lịch sử buổi học",
    "🗓 上課記錄": "🗓 Lịch sử buổi học",
    "還沒有上課記錄": "Chưa có buổi học nào",
    "上課時段": "Giờ học",
    "上課日期": "Ngày học",
    "上課內容": "Nội dung buổi học",
    "課後小結": "Tóm tắt sau buổi học",
    "時段": "Khung giờ",
    "日期": "Ngày",
    "日期 *": "Ngày *",
    "請選日期": "Vui lòng chọn ngày",
    "月份": "Tháng",
    "今天": "Hôm nay",
    "明天": "Ngày mai",
    "填今天": "Điền ngày hôm nay",
    "本月": "Tháng này",
    "最近": "Gần đây",
    "最新": "Mới nhất",
    "期間": "Khoảng thời gian",
    "未來": "Sắp tới",
    "開始": "Bắt đầu",
    "截止": "Hạn chót",
    "截止日期": "Hạn nộp",
    "期限": "Thời hạn",
    "沒設期限": "Chưa đặt thời hạn",
    "今天到期": "Đến hạn hôm nay",
    "逾期": "Quá hạn",
    "已過": "Đã qua",
    "快開始了": "Sắp bắt đầu",
    "出席": "Có mặt",
    "出席率": "Tỷ lệ đi học",
    "請假": "Nghỉ có phép",
    "🏖 請假": "🏖 Nghỉ có phép",
    "缺席": "Vắng mặt",
    "補課": "Học bù",
    "免費": "Miễn phí",
    "🎁 免費": "🎁 Miễn phí",
    "時數": "Số giờ",
    "小時": "giờ",
    "堂課": "buổi học",
    "狀態": "Trạng thái",
    "✍️ 去點名": "✍️ Điểm danh",
    "✅ 已點名": "✅ Đã điểm danh",
    "📌 預排": "📌 Lịch dự kiến",
    "🔁 固定時段": "🔁 Giờ cố định",
    "🔁 照上一週排下一週": "🔁 Xếp tuần sau theo tuần trước",
    "‹ 上個月": "‹ Tháng trước",
    "下個月 ›": "Tháng sau ›",
    "＋ 新增時段": "＋ Thêm khung giờ",
    "＋ 新增練習時間": "＋ Thêm buổi luyện tập",
    "排課中…": "Đang xếp lịch…",
    "刪掉這一堂": "Xoá buổi này",
    "線上教室：": "Lớp học trực tuyến:",
    "📝 記一堂課": "📝 Ghi một buổi học",
    "📌 排一堂課": "📌 Xếp một buổi học",
    "💬 寫回饋單": "💬 Viết phiếu nhận xét",

    /* ── 教材・課程 ── */
    "教材": "Giáo trình",
    "課程": "Khoá học",
    "課文": "Bài khoá",
    "課名": "Tên bài",
    "課名 *": "Tên bài *",
    "課序": "Thứ tự bài",
    "第幾課": "Bài số mấy",
    "標題": "Tiêu đề",
    "請填標題": "Vui lòng nhập tiêu đề",
    "內容": "Nội dung",
    "段落": "Đoạn",
    "小節": "Tiểu mục",
    "小節（選填）": "Tiểu mục (không bắt buộc)",
    "生詞": "Từ vựng",
    "生詞語法": "Từ vựng & ngữ pháp",
    "語法": "Ngữ pháp",
    "語法練習": "Luyện ngữ pháp",
    "屬於哪個語法點": "Thuộc điểm ngữ pháp nào",
    "例句": "Câu ví dụ",
    "對話": "Hội thoại",
    "對話一": "Hội thoại 1",
    "短文": "Bài đọc ngắn",
    "原文": "Nguyên văn",
    "注釋": "Chú thích",
    "聽力": "Nghe hiểu",
    "發音": "Phát âm",
    "發音教材": "Giáo trình phát âm",
    "儲存發音課": "Lưu bài phát âm",
    "已上傳發音": "Đã tải lên phát âm",
    "▶ 試聽": "▶ Nghe thử",
    "此瀏覽器不支援錄音，請改用上傳": "Trình duyệt này không hỗ trợ ghi âm, vui lòng tải tệp lên",
    "文言文": "Hán văn cổ",
    "📜 文言文": "📜 Hán văn cổ",
    "講義": "Tài liệu bài giảng",
    "📄 講義（PDF）": "📄 Tài liệu bài giảng (PDF)",
    "作業": "Bài tập",
    "作業簿": "Vở bài tập",
    "📒 作業簿": "📒 Vở bài tập",
    "📒 挑作業": "📒 Chọn bài tập",
    "作業完成": "Bài tập đã hoàn thành",
    "作業成績": "Điểm bài tập",
    "完成作業": "Bài tập đã hoàn thành",
    "還沒做": "Chưa làm",
    "練習": "Luyện tập",
    "練習題": "Bài luyện tập",
    "課文練習": "Luyện bài khoá",
    "題庫練習": "Bài luyện từ ngân hàng đề",
    "造句": "Đặt câu",
    "課後問答": "Hỏi đáp sau buổi học",
    "問題與討論": "Câu hỏi & thảo luận",
    "隨堂小考": "Kiểm tra nhanh",
    "📝 隨堂小考": "📝 Kiểm tra nhanh",
    "小考": "Bài kiểm tra ngắn",
    "題目": "Câu hỏi",
    "題型": "Dạng câu hỏi",
    "小題": "Câu nhỏ",
    "選項": "Lựa chọn",
    "單選": "Chọn một",
    "填空": "Điền vào chỗ trống",
    "配對": "Nối",
    "重組": "Sắp xếp lại",
    "問答": "Hỏi đáp",
    "示範": "Ví dụ mẫu",
    "正確答案": "Đáp án đúng",
    "參考答案": "Đáp án tham khảo",
    "✅ 補參考答案": "✅ Bổ sung đáp án tham khảo",
    "找不到題庫": "Không tìm thấy ngân hàng đề",
    "這本還沒有課。": "Sách này chưa có bài nào.",
    "還沒有課文": "Chưa có bài khoá",
    "看拼音寫字": "Nhìn pinyin viết chữ",
    "看意思寫字": "Nhìn nghĩa viết chữ",
    "看字選意思": "Nhìn chữ chọn nghĩa",
    "看例句填生詞": "Xem câu ví dụ điền từ vựng",
    "建立並編輯": "Tạo rồi sửa",
    "建立全部": "Tạo tất cả",
    "課標成完成": "Đánh dấu bài đã xong",
    "📢 發佈內容": "📢 Đăng nội dung",
    "👥 發佈": "👥 Đăng",
    "已發佈": "Đã đăng",
    "學生會看到": "Học viên sẽ nhìn thấy",
    "學生現在看不到": "Hiện học viên chưa nhìn thấy",
    "所有學生登入首頁都會看到": "Mọi học viên đăng nhập vào trang chủ đều nhìn thấy",
    "📌 套用到全班學生": "📌 Áp dụng cho cả lớp",
    "儲存成員": "Lưu thành viên",
    "🖥 上課投影片": "🖥 Slide bài giảng",

    /* ── 批改 ── */
    "批改": "Chấm bài",
    "去批改": "Vào chấm bài",
    "待批改": "Chờ chấm",
    "已交": "Đã nộp",
    "作答中": "Đang làm bài",
    "未開始": "Chưa bắt đầu",
    "分數": "Điểm",
    "平均": "Trung bình",
    "答對率": "Tỷ lệ đúng",
    "百分比": "Phần trăm",
    "✓ 對": "✓ Đúng",
    "✗ 錯": "✗ Sai",
    "整體評語": "Nhận xét chung",
    "整體鼓勵或建議…": "Lời động viên hoặc góp ý chung…",
    "給這一題的建議（學生會看到）": "Góp ý cho câu này (học viên sẽ thấy)",
    "儲存建議": "Lưu góp ý",
    "💾 儲存建議": "💾 Lưu góp ý",
    "已儲存建議": "Đã lưu góp ý",
    "已批改，學生可看到建議": "Đã chấm, học viên xem được góp ý",
    "已改回進行中": "Đã chuyển lại thành “đang làm”",
    "目前沒有待批改的項目 🎉": "Hiện không có mục nào chờ chấm 🎉",
    "老師的話": "Lời nhắn của giáo viên",
    "這個月的進步": "Tiến bộ trong tháng này",
    "謝謝你這段時間的努力 ♡": "Cảm ơn em đã cố gắng trong thời gian qua ♡",
    "開口說": "Luyện nói",
    "專心度": "Mức độ tập trung",
    "上課回饋單": "Phiếu nhận xét buổi học",
    "月總結": "Tổng kết tháng",
    "📄 學習報告": "📄 Báo cáo học tập",

    /* ── 財務 ── */
    "繳費": "Nộp phí",
    "💰 繳費": "💰 Nộp phí",
    "💰 記繳費": "💰 Ghi nộp phí",
    "💰 記一筆收款": "💰 Ghi một khoản thu",
    "繳費記錄": "Lịch sử nộp phí",
    "學費": "Học phí",
    "未設學費": "Chưa đặt học phí",
    "計費": "Tính phí",
    "單價": "Đơn giá",
    "沒填單價": "Chưa điền đơn giá",
    "沒設單價": "Chưa đặt đơn giá",
    "金額": "Số tiền",
    "金額 *": "Số tiền *",
    "請填金額": "Vui lòng nhập số tiền",
    "合計": "Tổng cộng",
    "數量": "Số lượng",
    "幣別": "Loại tiền",
    "總費用幣別": "Loại tiền của tổng phí",
    "臺幣 NT$": "Đài tệ (TWD)",
    "美元 US$": "Đô la Mỹ (USD)",
    "越南盾 VND": "Đồng Việt Nam (VND)",
    "越南盾 VND（打千位）": "Đồng Việt Nam (VND) – nhập theo đơn vị nghìn",
    "越南盾打千位": "Nhập VND theo đơn vị nghìn",
    "VND 千": "Nghìn VND",
    "折合帳單幣別": "Quy đổi sang loại tiền của hoá đơn",
    "未換算": "Chưa quy đổi",
    "付款日": "Ngày thanh toán",
    "收款日期 *": "Ngày thu tiền *",
    "收款方式": "Hình thức thanh toán",
    "💳 收款帳號": "💳 Tài khoản nhận tiền",
    "帳號": "Tài khoản",
    "應收": "Phải thu",
    "已收": "Đã thu",
    "已繳": "Đã nộp",
    "· 已繳": "· Đã nộp",
    "尚欠": "Còn nợ",
    "預繳": "Trả trước",
    "結餘": "Số dư",
    "已結清": "Đã thanh toán đủ",
    "✅ 已結清": "✅ Đã thanh toán đủ",
    "累計": "Luỹ kế",
    "累計應收": "Tổng phải thu",
    "累計實收": "Tổng đã thu",
    "累計收入": "Thu nhập luỹ kế",
    "還沒收到": "Chưa nhận được",
    "🔴 還沒收": "🔴 Chưa thu",
    "🧾 目前應收：": "🧾 Phải thu hiện tại:",
    "已處理": "Đã xử lý",
    "退費單": "Phiếu hoàn phí",
    "價目表": "Bảng giá",
    "價目表還是空的": "Bảng giá vẫn trống",
    "名稱": "Tên",
    "項目": "Hạng mục",
    "類別": "Phân loại",
    "💰 開一張報價單": "💰 Lập một bảng báo giá",
    "📊 匯出對帳資料": "📊 Xuất dữ liệu đối chiếu",
    "收入會併進「營運 → 🧮 總收入」。": "Khoản thu sẽ được gộp vào “Vận hành → 🧮 Tổng thu nhập”.",

    /* ── 留學業務 ── */
    "留學代辦": "Dịch vụ du học",
    "代辦": "Dịch vụ",
    "代辦申請": "Hồ sơ dịch vụ",
    "代書": "Dịch vụ viết hồ sơ",
    "文件代寫": "Dịch vụ viết hồ sơ",
    "申請學校": "Trường nộp hồ sơ",
    "學校": "Trường",
    "客戶資料": "Thông tin khách hàng",
    "看客戶": "Xem khách hàng",
    "刪除這位客戶": "Xoá khách hàng này",
    "文件名稱": "Tên hồ sơ",
    "入學申請資料表": "Phiếu thông tin đăng ký nhập học",
    "自傳": "Bài tự thuật (giới thiệu bản thân)",
    "推薦信": "Thư giới thiệu",
    "修改讀書計畫": "Sửa kế hoạch học tập",
    "承辦人": "Người phụ trách",
    "階段": "Giai đoạn",
    "進度": "Tiến độ",
    "＋ 新增一筆進度": "＋ Thêm một mốc tiến độ",
    "交件": "Nộp hồ sơ",
    "還缺": "Còn thiếu",
    "這一本還缺": "Sách này còn thiếu",
    "📄 正式案件": "📄 Hồ sơ chính thức",
    "✕ 沒談成": "✕ Không chốt được",
    "面試": "Phỏng vấn",
    "面試日": "Ngày phỏng vấn",
    "面試練習": "Luyện phỏng vấn",
    "🎤 面試練習": "🎤 Luyện phỏng vấn",
    "🎯 正式面試": "🎯 Phỏng vấn chính thức",
    "面試目標": "Mục tiêu phỏng vấn",
    "✅ 通過": "✅ Đạt",
    "❌ 沒通過": "❌ Không đạt",
    "📎 上傳／查看檔案": "📎 Tải lên / xem tệp",
    "📤 上傳區": "📤 Khu tải lên",
    "檔案": "Tệp",
    "個檔案": "tệp",
    "📋 提醒訊息": "📋 Tin nhắn nhắc nhở",
    "📄 報告與證書": "📄 Báo cáo & chứng chỉ",
    "✉️ 聯絡與提醒": "✉️ Liên hệ & nhắc nhở",
    "📁 檔案與紀錄": "📁 Tệp & hồ sơ",
    "📌 其他": "📌 Khác",
    "＋ 記下來": "＋ Ghi lại",
    "待處理": "Chờ xử lý",
    "目前": "Hiện tại",
    "中文": "Tiếng Trung",
    "說明": "Hướng dẫn",
    "類型": "Loại",
    "開立時間": "Thời gian lập",
    "華語教學 · 留學代辦": "Dạy tiếng Trung · Dịch vụ du học",
    "中文課 ·": "Lớp tiếng Trung ·",
    "手寫": "Viết tay",
    "還有": "Còn",
    "都可以": "Đều được",
    "換上面的分類看看。": "Thử đổi phân loại ở trên xem.",
    "還沒到（今天是": "Chưa đến (hôm nay là",
    "例：Nguyễn Văn A": "Ví dụ: Nguyễn Văn A",
    "例：500": "Ví dụ: 500",
    "例：A、B": "Ví dụ: A, B",
    "選填。填了才會算「還差多少」": "Không bắt buộc. Điền vào mới tính được “còn thiếu bao nhiêu”",
    "選填，會在「待辦」提醒": "Không bắt buộc, sẽ nhắc ở mục “Việc cần làm”",
    "📧 有人報名時通知我": "📧 Báo cho tôi khi có người đăng ký",
    "第 1 步": "Bước 1",
    "第 2 步": "Bước 2",
    "學生名單": "Danh sách học viên",
    "👥 學生名單": "👥 Danh sách học viên",
    "團班每位學生各自繳自己的。": "Mỗi học viên trong lớp nhóm tự đóng phần của mình.",
    "成員": "Thành viên",
    "成員／時段": "Thành viên / Giờ học",
    "班級資訊": "Thông tin lớp",
    "課程模組": "Mô-đun bài học",
    "繳交狀況": "Tình hình nộp bài",
    "🗓 上課點名": "🗓 Điểm danh buổi học",
    "🖨 班級總覽": "🖨 Tổng quan lớp",
    "📤 匯出這班的學生": "📤 Xuất học viên lớp này",
    "已上課": "Đã học",
    "下次上課": "Buổi học kế tiếp",
    "還沒排": "Chưa xếp lịch",
    "還沒點過名": "Chưa điểm danh lần nào",
    "已上": "Đã học",
    "目前結餘": "Số dư hiện tại",
    "還沒開始上課": "Chưa bắt đầu học",
    "還沒設定學費": "Chưa đặt học phí",
    "總覽": "Tổng quan",
    "📋 週報": "📋 Báo cáo tuần",
    "💰 收款": "💰 Thu tiền",
    "📤 匯出": "📤 Xuất dữ liệu",
    "🎥 教室": "🎥 Phòng học",
    "📁 資料夾": "📁 Thư mục",
    "⋯ 更多工具": "⋯ Công cụ khác",
    "🔎 完整檔案": "🔎 Hồ sơ đầy đủ",
    "📄 檔案卡": "📄 Thẻ hồ sơ",
    "🧾 對帳單": "🧾 Bảng đối chiếu công nợ",
    "＋ 記一堂課": "＋ Ghi một buổi học",
    "＋ 記一筆繳費": "＋ Ghi một khoản nộp phí",
    "還沒有繳費記錄。": "Chưa có lịch sử nộp phí.",
    "還沒有繳費記錄": "Chưa có lịch sử nộp phí",
    "還沒有成員": "Chưa có thành viên",
    "收款金額": "Số tiền đã thu",
    "這個分頁只有主管理員看得到。": "Trang này chỉ quản trị viên chính mới xem được.",
    "待辦": "Việc cần làm",
    "今天要處理": "Cần xử lý hôm nay",
    "今天的課": "Buổi học hôm nay",
    "備忘": "Ghi chú",
    "本月收入": "Thu nhập tháng này",
    "尚未收款": "Chưa thu tiền",
    "堂數快用完": "Sắp hết số buổi",
    "費用明細": "Chi tiết chi phí",
    "華語教學": "Dạy tiếng Trung",
    "營運": "Vận hành",
    "🧮 總收入": "🧮 Tổng thu nhập",

    /* ══ 第二批 VI_V963 ══ */
    /* 今日總覽 */
    "早安": "Chào buổi sáng",
    "午安": "Chào buổi chiều",
    "晚安": "Chào buổi tối",
    "QNA CHINESE · 教師工作台": "QNA CHINESE · Bàn làm việc giáo viên",
    "資料更新於": "Dữ liệu cập nhật lúc",
    "今天有": "Hôm nay có",
    "份作業等你批改": "bài tập đang chờ chấm",
    "最久的一份已經等了": "Bài chờ lâu nhất đã chờ",
    "今天沒有待批改的作業": "Hôm nay không có bài nào chờ chấm",
    "；另外有": "; ngoài ra có",
    "位學生的學費還沒收到": "học viên chưa nộp học phí",
    "✍️ 去批改": "✍️ Vào chấm bài",
    "待辦提醒": "Nhắc việc cần làm",
    "我負責的學生": "Học viên tôi phụ trách",
    "目前沒有記著的事。想到什麼就打在上面，做完打勾。": "Hiện chưa ghi việc nào. Nghĩ ra gì thì gõ ở trên, xong thì tích vào.",
    "目前沒有待辦": "Hiện không có việc cần làm",
    "目前沒有需要提醒的事項 👍": "Hiện không có việc nào cần nhắc 👍",
    "目前沒有即將到期或逾期的付款 👍": "Hiện không có khoản nào sắp đến hạn hoặc quá hạn 👍",
    "目前沒有欠款的學生 👍": "Hiện không có học viên nào còn nợ 👍",
    "目前沒有待批改的作業 👍": "Hiện không có bài tập nào chờ chấm 👍",
    "目前沒有待批改的造句 👍": "Hiện không có bài đặt câu nào chờ chấm 👍",
    "目前沒有待批改的問題與討論 👍": "Hiện không có câu hỏi & thảo luận nào chờ chấm 👍",
    "目前每一位學生的作業都交齊了 👍": "Hiện tất cả học viên đều đã nộp đủ bài 👍",
    "先到「學生名冊」新增學生。": "Hãy vào “Danh sách học viên” để thêm học viên trước.",
    "💰 欠": "💰 Nợ",
    "🔁 待補": "🔁 Chờ học bù",
    "補登": "Ghi bù",
    "🎯 待填結果": "🎯 Chờ điền kết quả",
    "填面試結果": "Điền kết quả phỏng vấn",
    "交件已過": "Đã quá hạn nộp hồ sơ",
    "今天要交件！": "Hôm nay phải nộp hồ sơ!",
    "明天要交件": "Ngày mai phải nộp hồ sơ",
    "繳件已過": "Đã quá hạn nộp",
    "今天要繳件！": "Hôm nay phải nộp!",
    "明天要繳件": "Ngày mai phải nộp",
    "還沒備份過": "Chưa sao lưu lần nào",
    "這週還沒備份": "Tuần này chưa sao lưu",
    "📦 備份": "📦 Sao lưu",
    "改標題、內容或日期": "Sửa tiêu đề, nội dung hoặc ngày",
    "刪掉這一件": "Xoá việc này",
    "要哪天做完（可不填）": "Ngày hoàn thành (có thể bỏ trống)",
    "已逾期": "Đã quá hạn",

    /* 課表 */
    "週一": "Thứ 2", "週二": "Thứ 3", "週三": "Thứ 4", "週四": "Thứ 5",
    "週五": "Thứ 6", "週六": "Thứ 7", "週日": "Chủ nhật",
    "星期": "Thứ",
    "結束": "Kết thúc",
    "加堂": "Thêm buổi",
    "進入教室": "Vào lớp học",
    "進入教室（開新分頁進入 Google Meet）": "Vào lớp (mở tab mới tới Google Meet)",
    "刪除時段": "Xoá khung giờ",
    "還沒有上課時段，請先到上面新增": "Chưa có khung giờ học, vui lòng thêm ở trên",
    "請選擇": "Vui lòng chọn",
    "🗓 排課": "🗓 Xếp lịch",
    "把某一週的課整組往後排": "Dời cả tuần học sang tuần sau",
    "📆 這一週": "📆 Tuần này",
    "🗓 這個月": "🗓 Tháng này",
    "👥 上課記錄": "👥 Lịch sử buổi học",
    "固定週表": "Lịch tuần cố định",
    "預排的課": "Buổi đã xếp trước",
    "各自一次。": "mỗi loại một lần.",
    "會排成每週重複，": "sẽ lặp lại hằng tuần,",
    "📅 加入日曆": "📅 Thêm vào lịch",
    "📅 匯出全部上課日曆": "📅 Xuất toàn bộ lịch học",
    "含已休學": "Gồm cả học viên đã tạm nghỉ",
    "這個月還沒有課": "Tháng này chưa có buổi học nào",
    "各學生計費堂數": "Số buổi tính phí của từng học viên",
    "整個團班刪掉這一堂": "Xoá buổi này cho cả lớp nhóm",
    "台灣時間（GMT+8）": "Giờ Đài Loan (GMT+8)",
    "越南時間 ＝ 台灣 − 1 小時": "Giờ Việt Nam = giờ Đài Loan − 1 tiếng",
    "🕒 時間都以": "🕒 Mọi giờ đều theo",
    "為準；": "làm chuẩn;",
    "這一堂上了哪一課": "Buổi này học bài nào",
    "✅ 記錄這一堂並點名": "✅ Ghi buổi này và điểm danh",
    "✅ 加入預排": "✅ Thêm vào lịch dự kiến",
    "已排": "Đã xếp",
    "已記錄": "Đã ghi",
    "全選": "Chọn tất cả",
    "全不選": "Bỏ chọn tất cả",
    "排課失敗": "Xếp lịch thất bại",
    "這個團班還沒有成員": "Lớp nhóm này chưa có thành viên",
    "那天已經點名過": "Ngày đó đã điểm danh rồi",
    "那天已經排過": "Ngày đó đã xếp lịch rồi",
    "🚀 排下去": "🚀 Xếp lịch",
    "請至少選一位學生": "Vui lòng chọn ít nhất một học viên",
    "🌙 請假（照計）": "🌙 Nghỉ có phép (vẫn tính phí)",
    "🌙 請假": "🌙 Nghỉ có phép",
    "🙈 缺席": "🙈 Vắng mặt",
    "不計費": "Không tính phí",
    "⏱ 這堂": "⏱ Buổi này",

    /* 教材・課程 */
    "🎒 試做": "🎒 Làm thử",
    "📤 送出": "📤 Nộp",
    "其他練習": "Bài luyện khác",
    "解答": "Đáp án",
    "學生版": "Bản học viên",
    "要出哪一課": "Chọn bài nào để ra đề",
    "要出哪幾課": "Chọn những bài nào để ra đề",
    "未發佈": "Chưa đăng",
    "標題 *": "Tiêu đề *",
    "圖片已上傳": "Đã tải ảnh lên",
    "圖片好了": "Ảnh đã sẵn sàng",
    "已上傳": "Đã tải lên",
    "⬆ 上傳": "⬆ Tải lên",
    "⬆ 上傳檔案": "⬆ Tải tệp lên",
    "＋ 加一題": "＋ Thêm một câu",
    "⏹ 停止": "⏹ Dừng",
    "🎙 錄音": "🎙 Ghi âm",
    "● 錄音中…再按一次停止": "● Đang ghi âm… bấm lần nữa để dừng",
    "無法使用麥克風，請允許權限或改用上傳": "Không dùng được micro, hãy cấp quyền hoặc tải tệp lên",
    "無法讀取音檔：": "Không đọc được tệp âm thanh:",
    "課號": "Mã bài",
    "課文段落": "Đoạn bài khoá",
    "內文": "Nội dung",
    "影片": "Video",
    "🎬 影片": "🎬 Video",
    "課室活動": "Hoạt động trong lớp",
    "文化": "Văn hoá",
    "聽力文本": "Văn bản bài nghe",
    "答案": "Đáp án",
    "放哪一邊": "Đặt ở bên nào",
    "屬於哪個語法": "Thuộc điểm ngữ pháp nào",
    "音檔": "Tệp âm thanh",
    "圖片": "Hình ảnh",
    "口說": "Nói",
    "單元": "Chương",
    "回家作業": "Bài về nhà",
    "課數": "Số bài",
    "題數": "Số câu",
    "發佈進度": "Tiến độ đăng bài",
    "學生進度": "Tiến độ học viên",
    "已有": "Đã có",
    "沒有練習題": "Chưa có bài luyện tập",
    "題目都齊了": "Câu hỏi đã đủ",
    "還沒有人做完": "Chưa có ai làm xong",
    "要發給：": "Đăng cho:",
    "發佈給誰": "Đăng cho ai xem",
    "儲存發佈": "Lưu đăng bài",
    "儲存順序": "Lưu thứ tự",
    "已套用": "Đã áp dụng",
    "請輸入課名": "Vui lòng nhập tên bài",
    "這本教材沒有課，換一本試試。": "Giáo trình này chưa có bài, thử đổi sang cuốn khác.",
    "上面選一本教材。": "Chọn một giáo trình ở trên.",
    "還沒選學生。": "Chưa chọn học viên.",
    "已移到垃圾桶（可復原）": "Đã chuyển vào thùng rác (có thể khôi phục)",
    "復原": "Khôi phục",
    "收回中…": "Đang thu hồi…",
    "已收回發佈，學生已看不到": "Đã thu hồi, học viên không còn nhìn thấy",
    "收回這份練習": "Thu hồi bài luyện này",
    "正解：": "Đáp án đúng:",
    "沒有可留空": "Không có thì để trống",
    "投影片.pdf": "slide.pdf",
    "放在整課最上面，例如作者畫像或情境圖": "Đặt ở đầu bài, ví dụ chân dung tác giả hoặc ảnh tình huống",
    "上傳作業簿": "Tải vở bài tập lên",
    "上傳練習": "Tải bài luyện tập lên",
    "小考練習": "Bài kiểm tra ngắn",
    "自訂題目": "Câu hỏi tự soạn",
    "🎙️ 老師錄音聽寫": "🎙️ Chính tả qua ghi âm của giáo viên",
    "聽寫": "Chính tả",
    "＋ 建立隨堂小考": "＋ Tạo bài kiểm tra nhanh",
    "🎮 即時比賽（Kahoot 式）": "🎮 Thi đấu trực tiếp (kiểu Kahoot)",
    "＋ 新增即時比賽題庫（自己出題）": "＋ Thêm ngân hàng đề thi đấu (tự soạn)",
    "· 可以重做": "· Được làm lại",
    "· 只能做一次": "· Chỉ làm được một lần",
    "做完": "Làm xong",
    "做完的": "Đã làm xong",
    "改期限": "Đổi thời hạn",
    "📤 指派出去": "📤 Giao bài",
    "📤 指派出去的題庫練習": "📤 Bài luyện từ ngân hàng đề đã giao",
    "還沒有指派過。挑一份題庫按「📤 指派」就可以了。": "Chưa giao lần nào. Chọn một ngân hàng đề rồi bấm “📤 Giao bài” là được.",
    "二 寫出拼音": "2. Viết pinyin",
    "三 寫出中國字": "3. Viết chữ Hán",
    "四 句子重組": "4. Sắp xếp lại câu",
    "六 圖片描述": "6. Miêu tả tranh",
    "七 語法練習": "7. Luyện ngữ pháp",
    "A 聲調辨識": "A. Nhận biết thanh điệu",
    "B 選出發音": "B. Chọn cách phát âm",
    "發音課": "Bài phát âm",
    "＋ 開放上傳格子": "＋ Mở ô nộp bài",
    "請先輸入區域名稱": "Vui lòng nhập tên khu vực trước",
    "把檔案拖進來，或點這裡選檔": "Kéo tệp vào đây, hoặc bấm để chọn tệp",
    "📎 檔案 ·": "📎 Tệp ·",
    "✅ 已上傳": "✅ Đã tải lên",
    "挑幾組練習當回家作業": "Chọn vài nhóm bài luyện làm bài về nhà",
    "常用：": "Thường dùng:",

    /* 批改・成績 */
    "成績": "Điểm số",
    "得分": "Điểm đạt",
    "答對": "Trả lời đúng",
    "總題數": "Tổng số câu",
    "顆星": "sao",
    "未評": "Chưa đánh giá",
    "操作": "Thao tác",
    "儲存評語": "Lưu nhận xét",
    "✓ 已寫": "✓ Đã viết",
    "寫這一堂的回饋單": "Viết phiếu nhận xét buổi này",
    "找不到這一堂": "Không tìm thấy buổi học này",
    "這位學生還沒有上課記錄": "Học viên này chưa có buổi học nào",
    "這個月沒有上課記錄": "Tháng này chưa có buổi học nào",
    "上課回饋": "Nhận xét buổi học",
    "華語教學 · 教師回饋單": "Dạy tiếng Trung · Phiếu nhận xét của giáo viên",
    "學習總結": "Tổng kết học tập",
    "需要改進": "Cần cải thiện",
    "下個月練習": "Luyện tập tháng sau",
    "學生資料": "Dữ liệu học viên",
    "學生檔案": "Hồ sơ học viên",
    "✨ 幫我擬草稿": "✨ Soạn bản nháp giúp tôi",
    "✨ AI 幫我翻越南文（草稿）": "✨ AI dịch sang tiếng Việt (bản nháp)",
    "AI 想一下…": "AI đang nghĩ…",
    "還沒設定 AI 金鑰。": "Chưa thiết lập khoá AI.",
    "這是 AI 草稿，還沒存檔、學生也還看不到。": "Đây là bản nháp AI, chưa lưu và học viên chưa nhìn thấy.",
    "＋整體評語": "＋ Nhận xét chung",
    "已送出，等主管理員確認": "Đã gửi, chờ quản trị viên chính xác nhận",
    "已退回": "Đã trả lại",
    "送出失敗": "Gửi thất bại",
    "未設截止日": "Chưa đặt hạn nộp",
    "份未交": "bài chưa nộp",
    "全部未交": "Tất cả chưa nộp",
    "📋 複製提醒訊息": "📋 Sao chép tin nhắn nhắc nhở",
    "📋 複製": "📋 Sao chép",
    "沒有逾期或快到期的作業 👍　（按「看全部未交」可以看其他的）": "Không có bài nào quá hạn hoặc sắp đến hạn 👍 (bấm “Xem tất cả chưa nộp” để xem thêm)",
    "· 七天內到期": "· Đến hạn trong 7 ngày",
    "💡 在課文的「發佈」裡設「截止日期」，這裡才會自動排出誰快遲交。": "💡 Đặt “Hạn nộp” trong phần “Đăng” của bài khoá thì ở đây mới tự xếp ra ai sắp trễ.",

    /* 繳費・對帳 */
    "計費單位": "Đơn vị tính phí",
    "計費方式": "Cách tính phí",
    "每小時": "Mỗi giờ",
    "每堂": "Mỗi buổi",
    "上課筆數": "Số buổi học",
    "付費日期": "Ngày thanh toán",
    "請選收款日期": "Vui lòng chọn ngày thu",
    "已記錄收款 ✓": "Đã ghi khoản thu ✓",
    "刪除這筆收款紀錄？": "Xoá khoản thu này?",
    "繳費收據": "Biên lai nộp phí",
    "月結單": "Bảng kê hàng tháng",
    "對帳單": "Bảng đối chiếu công nợ",
    "對帳總表": "Bảng đối chiếu tổng hợp",
    "報價單": "Bảng báo giá",
    "客戶": "Khách hàng",
    "面試練習繳費": "Phí luyện phỏng vấn",
    "要匯出哪幾張表？": "Xuất những bảng nào?",
    "每一堂一列，含這堂算多少錢": "Mỗi buổi một dòng, kèm số tiền của buổi đó",
    "每一筆收款一列": "Mỗi khoản thu một dòng",
    "全部（不限期間）": "Tất cả (không giới hạn thời gian)",
    "自己指定起訖日": "Tự chọn ngày bắt đầu và kết thúc",
    "至少要勾一張表": "Phải chọn ít nhất một bảng",
    "起日不能晚於迄日": "Ngày bắt đầu không được sau ngày kết thúc",
    "最早": "Sớm nhất",
    "已匯出": "Đã xuất",
    "筆資料": "mục dữ liệu",
    "還沒勾任何學生": "Chưa chọn học viên nào",
    "這個條件下沒有學生": "Không có học viên nào theo điều kiện này",
    "⚠ 學費未設定": "⚠ Chưa đặt học phí",
    "⚠ 未換算": "⚠ Chưa quy đổi",
    "✅ 結清": "✅ Thanh toán đủ",
    "🟠 溢繳": "🟠 Nộp dư",
    "點一下切換：這位學生自己看不看得到費用": "Bấm để bật/tắt: học viên này có xem được học phí hay không",
    "👁 學生看得到": "👁 Học viên xem được",
    "🙈 學生看不到": "🙈 Học viên không xem được",
    "· 與": "· Chung với",
    "共用": "dùng chung",
    "🎟️ 已上": "🎟️ Đã học",
    "沒設「每堂多少錢」，所以算不出應收": "Chưa đặt “mỗi buổi bao nhiêu tiền” nên không tính được khoản phải thu",
    "不影響學生上課，但會讓堂數／收入統計不準，有空修一修。": "Những mục này không ảnh hưởng việc học, nhưng làm thống kê số buổi / thu nhập sai lệch, nên tranh thủ sửa lại.",
    "去修正": "Vào sửa",
    "💰 收錢請到左邊選單的「💰 繳費」，所有學生（含團班）都在那一頁記。": "💰 Thu tiền vui lòng vào “💰 Nộp phí” ở menu bên trái, mọi học viên (kể cả lớp nhóm) đều ghi ở trang đó.",

    /* 留學業務・文件 */
    "代辦客戶": "Khách hàng dịch vụ du học",
    "去代辦申請": "Đến hồ sơ dịch vụ",
    "申請文件清單": "Danh sách hồ sơ cần nộp",
    "還沒有文件清單": "Chưa có danh sách hồ sơ",
    "收到／寄出的日期": "Ngày nhận / gửi",
    "備註（選填）": "Ghi chú (không bắt buộc)",
    "刪掉這一列": "Xoá dòng này",
    "方向": "Chiều nhận / gửi",
    "護照影本": "Bản sao hộ chiếu",
    "身分證影本": "Bản sao CCCD/CMND",
    "最高學歷畢業證書（經驗證）": "Bằng tốt nghiệp cao nhất (đã chứng thực)",
    "歷年成績單（經驗證）": "Bảng điểm các năm (đã chứng thực)",
    "中文或英文能力證明": "Chứng chỉ năng lực tiếng Trung hoặc tiếng Anh",
    "財力證明／存款證明": "Chứng minh tài chính / xác nhận số dư tiết kiệm",
    "證件照（白底）": "Ảnh thẻ (nền trắng)",
    "讀書計畫": "Kế hoạch học tập",
    "健康檢查表": "Giấy khám sức khoẻ",
    "申請表（本人簽名）": "Đơn đăng ký (có chữ ký)",
    "填好的入學申請表": "Đơn nhập học đã điền đầy đủ",
    "學校錄取通知書": "Giấy báo trúng tuyển",
    "學校繳費單／收據": "Phiếu thu / biên lai của trường",
    "簽證面試需要的文件": "Hồ sơ cần cho phỏng vấn visa",
    "年 / 月 / 日": "Ngày / Tháng / Năm",
    "是 Có ／ 否 Không": "Có / Không",
    "填寫說明 / Hướng dẫn điền": "Hướng dẫn điền",
    "以上資料均為本人親自填寫，內容屬實。": "Tôi xin cam đoan những thông tin trên là do chính tôi điền và hoàn toàn đúng sự thật.",
    "清單是空的，先按「📋 帶入範本」或自己加幾列": "Danh sách đang trống, hãy bấm “📋 Dùng mẫu” hoặc tự thêm vài dòng",
    "列印日期": "Ngày in",
    "沒填日期的就是還沒收到／還沒寄出。": "Mục chưa có ngày là chưa nhận / chưa gửi.",
    "Word 檔已下載": "Đã tải tệp Word",
    "使用說明卡": "Thẻ hướng dẫn sử dụng",
    "練習題卷": "Phiếu bài luyện tập",
    "學習報告": "Báo cáo học tập",
    "結業證書": "Giấy chứng nhận hoàn thành khoá học",
    "🎓 留學業務": "🎓 Dịch vụ du học",
    "🧑‍🏫 教學": "🧑‍🏫 Giảng dạy",
    "👧 對方比我小": "👧 Người kia nhỏ tuổi hơn",
    "🧑 對方比我大": "🧑 Người kia lớn tuổi hơn",
    "🤝 平輩・不確定": "🤝 Ngang tuổi · không chắc",
    "叫對方 em，自己是 chị": "Gọi đối phương là em, mình là chị",
    "叫對方 anh／chị，自己是 em": "Gọi đối phương là anh/chị, mình là em",
    "用 bạn／mình": "Dùng bạn / mình",

    /* 回覆範本・價目表 */
    "有中文": "Có tiếng Trung",
    "沒有中文": "Không có tiếng Trung",
    "有越南文": "Có tiếng Việt",
    "沒有越南文": "Không có tiếng Việt",
    "沒有關鍵字": "Không có từ khoá",
    "還沒有內容——按「✏️ 編輯」把說法打進去": "Chưa có nội dung — bấm “✏️ Sửa” để nhập cách nói vào",
    "刪除這一份": "Xoá mẫu này",
    "📮 回覆客人": "📮 Trả lời khách",
    "一份": "một mẫu",
    "搜尋：語言學校、碩士、團班…": "Tìm: trường tiếng, thạc sĩ, lớp nhóm…",
    "符合": "khớp",
    "份還沒填內容": "mẫu chưa có nội dung",
    "把範本列印或存成 PDF，可以挑分類、語言和字體": "In mẫu hoặc lưu PDF, có thể chọn phân loại, ngôn ngữ và phông chữ",
    "還沒有任何範本": "Chưa có mẫu nào",
    "按「＋ 新增一份」建立，例如「申請語言學校費用」。": "Bấm “＋ Thêm một mẫu” để tạo, ví dụ “Phí đăng ký trường tiếng”.",
    "中文和越南文各存一份，之後客人一問就複製貼上。": "Lưu cả bản tiếng Trung và tiếng Việt, khách hỏi là sao chép dán ngay.",
    "＋ 新增一份": "＋ Thêm một mẫu",
    "＋ 新增一個項目": "＋ Thêm một hạng mục",
    "先把你的項目和單價設進去，": "Hãy đặt hạng mục và đơn giá của bạn vào trước,",
    "要一次把所有費用傳給客人，或是印一張留底，就用這兩顆": "Muốn gửi toàn bộ bảng phí cho khách hoặc in một bản lưu thì dùng hai nút này",
    "搬到只有主管理員讀得到的位置": "Chuyển đến nơi chỉ quản trị viên chính đọc được",

    /* 程度 */
    "入門": "Nhập môn", "基礎": "Cơ bản", "初階": "Sơ cấp",
    "進階": "Nâng cao", "高階": "Cao cấp", "流利": "Lưu loát", "精通": "Thông thạo",

    /* 設定・管理 */
    "＋ 新增管理員": "＋ Thêm quản trị viên",
    "請輸入 Email 與密碼": "Vui lòng nhập Email và mật khẩu",
    "Email 格式不正確": "Định dạng Email không đúng",
    "密碼不正確": "Mật khẩu không đúng",
    "系統預設": "Mặc định hệ thống",
    "寄測試通知": "Gửi thông báo thử",
    "你現在是": "Bạn hiện là",
    "聯絡：": "Liên hệ:",
    "🧪 測試": "🧪 Thử nghiệm",
    "發生錯誤": "Đã xảy ra lỗi",
    "存不進去": "Không lưu được",
    "只有主管理員可以做這個動作": "Chỉ quản trị viên chính mới làm được thao tác này",
    "資料還沒載入完，請稍候再試": "Dữ liệu chưa tải xong, vui lòng thử lại sau",
    "這個分頁顯示時發生問題": "Trang này gặp sự cố khi hiển thị",
    "請允許彈出視窗後再按一次": "Vui lòng cho phép cửa sổ bật lên rồi bấm lại",
    "標楷體 ＋ Times New Roman —— 標準": "Kaiti ＋ Times New Roman —— Tiêu chuẩn",
    "跟平台一樣": "Giống cài đặt của nền tảng",
    "已開放給學生 ✅": "Đã mở cho học viên ✅",
    "已對學生關閉": "Đã đóng với học viên",
    "跟原本一樣，沒有實際變動。": "Giống hệt bản gốc, không có thay đổi thực tế.",
    "改前": "Trước khi sửa",
    "改後": "Sau khi sửa",
    "剛剛讀的": "Vừa đọc",
    "分鐘前讀的": "phút trước",
    "小時前讀的": "giờ trước",
    "基本資料與學費": "Thông tin cơ bản và học phí",
    "基本資料與上課記錄": "Thông tin cơ bản và lịch sử buổi học",
    "每位學生的上課時段與 Meet 教室": "Giờ học và phòng Meet của từng học viên",
    "管理員 ·": "Quản trị viên ·",
    "越南名字不用打聲調——打 Luong 就找得到 Lương。": "Tên tiếng Việt không cần gõ dấu — gõ Luong là tìm được Lương.",
    "只列前 6 筆": "Chỉ hiện 6 mục đầu",
    "正在搬移中，請稍等…": "Đang chuyển dữ liệu, vui lòng đợi…",
    "沒有需要搬移的資料": "Không có dữ liệu cần chuyển",
    "搬移中…": "Đang chuyển…",

    /* ══ VI_V966 首頁拼出來的句子，一段一段 ══ */
    "今天沒有待批改的作業；另外有": "Hôm nay không có bài nào chờ chấm; ngoài ra có",
    "位學生的學費還沒收到。往下有「今天要處理」和「今天的課」。": "học viên chưa nộp học phí. Bên dưới có “Cần xử lý hôm nay” và “Buổi học hôm nay”.",
    "。往下有「今天要處理」和「今天的課」。": ". Bên dưới có “Cần xử lý hôm nay” và “Buổi học hôm nay”.",
    "，還有": ", còn",
    /* 繳費頁 */
    "還沒收": "Chưa thu",
    "✅ 都收齊了": "✅ Đã thu đủ",
    "＋ 記一筆": "＋ Ghi một khoản",
    "✅ 已處理": "✅ Đã xử lý",
    "人": "người",
    /* ── V980 按鈕統一之後補的三句 ── */
    "🔎 開啟班級頁": "🔎 Mở trang lớp",
    "📝 練習題": "📝 Bài luyện tập",
    "＋ 記一筆付費": "＋ Ghi một khoản thanh toán",
    /* ── 第四批 V979：到處都會看到的短字（按鈕、標籤、狀態） ── */
    "上移": "Chuyển lên",
    "下移": "Chuyển xuống",
    "不同": "Khác nhau",
    "不要": "Không",
    "你好": "Xin chào",
    "價格": "Giá",
    "共上": "Đã học tổng cộng",
    "再考": "Làm lại bài",
    "出題": "Ra đề",
    "分成": "Chia thành",
    "功能": "Chức năng",
    "加入": "Thêm vào",
    "否定": "Phủ định",
    "單號": "Số phiếu",
    "寄出": "Gửi đi",
    "寫出": "Viết ra",
    "已幫": "Đã giúp",
    "帳務": "Sổ sách",
    "性別": "Giới tính",
    "打開": "Mở",
    "持平": "Không đổi",
    "指定": "Chỉ định",
    "搬好": "Đã chuyển xong",
    "收到": "Đã nhận",
    "最快": "Sớm nhất",
    "未收": "Chưa thu",
    "歸類": "Phân loại",
    "沒課": "Không có buổi học",
    "清除": "Xoá trắng",
    "版本": "Phiên bản",
    "用法": "Cách dùng",
    "疑問": "Nghi vấn",
    "科系": "Ngành học",
    "簡體": "Giản thể",
    "結構": "Cấu trúc",
    "緊湊": "Gọn",
    "繁體": "Phồn thể",
    "表現": "Thể hiện",
    "補件": "Bổ sung hồ sơ",
    "要把": "Muốn chuyển",
    "討論": "Thảo luận",
    "詞彙": "Từ vựng",
    "詞語": "Từ ngữ",
    "負責": "Phụ trách",
    "退費": "Hoàn phí",
    "送件": "Nộp hồ sơ",
    "這筆": "Mục này",
    "重點": "Trọng tâm",
    "開啟": "Mở",
    "預排": "Lịch dự kiến",
    "點選": "Bấm chọn",
    "· 共": "· Tổng",
    "· 第": "· Buổi thứ",
    "❌ 錯": "❌ Sai",
    "⭕ 對": "⭕ Đúng",
    "代辦費": "Phí dịch vụ du học",
    "使用中": "Đang dùng",
    "刪不掉": "Không xoá được",
    "印圖片": "In hình ảnh",
    "可複選": "Chọn được nhiều",
    "已公開": "Đã công khai",
    "已匯入": "Đã nhập vào",
    "已取消": "Đã huỷ",
    "已帶入": "Đã điền vào",
    "已指派": "Đã giao",
    "已改成": "Đã đổi thành",
    "已結束": "Đã kết thúc",
    "已隱藏": "Đã ẩn",
    "已預排": "Đã xếp lịch dự kiến",
    "待審核": "Chờ duyệt",
    "或自訂": "Hoặc tự nhập",
    "打勾＝": "Tích chọn =",
    "挑學生": "Chọn học viên",
    "挑戰版": "Bản nâng cao",
    "排到第": "Xếp đến buổi thứ",
    "換一張": "Đổi ảnh khác",
    "改不了": "Không sửa được",
    "改不動": "Không sửa được",
    "改好了": "Đã sửa xong",
    "期間內": "Trong khoảng thời gian này",
    "本課程": "Khoá học này",
    "欄位用": "Ô này dùng",
    "沒內容": "Không có nội dung",
    "沒問題": "Không có vấn đề gì",
    "生存版": "Bản cơ bản",
    "生活版": "Bản đời sống",
    "發給誰": "Giao cho ai",
    "管理員": "Quản trị viên",
    "老師版": "Bản giáo viên",
    "茲證明": "Nay chứng nhận",
    "要建立": "Cần tạo",
    "要算誰": "Tính cho ai",
    "詞彙表": "Bảng từ vựng",
    "說明…": "Mô tả…",
    "辦簽證": "Làm visa",
    "這一節": "Tiểu mục này",
    "選題型": "Chọn dạng câu hỏi",
    "＋自訂": "＋ Tự nhập",
    "# 綜合": "# Tổng hợp",
    "[拼音]": "[Pinyin]",
    "· 已上": "· Đã học",
    "· 還剩": "· Còn lại",
    "→下一行": "→ Dòng tiếp theo",
    "↩ 收回": "↩ Thu hồi",
    "【例句】": "[Câu ví dụ]",
    "【練習】": "[Bài luyện tập]",
    "【說明】": "[Giải thích]",
    "一、聽力": "I. Nghe hiểu",
    "一行一題": "Mỗi dòng một câu",
    "上傳失敗": "Tải lên thất bại",
    "中文姓名": "Họ tên tiếng Trung",
    "主題詞彙": "Từ vựng theo chủ đề",
    "五、閱讀": "V. Đọc hiểu",
    "今天已寫": "Hôm nay đã viết",
    "今天已記": "Hôm nay đã ghi",
    "今天截止": "Hạn chót hôm nay",
    "今天有課": "Hôm nay có buổi học",
    "代書客戶": "Khách dịch vụ viết hồ sơ",
    "代書資料": "Thông tin dịch vụ viết hồ sơ",
    "代辦收款": "Thu phí dịch vụ du học",
    "代辦資料": "Thông tin dịch vụ du học",
    "作答方式": "Cách trả lời",
    "作答空間": "Chỗ trống để viết",
    "全部收齊": "Đã nhận đủ",
    "全部期間": "Toàn bộ thời gian",
    "全部類型": "Tất cả các loại",
    "出席狀況": "Tình hình đi học",
    "刪除區塊": "Xoá khối này",
    "刪除小節": "Xoá tiểu mục",
    "刪除整組": "Xoá cả nhóm",
    "加入中…": "Đang thêm…",
    "匯入中…": "Đang nhập dữ liệu…",
    "匯入失敗": "Nhập dữ liệu thất bại",
    "即時儲存": "Lưu tức thì",
    "取得學位": "Lấy bằng",
    "哪一堂課": "Buổi học nào",
    "單價 *": "Đơn giá *",
    "單元／課": "Chương / Bài",
    "在校成績": "Kết quả học tập ở trường",
    "在臺親友": "Người thân ở Đài Loan",
    "填申請表": "Điền đơn đăng ký",
    "天後到期": "ngày nữa đến hạn",
    "天後截止": "ngày nữa hết hạn",
    "套用失敗": "Áp dụng thất bại",
    "學校回覆": "Phản hồi của trường",
    "學生作答": "Bài làm của học viên",
    "學生姓名": "Họ tên học viên",
    "學生給我": "Học viên gửi cho tôi",
    "學習概況": "Tổng quan học tập",
    "學習進度": "Tiến độ học tập",
    "宗教信仰": "Tôn giáo",
    "寫作練習": "Luyện viết",
    "小考名稱": "Tên bài kiểm tra ngắn",
    "尚未上傳": "Chưa tải lên",
    "尚無音檔": "Chưa có tệp âm thanh",
    "就讀期間": "Thời gian theo học",
    "建議修改": "Gợi ý sửa",
    "思源宋體": "Noto Serif",
    "思源黑體": "Noto Sans",
    "我現場唸": "Tôi đọc trực tiếp",
    "我給學生": "Tôi gửi cho học viên",
    "手機號碼": "Số điện thoại",
    "拼音 b": "Pinyin b",
    "搬移失敗": "Chuyển dữ liệu thất bại",
    "整班發佈": "Giao cho cả lớp",
    "整節共用": "Dùng chung cho cả tiểu mục",
    "文件清單": "Danh sách hồ sơ",
    "新增中…": "Đang thêm…",
    "新增項目": "Thêm mục mới",
    "新增題庫": "Thêm ngân hàng đề",
    "更新日期": "Ngày cập nhật",
    "最近上課": "Buổi học gần nhất",
    "最高學歷": "Trình độ học vấn cao nhất",
    "期限改成": "Đổi hạn thành",
    "本月已收": "Tháng này đã thu",
    "本月應收": "Tháng này phải thu",
    "本月結餘": "Số dư tháng này",
    "本月練習": "Bài luyện tháng này",
    "本期：共": "Kỳ này: tổng",
    "正確順序": "Thứ tự đúng",
    "母親職業": "Nghề nghiệp của mẹ",
    "母親電話": "Điện thoại của mẹ",
    "每行一個": "Mỗi dòng một mục",
    "沒有變動": "Không có thay đổi",
    "注音 ㄅ": "Bopomofo ㄅ",
    "測驗名稱": "Tên bài kiểm tra",
    "父親職業": "Nghề nghiệp của cha",
    "父親電話": "Điện thoại của cha",
    "班級資料": "Thông tin lớp",
    "現有團班": "Lớp nhóm hiện có",
    "產生證書": "Tạo giấy chứng nhận",
    "申請資料": "Hồ sơ đăng ký",
    "畢業年月": "Tháng năm tốt nghiệp",
    "目前記在": "Hiện đang ghi ở",
    "篩選結果": "Kết quả lọc",
    "累計結餘": "Số dư luỹ kế",
    "結業日期": "Ngày hoàn thành khoá học",
    "結算月份": "Tháng quyết toán",
    "結算期間": "Kỳ quyết toán",
    "編輯項目": "Sửa mục",
    "編輯題庫": "Sửa ngân hàng đề",
    "繳報名費": "Nộp phí đăng ký",
    "翻譯文件": "Dịch giấy tờ",
    "老師評語": "Nhận xét của giáo viên",
    "考哪一課": "Kiểm tra bài nào",
    "聽力對話": "Hội thoại nghe",
    "聽力理解": "Nghe hiểu",
    "聽寫生詞": "Chính tả từ vựng",
    "自動批改": "Chấm tự động",
    "自己回答": "Tự trả lời",
    "英文檢定": "Chứng chỉ tiếng Anh",
    "華語檢定": "Chứng chỉ tiếng Trung",
    "複製中…": "Đang sao chép…",
    "複製失敗": "Sao chép thất bại",
    "要做什麼": "Cần làm gì",
    "要匯出誰": "Xuất dữ liệu của ai",
    "要把全部": "Muốn chuyển tất cả",
    "記錄中…": "Đang ghi…",
    "記錄失敗": "Ghi thất bại",
    "詞彙選擇": "Chọn từ vựng",
    "詞語測驗": "Kiểm tra từ ngữ",
    "語法說明": "Giải thích ngữ pháp",
    "說明：…": "Giải thích: …",
    "請填教材": "Vui lòng chọn giáo trình",
    "請填課名": "Vui lòng nhập tên bài",
    "請選客戶": "Vui lòng chọn khách hàng",
    "請選月份": "Vui lòng chọn tháng",
    "護照號碼": "Số hộ chiếu",
    "讀取失敗": "Đọc dữ liệu thất bại",
    "退回失敗": "Trả lại thất bại",
    "這份練習": "Bài luyện này",
    "這個月有": "Tháng này có",
    "這次費用": "Chi phí lần này",
    "還沒交的": "Chưa nộp",
    "還沒作答": "Chưa làm bài",
    "郵遞區號": "Mã bưu chính",
    "錄音題目": "Câu hỏi ghi âm",
    "開立日期": "Ngày lập",
    "閱讀測驗": "Kiểm tra đọc hiểu",
    "關鍵詞語": "Từ khoá",
    "面試安排": "Sắp xếp phỏng vấn",
    "面試客戶": "Khách hàng phỏng vấn",
    "面試當天": "Ngày phỏng vấn",
    "面試資料": "Hồ sơ phỏng vấn",
    "頒發單位": "Đơn vị cấp",
    "＋ 排課": "＋ Xếp lịch học",
    "＋ 新增": "＋ Thêm mới",
    "🅰 字體": "🅰 Font chữ",
    "🎓 證書": "🎓 Giấy chứng nhận",
    "🎤 錄音": "🎤 Ghi âm",
    "👥 學生": "👥 Học viên",
    "📂 檔案": "📂 Tệp",
    "📎 檔案": "📎 Tệp",
    "🔊 音檔": "🔊 Tệp âm thanh",
    "🖼 圖片": "🖼 Hình ảnh",
    "🗑 刪除": "🗑 Xoá",
    "# 作業簿": "# Vở bài tập",
    "# 語法1": "# Ngữ pháp 1",
    "# 語法4": "# Ngữ pháp 4",
    "· 共發佈": "· Đã giao tổng cộng",
    "· 這一週": "· Tuần này",
    "← 上一步": "← Bước trước",
    "② 收檔案": "② Nhận tệp",
    "✅ 已儲存": "✅ Đã lưu",
    "✍️ 代書": "✍️ Dịch vụ viết hồ sơ",
    "✏️ 成員": "✏️ Thành viên",
    "✕ 看全部": "✕ Xem tất cả",
    "・你填的是": "· Bạn đã điền là",
    "三、配合題": "III. Nối ghép",
    "上課專心度": "Mức độ tập trung trong giờ học",
    "下一步 →": "Bước tiếp theo →",
    "不自動算分": "Không tự động tính điểm",
    "付費紀錄？": "Lịch sử thanh toán?",
    "作業與成績": "Bài tập và điểm số",
    "作者・背景": "Tác giả · Bối cảnh",
    "例：250": "Ví dụ: 250",
    "例：300": "Ví dụ: 300",
    "例：進階級": "Ví dụ: Cấp nâng cao",
    "公證／驗證": "Công chứng / Chứng thực",
    "刪掉這一題": "Xoá câu này",
    "刪除此團班": "Xoá lớp nhóm này",
    "刪除這個音": "Xoá âm này",
    "原本的記錄": "Bản ghi gốc",
    "另一種幣別": "Loại tiền khác",
    "只出作業簿": "Chỉ ra bài trong vở bài tập",
    "回饋單合集": "Tổng hợp phiếu nhận xét",
    "學中文多久": "Đã học tiếng Trung bao lâu",
    "學生檔案卡": "Thẻ hồ sơ học viên",
    "實際付款日": "Ngày thanh toán thực tế",
    "寫讀書計畫": "Viết kế hoạch học tập",
    "尚無學生。": "Chưa có học viên.",
    "已上傳 ✓": "Đã tải lên ✓",
    "已上傳講義": "Đã tải tài liệu bài giảng lên",
    "已儲存 ✓": "Đã lưu ✓",
    "已儲存評語": "Đã lưu nhận xét",
    "已取消公開": "Đã huỷ công khai",
    "已取消期限": "Đã huỷ hạn chót",
    "已清掉草稿": "Đã xoá bản nháp",
    /* ── 第五批 V981：到處都會看到的短句（5～8 字） ── */
    "已清除總額": "Đã xoá tổng số tiền",
    "已過期 ·": "Đã quá hạn ·",
    "建立新團班": "Tạo lớp nhóm mới",
    "我先錄好音": "Tôi ghi âm sẵn",
    "手寫（大）": "Viết tay (lớn)",
    "把下面訊息": "Đem tin nhắn dưới đây",
    "文件・學校": "Giấy tờ · Trường",
    "文言文閱讀": "Đọc Hán văn cổ",
    "新增管理員": "Thêm quản trị viên",
    "日期可以填": "Ngày có thể điền",
    "月 · 共": "tháng · tổng",
    "期限・結果": "Hạn chót · Kết quả",
    "本對帳單由": "Bảng đối chiếu công nợ này do",
    "本月結單由": "Bảng kê tháng này do",
    "母親出生年": "Năm sinh của mẹ",
    "無自動分數": "Không có điểm tự động",
    "父親出生年": "Năm sinh của bố",
    "生詞・語法": "Từ vựng · Ngữ pháp",
    "發音・聲調": "Phát âm · Thanh điệu",
    "目前的檔案": "Tệp hiện có",
    "自己打題目": "Tự nhập câu hỏi",
    "要哪天做完": "Cần làm xong ngày nào",
    "要發哪幾課": "Giao những bài nào",
    "請先選一課": "Vui lòng chọn một bài trước",
    "請貼上內容": "Vui lòng dán nội dung vào",
    "請輸入名字": "Vui lòng nhập tên",
    "護照效期至": "Hộ chiếu có hạn đến",
    "越南文姓名": "Họ tên tiếng Việt",
    "這一份給誰": "Bản này gửi cho ai",
    "開放給學生": "Mở cho học viên",
    "音檔已上傳": "Đã tải tệp âm thanh lên",
    "頁：月總結": "trang: Tổng kết tháng",
    "＋ 加一級": "＋ Thêm một bậc",
    "👁 看清單": "👁 Xem danh sách",
    "👤 管理員": "👤 Quản trị viên",
    "🖨 學生版": "🖨 Bản học viên",
    "5 顆星最好": "5 sao là cao nhất",
    "· 上課記錄": "· Lịch sử buổi học",
    "· 學習報表": "· Báo cáo học tập",
    "· 小考作答": "· Bài kiểm tra ngắn đã làm",
    "· 登入紀錄": "· Lịch sử đăng nhập",
    "↗ 預覽官網": "↗ Xem trước trang web",
    "⏳ 等你批改": "⏳ Chờ bạn chấm",
    "✅ 再試一次": "✅ Thử lại lần nữa",
    "✅ 確定轉換": "✅ Xác nhận chuyển đổi",
    "✓ 建立小考": "✓ Tạo bài kiểm tra ngắn",
    "✕ 不用草稿": "✕ Không dùng bản nháp",
    "✕ 全部取消": "✕ Bỏ chọn tất cả",
    "一次只改一塊": "Mỗi lần chỉ sửa một khối",
    "不要重新整理": "Đừng tải lại trang",
    "五 完成對話": "V. Hoàn thành hội thoại",
    "交了什麼文件": "Đã nộp giấy tờ gì",
    "份、上課回饋": "bản, phiếu nhận xét buổi học",
    "份回覆範本和": "mẫu câu trả lời và",
    "你改成的日期": "Ngày bạn đã sửa thành",
    "例：週二晚班": "Ví dụ: Lớp tối thứ 3",
    "修改自我介紹": "Sửa phần tự giới thiệu",
    "儲存團班資訊": "Lưu thông tin lớp nhóm",
    "兄弟姊妹人數": "Số anh chị em",
    "內容不能空著": "Nội dung không được để trống",
    "六 語法練習": "VI. Luyện ngữ pháp",
    "印一張空白的": "In một bản trắng",
    "原檔不會外流": "Tệp gốc không bị lộ ra ngoài",
    "單位（中文）": "Đơn vị (tiếng Trung)",
    "四 完成對話": "IV. Hoàn thành hội thoại",
    "回報面試結果": "Báo kết quả phỏng vấn",
    "圖片上傳中…": "Đang tải hình ảnh lên…",
    "圖片上傳失敗": "Tải hình ảnh lên thất bại",
    "在學中的學生": "Học viên đang học",
    "堂、完成作業": "buổi, bài tập đã hoàn thành",
    "報價有效天數": "Số ngày báo giá còn hiệu lực",
    "學生不會看到": "Học viên sẽ không nhìn thấy",
    "學生基本資料": "Thông tin cơ bản của học viên",
    "安排練習時間": "Sắp xếp giờ luyện tập",
    "完成一次練習": "Hoàn thành một buổi luyện tập",
    "客人姓名 *": "Tên khách hàng *",
    "寄學生資料表": "Gửi phiếu thông tin học viên",
    "寫一張回饋單": "Viết một phiếu nhận xét",
    "已刪除發音課": "Đã xoá bài phát âm",
    "已放回諮詢中": "Đã chuyển lại thành đang tư vấn",
    "已新增管理員": "Đã thêm quản trị viên",
    "已標成沒談成": "Đã đánh dấu là không thành",
    "已移除管理員": "Đã gỡ quản trị viên",
    "已記錄這一堂": "Đã ghi lại buổi học này",
    "已選 0 位": "Đã chọn 0 người",
    "很用心，讚！": "Rất chăm chỉ, giỏi lắm!",
    "打不開這一筆": "Không mở được mục này",
    "打名字篩選…": "Gõ tên để lọc…",
    "提醒面試時間": "Nhắc giờ phỏng vấn",
    "收到學生資料": "Đã nhận thông tin học viên",
    "收到錄取通知": "Đã nhận thư báo trúng tuyển",
    "是否曾被拒簽": "Đã từng bị từ chối visa chưa",
    "是否需要宿舍": "Có cần ký túc xá không",
    "會印在最下面": "Sẽ in ở dưới cùng",
    "每一小題下面": "Dưới mỗi câu nhỏ",
    "每週固定時段": "Giờ cố định hàng tuần",
    "沒收錢就留空": "Không thu tiền thì để trống",
    "沒有作答資料": "Không có dữ liệu bài làm",
    "由你親自批改": "Do bạn tự chấm",
    "發給整個團班": "Giao cho cả lớp nhóm",
    "發音很清楚！": "Phát âm rất rõ ràng!",
    "目前：看不到": "Hiện tại: không xem được",
    "目前：看得到": "Hiện tại: xem được",
    "第一志願學校": "Trường nguyện vọng 1",
    "第一志願科系": "Ngành nguyện vọng 1",
    "第一課的期限": "Hạn chót của bài 1",
    "第二志願學校": "Trường nguyện vọng 2",
    "第二志願科系": "Ngành nguyện vọng 2",
    "給學生的評語": "Nhận xét gửi học viên",
    "聽力文本練習": "Luyện văn bản bài nghe",
    "要改哪一塊？": "Muốn sửa khối nào?",
    "設為正確答案": "Đặt làm đáp án đúng",
    "評語（選填）": "Nhận xét (không bắt buộc)",
    "試學（免費）": "Học thử (miễn phí)",
    "說明（中文）": "Giải thích (tiếng Trung)",
    "課文也印出來": "In cả bài khoá ra",
    "課本＋作業簿": "Sách giáo khoa ＋ Vở bài tập",
    "請先勾選學生": "Vui lòng chọn học viên trước",
    "請填學校名稱": "Vui lòng điền tên trường",
    "請填項目名稱": "Vui lòng điền tên mục",
    "請將左右配對": "Vui lòng nối trái với phải",
    "請選付費日期": "Vui lòng chọn ngày thanh toán",
    "請選完成日期": "Vui lòng chọn ngày hoàn thành",
    "越南文／英文": "Tiếng Việt / Tiếng Anh",
    "越南身分證號": "Số CCCD Việt Nam",
    "這次要唸幾句": "Lần này đọc mấy câu",
    "還沒有團班。": "Chưa có lớp nhóm.",
    "還沒有學生。": "Chưa có học viên.",
    "開口說・互動": "Nói · Tương tác",
    "開新分頁登入": "Mở tab mới để đăng nhập",
    "預計入學學期": "Học kỳ dự kiến nhập học",
    "題題目是空的": "câu hỏi đang để trống",
    "＋ 加一個音": "＋ Thêm một âm",
    "＋ 新增一題": "＋ Thêm một câu",
    "＋ 新增注釋": "＋ Thêm chú thích",
    "＋ 新增詢問": "＋ Thêm khách hỏi",
    "🌐 官網內容": "🌐 Nội dung trang web",
    "🎓 代辦申請": "🎓 Hồ sơ du học",
    "🎓 結業證書": "🎓 Giấy chứng nhận hoàn thành",
    "🏆 最終排名": "🏆 Xếp hạng cuối cùng",
    "🏫 學校名冊": "🏫 Danh bạ trường",
    "👥 團班管理": "👥 Quản lý lớp nhóm",
    "💬 老師的話": "💬 Lời nhắn của giáo viên",
    "💰 付費 ·": "💰 Thanh toán ·",
    "💾 儲存修改": "💾 Lưu thay đổi",
    "💾 儲存備註": "💾 Lưu ghi chú",
    "💾 儲存總額": "💾 Lưu tổng số tiền",
    "📄 匯出講義": "📄 Xuất tài liệu bài giảng",
    "📈 學習進度": "📈 Tiến độ học tập",
    "📊 學習報表": "📊 Báo cáo học tập",
    "📊 繳交狀況": "📊 Tình hình nộp bài",
    "📋 學習總結": "📋 Tổng kết học tập",
    "📋 複製訊息": "📋 Sao chép tin nhắn",
    "📚 課程模組": "📚 Mô-đun bài học",
    "📢 費用公開": "📢 Công khai học phí",
    "📤 批次指派": "📤 Giao hàng loạt",
    "🔗 班級資訊": "🔗 Thông tin lớp",
    "🕒 登入紀錄": "🕒 Lịch sử đăng nhập",
    "🖥 有投影片": "🖥 Có slide",
    "🖨 只印答案": "🖨 Chỉ in đáp án",
    "🖼 情境圖片": "🖼 Hình minh hoạ tình huống",
    "🚀 新手引導": "🚀 Hướng dẫn cho người mới",
    "⚙️ 功能設定": "⚙️ Cài đặt chức năng",
    "✏️ 改這一件": "✏️ Sửa mục này",
    "✓ 你判定：對": "✓ Bạn chấm: Đúng",
    "✓ 記今天上課": "✓ Ghi buổi học hôm nay",
    "✗ 你判定：錯": "✗ Bạn chấm: Sai",
    "✨ 自動加拼音": "✨ Tự động thêm phiên âm",
    "⬆ 上傳新檔案": "⬆ Tải tệp mới lên",
    "⭐ 今天的表現": "⭐ Biểu hiện hôm nay",
    "一次講一件就好": "Mỗi lần chỉ nói một việc thôi",
    "上傳生詞音檔…": "Tải tệp âm thanh từ vựng…",
    "上傳課文音檔…": "Tải tệp âm thanh bài khoá…",
    "不勾＝整課都出": "Không đánh dấu = ra cả bài",
    "今天已經記過了": "Hôm nay đã ghi rồi",
    "例：第 3 課": "Ví dụ: Bài 3",
    "全部（含休學）": "Tất cả (gồm cả đã tạm nghỉ)",
    "刪除這筆進度？": "Xoá mục tiến độ này?",
    "勾選要報的項目": "Đánh dấu mục muốn đăng ký",
    "印出填好的內容": "In nội dung đã điền",
    "只出課本練習題": "Chỉ ra bài luyện trong sách",
    "圖片位子已更新": "Đã cập nhật vị trí hình ảnh",
    "學生給我的文件": "Giấy tờ học viên gửi tôi",
    "學習總結已儲存": "Đã lưu tổng kết học tập",
    "已儲存團班資訊": "Đã lưu thông tin lớp nhóm",
    "已儲存文言文課": "Đã lưu bài Hán văn cổ",
    "已取消這個階段": "Đã huỷ giai đoạn này",
    "已改回左側選單": "Đã chuyển lại menu bên trái",
    "已改成頂部選單": "Đã chuyển sang menu trên cùng",
    "已標記為已處理": "Đã đánh dấu là đã xử lý",
    "已用新內容取代": "Đã thay bằng nội dung mới",
    "已轉成正式案件": "Đã chuyển thành hồ sơ chính thức",
    "待批改／作答中": "Chờ chấm / Đang làm",
    "我給學生的文件": "Giấy tờ tôi gửi học viên",
    "找不到檔案內容": "Không tìm thấy nội dung tệp",
    "找不到這份作答": "Không tìm thấy bài làm này",
    "找不到這位客戶": "Không tìm thấy khách hàng này",
    "是否曾到過臺灣": "Đã từng đến Đài Loan chưa",
    "是否申請獎學金": "Có xin học bổng không",
    "會再算回欠款。": "Sẽ được tính lại vào khoản nợ.",
    "有進步，加油！": "Có tiến bộ, cố lên!",
    "每行「左=右」": "Mỗi dòng ghi 「trái=phải」",
    "沒有可寫「無」": "Không có thì ghi 「không」",
    "清掉這份草稿？": "Xoá bản nháp này?",
    "生詞越南文翻譯": "Bản dịch tiếng Việt của từ vựng",
    "發佈給整個團班": "Giao cho cả lớp nhóm",
    "看「上課內容」": "Xem 「Nội dung buổi học」",
    "知道了，收起來": "Đã hiểu, thu lại",
    "管理員看不到的": "Quản trị viên không xem được",
    "聽發音、練生詞": "Nghe phát âm, luyện từ vựng",
    "要哪一種用法？": "Cần cách dùng nào?",
    "請假（不扣堂）": "Nghỉ có phép (không trừ buổi)",
    "請先勾要發給誰": "Vui lòng chọn giao cho ai trước",
    "讀取與分析中…": "Đang đọc và phân tích…",
    "超過 50MB": "Vượt quá 50MB",
    "這一份要出什麼": "Bản này ra những gì",
    "這一班沒有學生": "Lớp này chưa có học viên",
    "這一課沒有題目": "Bài này chưa có câu hỏi",
    "這個月上了幾堂": "Tháng này đã học mấy buổi",
    "這個月收到的款": "Số tiền thu được tháng này",
    "這筆已經收到了": "Khoản này đã thu rồi",
    "進度已更新 ✓": "Đã cập nhật tiến độ ✓",
    "選填，預設今天": "Không bắt buộc, mặc định là hôm nay",
    "還沒有代辦客戶": "Chưa có khách dịch vụ du học",
    "還沒有繳費紀錄": "Chưa có lịch sử nộp phí",
    "還沒有面試客戶": "Chưa có khách phỏng vấn",
    "需要改進的地方": "Chỗ cần cải thiện",
    "＋ 新增語法點": "＋ Thêm điểm ngữ pháp",
    "＋小節 A／B": "＋ Tiểu mục A / B",
    "💡 這個語法的": "💡 Của điểm ngữ pháp này",
    "💬 上課回饋單": "💬 Phiếu nhận xét buổi học",
    "📄 學生檔案卡": "📄 Thẻ hồ sơ học viên",
    "📈 財務・營運": "📈 Tài chính · Vận hành",
    "📋 學生資料表": "📋 Phiếu thông tin học viên",
    "📝 詢問／候補": "📝 Khách hỏi / Chờ xếp lớp",
    "🔁 這堂是補課": "🔁 Buổi này là học bù",
    "🖼 加課本圖表": "🖼 Thêm hình / bảng trong sách",
    "🧾 產生月結單": "🧾 Tạo bảng kê hàng tháng",
    "🪪 使用說明卡": "🪪 Thẻ hướng dẫn sử dụng",
    "# 語法1 標題": "# Tiêu đề Ngữ pháp 1",
    "- ＿＿天氣不好": "- ＿＿ thời tiết không tốt",
    "GPA 或百分制": "GPA hoặc thang 100",
    "① 開放上傳格子": "① Mở ô để nộp bài",
    "⚠️ 缺聽力音檔": "⚠️ Thiếu tệp âm thanh bài nghe",
    "✅ 已儲存發音課": "✅ Đã lưu bài phát âm",
    "➕ 加入這些對象": "➕ Thêm những người này",
    "➖ 從這些課移除": "➖ Gỡ khỏi những bài này",
    "⬆ 上傳並切逐句": "⬆ Tải lên và cắt theo từng câu",
    "⭐ 學生評價審核": "⭐ Duyệt đánh giá của học viên",
    "下個月可以這樣練": "Tháng sau có thể luyện thế này",
    "下課記得按結束。": "Hết giờ nhớ bấm kết thúc.",
    "不用作答、不計分": "Không cần làm, không tính điểm",
    "位學生，一位一頁": "học viên, mỗi người một trang",
    "位學生，每位一頁": "học viên, mỗi người một trang",
    "例句（時代華語）": "Câu ví dụ (Thời Đại Hoa Ngữ)",
    "例：一對一中文課": "Ví dụ: Lớp tiếng Trung 1 kèm 1",
    "例：他是美國人。": "Ví dụ: Anh ấy là người Mỹ.",
    "例：小時、堂、件": "Ví dụ: giờ, buổi, món",
    "做語法練習、送出": "Làm bài luyện ngữ pháp rồi nộp",
    "勾起來的才會匯出": "Chỉ những mục được đánh dấu mới xuất ra",
    "另一種幣別的價格": "Giá theo loại tiền còn lại",
    "含國碼 +84…": "Kèm mã quốc gia +84…",
    "填空處打 ＿＿＿": "Chỗ trống gõ ＿＿＿",
    "學校名稱（英文）": "Tên trường (tiếng Anh)",
    "學生上課時會用到": "Học viên sẽ dùng đến khi học",
    "寄送重設密碼信給": "Gửi thư đặt lại mật khẩu cho",
    "密碼至少 6 碼": "Mật khẩu ít nhất 6 ký tự",
    "已儲存這一次 ✓": "Đã lưu lần này ✓",
    "已取消這一堂預排": "Đã huỷ buổi học dự kiến này",
    "已更新這一堂 ✓": "Đã cập nhật buổi này ✓",
    "很好，繼續保持！": "Rất tốt, cứ giữ như vậy nhé!",
    "找不到這個名字。": "Không tìm thấy tên này.",
    "提供面試問題清單": "Cung cấp danh sách câu hỏi phỏng vấn",
    "文言文一份出一課": "Hán văn cổ mỗi bản ra một bài",
    "有錯字，請訂正。": "Có lỗi chính tả, hãy sửa lại nhé.",
    "清除（用預設圖）": "Xoá (dùng ảnh mặc định)",
    "自己試跑平台時用": "Dùng khi tự chạy thử nền tảng",
    "至少要有一句原文": "Phải có ít nhất một câu nguyên văn",
    "要出哪一邊的題目": "Ra câu hỏi của bên nào",
    "記得多練習生詞。": "Nhớ luyện từ vựng nhiều hơn nhé.",
    "請先勾要出哪幾課": "Vui lòng chọn ra những bài nào trước",
    "請至少勾一種文件": "Vui lòng chọn ít nhất một loại giấy tờ",
    "越南地址（英文）": "Địa chỉ Việt Nam (tiếng Anh)",
    "越南盾打千位：填": "VND nhập theo đơn vị nghìn: điền",
    "這裡還沒有檔案。": "Ở đây chưa có tệp nào.",
    "選填，打數字即可": "Không bắt buộc, chỉ cần gõ số",
    "還沒有上傳投影片": "Chưa tải slide lên",
    "那天做了什麼 *": "Hôm đó đã làm gì *",
    "開放中 · 關閉": "Đang mở · Đã đóng",
    "開放學生填寫評價": "Cho học viên viết đánh giá",
    "題的說明都改好了": "câu đã sửa xong phần hướng dẫn",
    "＋ 新增代辦客戶": "＋ Thêm khách dịch vụ du học",
    "＋ 新增面試客戶": "＋ Thêm khách phỏng vấn",
    "🎬 上課影片連結": "🎬 Link video buổi học",
    "🎯 各題型正確率": "🎯 Tỉ lệ đúng theo từng dạng câu",
    "💰 這次已經收款": "💰 Lần này đã thu tiền",
    "📈 這個月的進步": "📈 Tiến bộ trong tháng này",
    "📎 補充資料 ·": "📎 Tài liệu bổ sung ·",
    "📖 今天上了什麼": "📖 Hôm nay đã học gì",
    "📘 上課語法練習": "📘 Bài luyện ngữ pháp trên lớp"
  }
};
