/* QNA CHINESE — 教師後台介面越南文字典
   VI_V962／963 第一批＋第二批：側邊選單、分頁、按鈕、表格欄位、狀態、常見提示。
   M = 整句完全相同才換；R = 帶數字的句型，用規則換。
   還沒收錄的句子會維持中文，不會變成空白或亂碼。
   有翻得不好的地方直接跟我說哪一句，我改這個檔案就好，不用動 teacher.html。 */
window.QNA_VI = {
  wave: 3,
  R: [
    ["^共 ?(\\d+(?:\\.\\d+)?) ?堂$", "Tổng $1 buổi"],
    ["^共 ?(\\d+) ?筆$", "Tổng $1 mục"],
    ["^共 ?(\\d+) ?題$", "Tổng $1 câu"],
    ["^共 ?(\\d+) ?課$", "Tổng $1 bài"],
    ["^(\\d+(?:\\.\\d+)?) ?小時$", "$1 giờ"],
    ["^(\\d+(?:\\.\\d+)?) ?堂$", "$1 buổi"],
    ["^(\\d+) ?題$", "$1 câu"],
    ["^(\\d+) ?課$", "$1 bài"],
    ["^(\\d+) ?筆$", "$1 mục"],
    ["^(\\d+) ?份$", "$1 bài"],
    ["^(\\d+) ?位$", "$1 người"],
    ["^(\\d+) ?人$", "$1 người"],
    ["^(\\d+) ?次$", "$1 lần"],
    ["^(\\d+) ?天$", "$1 ngày"],
    ["^(\\d+) ?個生詞$", "$1 từ vựng"],
    ["^(\\d+) ?位學生$", "$1 học viên"],
    ["^還剩 ?(\\d+) ?堂$", "Còn $1 buổi"],
    ["^逾期 ?(\\d+) ?天$", "Quá hạn $1 ngày"],
    ["^還有 ?(\\d+) ?天$", "Còn $1 ngày"],
    ["^已交 ?(\\d+)/(\\d+)$", "Đã nộp $1/$2"],
    ["^儲存失敗：([\\s\\S]*)$", "Lưu thất bại: $1"],
    ["^刪除失敗：([\\s\\S]*)$", "Xoá thất bại: $1"],
    ["^上傳失敗：([\\s\\S]*)$", "Tải lên thất bại: $1"],
    ["^下載失敗：([\\s\\S]*)$", "Tải xuống thất bại: $1"],
    ["^匯出失敗：([\\s\\S]*)$", "Xuất thất bại: $1"],
    ["^載入失敗：([\\s\\S]*)$", "Tải dữ liệu thất bại: $1"],
    ["^讀取失敗：([\\s\\S]*)$", "Đọc dữ liệu thất bại: $1"],
    ["^失敗：([\\s\\S]*)$", "Thất bại: $1"],
    ["^寄送失敗：([\\s\\S]*)$", "Gửi thất bại: $1"],
    ["^尚欠 ?(.+)$", "Còn nợ $1"],
    ["^欠 ?(.+)$", "Nợ $1"],
    ["^預繳 ?(.+)$", "Trả trước $1"],
    ["^應收 ?(.+)$", "Phải thu $1"],
    ["^已收 ?(.+)$", "Đã thu $1"],
    ["^本月收入（(.+)）$", "Thu nhập tháng này ($1)"],
    ["^最新 ?(\\d+) ?筆$", "$1 mục mới nhất"],
    ["^最近 ?(\\d+) ?筆，共 ?(\\d+) ?筆$", "$1 mục gần nhất, tổng $2 mục"],
    ["^還剩 ?(\\d+) ?堂$", "Còn $1 buổi"],
    ["^(\\d+) ?/ ?(\\d+)$", "$1 / $2"],
    /* VI_V966 首頁那幾句是拼出來的（中間夾 <b> 數字），所以要一段一段對 */
    ["^早安，(.+)，今天先做這些。$", "Chào buổi sáng, $1, hôm nay làm mấy việc này nhé."],
    ["^午安，(.+)，今天先做這些。$", "Chào buổi trưa, $1, hôm nay làm mấy việc này nhé."],
    ["^晚安，(.+)，今天先做這些。$", "Chào buổi tối, $1, hôm nay làm mấy việc này nhé."],
    ["^資料更新於 (.+)（週日）$", "Dữ liệu cập nhật lúc $1 (Chủ nhật)"],
    ["^資料更新於 (.+)（週一）$", "Dữ liệu cập nhật lúc $1 (Thứ 2)"],
    ["^資料更新於 (.+)（週二）$", "Dữ liệu cập nhật lúc $1 (Thứ 3)"],
    ["^資料更新於 (.+)（週三）$", "Dữ liệu cập nhật lúc $1 (Thứ 4)"],
    ["^資料更新於 (.+)（週四）$", "Dữ liệu cập nhật lúc $1 (Thứ 5)"],
    ["^資料更新於 (.+)（週五）$", "Dữ liệu cập nhật lúc $1 (Thứ 6)"],
    ["^資料更新於 (.+)（週六）$", "Dữ liệu cập nhật lúc $1 (Thứ 7)"],
    ["^最久的一份已經等了 (\\d+) 天$", "Bài chờ lâu nhất đã $1 ngày"],
    ["^還沒收 (.+)$", "Chưa thu $1"],
    ["^已處理 (.+)$", "Đã xử lý $1"],
    ["^上課 (.+)$", "Đã học $1"]
  ],
  M: {
    /* ── 側邊選單 ── */
    "今日總覽": "Tổng quan hôm nay",
    "學生": "Học viên",
    "課表": "Lịch học",
    "教材與課程": "Giáo trình & bài học",
    "批改・成績": "Chấm bài・Điểm",
    "課堂活動": "Hoạt động lớp",
    "留學業務": "Dịch vụ du học",
    "收費・財務": "Thu phí・Tài chính",
    "回覆範本": "Mẫu trả lời",
    "使用說明": "Hướng dẫn sử dụng",
    "設定": "Cài đặt",
    "⚙️ 設定": "⚙️ Cài đặt",
    "登出": "Đăng xuất",
    "登入": "Đăng nhập",
    "教　學": "GIẢNG DẠY",
    "業　務": "NGHIỆP VỤ",
    "其　他": "KHÁC",
    "主管理員後台": "Trang quản trị chính",
    "教師管理": "Quản lý giáo viên",
    "華語線上作業簿": "Sổ bài tập tiếng Trung trực tuyến",

    /* ── 通用按鈕 ── */
    "儲存": "Lưu",
    "💾 儲存": "💾 Lưu",
    "儲存中…": "Đang lưu…",
    "已儲存": "Đã lưu",
    "儲存失敗": "Lưu thất bại",
    "儲存失敗，請重試": "Lưu thất bại, vui lòng thử lại",
    "取消": "Huỷ",
    "關閉": "Đóng",
    "刪除": "Xoá",
    "已刪除": "Đã xoá",
    "刪除失敗": "Xoá thất bại",
    "移除": "Bỏ",
    "已移除": "Đã bỏ",
    "新增": "Thêm mới",
    "編輯": "Sửa",
    "✏️ 編輯": "✏️ Sửa",
    "✏️ 修改": "✏️ Chỉnh sửa",
    "完成": "Hoàn thành",
    "已完成": "Đã hoàn thành",
    "標記完成": "Đánh dấu hoàn thành",
    "失敗": "Thất bại",
    "建立": "Tạo",
    "＋ 建立": "＋ Tạo",
    "建立中…": "Đang tạo…",
    "已建立": "Đã tạo",
    "建立失敗": "Tạo thất bại",
    "更新失敗": "Cập nhật thất bại",
    "已更新": "Đã cập nhật",
    "預覽": "Xem trước",
    "👁 預覽": "👁 Xem trước",
    "處理中…": "Đang xử lý…",
    "載入中…": "Đang tải…",
    "上傳中…": "Đang tải lên…",
    "上傳中…（檔案大時請稍候）": "Đang tải lên… (tệp lớn vui lòng đợi)",
    "↻ 重新整理": "↻ Tải lại",
    "⬇ 下載": "⬇ Tải xuống",
    "⬆ 上傳圖片": "⬆ Tải ảnh lên",
    "⬆ 上傳音檔": "⬆ Tải tệp âm thanh lên",
    "⬆ 上傳 PDF": "⬆ Tải PDF lên",
    "⬇ 匯出 Excel": "⬇ Xuất Excel",
    "⬇ 下載完整備份": "⬇ Tải bản sao lưu đầy đủ",
    "全選 / 取消": "Chọn tất cả / Bỏ chọn",
    "✔ 全選在學中": "✔ Chọn tất cả đang học",
    "✕ 清除": "✕ Xoá trắng",
    "▾ 全部展開": "▾ Mở tất cả",
    "已選": "Đã chọn",
    "還沒選人": "Chưa chọn ai",
    "選填": "Không bắt buộc",
    "可以不填": "Có thể để trống",
    "全部": "Tất cả",
    "其他": "Khác",
    "列表": "Danh sách",
    "🖨 列印 / 存成 PDF": "🖨 In / Lưu PDF",
    "🖨 列印／PDF": "🖨 In / PDF",
    "列印時這排按鈕不會印出來": "Hàng nút này sẽ không được in ra",
    "語言": "Ngôn ngữ",
    "字體": "Phông chữ",
    "中文 ＋ Tiếng Việt": "中文 ＋ Tiếng Việt",
    "⋯ 更多": "⋯ Thêm",
    "沒有權限": "Không có quyền",
    "這個功能只有主管理員可以用": "Chức năng này chỉ quản trị viên chính mới dùng được",
    "只有主管理員可以用": "Chỉ quản trị viên chính mới dùng được",
    "主管理員": "Quản trị viên chính",
    "老師": "Giáo viên",
    "存不起來": "Không lưu được",
    "未連 Storage": "Chưa kết nối Storage",
    "複製失敗，請手動選取": "Sao chép thất bại, vui lòng bôi đen thủ công",
    "匯出元件還在載入，請過幾秒再按一次": "Công cụ xuất đang tải, vui lòng bấm lại sau vài giây",

    /* ── 學生・班級 ── */
    "姓名": "Họ tên",
    "姓名 *": "Họ tên *",
    "請填姓名": "Vui lòng nhập họ tên",
    "找不到這位學生": "Không tìm thấy học viên này",
    "還沒有學生": "Chưa có học viên",
    "全部學生": "Tất cả học viên",
    "位學生": "học viên",
    "團班": "Lớp nhóm",
    "一對一": "Học 1 kèm 1",
    "🧑‍🏫 一對一": "🧑‍🏫 Học 1 kèm 1",
    "👥 團班（尚未分班）": "👥 Lớp nhóm (chưa xếp lớp)",
    "班級": "Lớp",
    "課程型態": "Hình thức lớp",
    "國籍": "Quốc tịch",
    "電話": "Điện thoại",
    "電話／Zalo／LINE": "Điện thoại / Zalo / LINE",
    "聯絡方式": "Thông tin liên hệ",
    "基本資料": "Thông tin cơ bản",
    "📋 基本資料": "📋 Thông tin cơ bản",
    "備註": "Ghi chú",
    "換頭像": "Đổi ảnh đại diện",
    "← 回學生列表": "← Về danh sách học viên",
    "去學生頁": "Đến trang học viên",
    "合併帳戶": "Tài khoản gộp",
    "主管理員還沒有把學生分配給你。": "Quản trị viên chính chưa phân học viên cho bạn.",

    /* ── 就學狀態 ── */
    "在學中": "Đang học",
    "試學": "Học thử",
    "休學": "Tạm nghỉ",
    "已結案": "Đã kết thúc",
    "預約": "Đặt lịch",
    "預約中": "Đang hẹn",
    "預約・詢問中": "Đang hỏi・đặt lịch",

    /* ── 上課 ── */
    "上課": "Buổi học",
    "上課記錄": "Lịch sử buổi học",
    "🗓 上課記錄": "🗓 Lịch sử buổi học",
    "還沒有上課記錄": "Chưa có buổi học nào",
    "上課時段": "Giờ học",
    "上課日期": "Ngày học",
    "上課內容": "Nội dung buổi học",
    "課後小結": "Tóm tắt sau buổi học",
    "時段": "Khung giờ",
    "日期": "Ngày",
    "日期 *": "Ngày *",
    "請選日期": "Vui lòng chọn ngày",
    "月份": "Tháng",
    "今天": "Hôm nay",
    "明天": "Ngày mai",
    "填今天": "Điền hôm nay",
    "本月": "Tháng này",
    "最近": "Gần đây",
    "最新": "Mới nhất",
    "期間": "Kỳ",
    "未來": "Sắp tới",
    "開始": "Bắt đầu",
    "截止": "Hạn chót",
    "截止日期": "Hạn nộp",
    "期限": "Thời hạn",
    "沒設期限": "Chưa đặt thời hạn",
    "今天到期": "Hết hạn hôm nay",
    "逾期": "Quá hạn",
    "已過": "Đã qua",
    "快開始了": "Sắp bắt đầu",
    "出席": "Có mặt",
    "出席率": "Tỷ lệ đi học",
    "請假": "Nghỉ phép",
    "🏖 請假": "🏖 Nghỉ phép",
    "缺席": "Vắng mặt",
    "補課": "Học bù",
    "免費": "Miễn phí",
    "🎁 免費": "🎁 Miễn phí",
    "時數": "Số giờ",
    "小時": "giờ",
    "堂課": "buổi học",
    "狀態": "Trạng thái",
    "✍️ 去點名": "✍️ Điểm danh",
    "✅ 已點名": "✅ Đã điểm danh",
    "📌 預排": "📌 Đã xếp lịch",
    "🔁 固定時段": "🔁 Giờ cố định",
    "🔁 照上一週排下一週": "🔁 Xếp tuần sau theo tuần trước",
    "‹ 上個月": "‹ Tháng trước",
    "下個月 ›": "Tháng sau ›",
    "＋ 新增時段": "＋ Thêm khung giờ",
    "＋ 新增練習時間": "＋ Thêm buổi luyện tập",
    "排課中…": "Đang xếp lịch…",
    "刪掉這一堂": "Xoá buổi này",
    "線上教室：": "Lớp học trực tuyến:",
    "📝 記一堂課": "📝 Ghi một buổi học",
    "📌 排一堂課": "📌 Xếp một buổi học",
    "💬 寫回饋單": "💬 Viết phiếu nhận xét",

    /* ── 教材・課程 ── */
    "教材": "Giáo trình",
    "課程": "Khoá học",
    "課文": "Bài khoá",
    "課名": "Tên bài",
    "課名 *": "Tên bài *",
    "課序": "Thứ tự bài",
    "第幾課": "Bài số mấy",
    "標題": "Tiêu đề",
    "請填標題": "Vui lòng nhập tiêu đề",
    "內容": "Nội dung",
    "段落": "Đoạn",
    "小節": "Mục nhỏ",
    "小節（選填）": "Mục nhỏ (không bắt buộc)",
    "生詞": "Từ vựng",
    "生詞語法": "Từ vựng & ngữ pháp",
    "語法": "Ngữ pháp",
    "語法練習": "Luyện ngữ pháp",
    "屬於哪個語法點": "Thuộc điểm ngữ pháp nào",
    "例句": "Câu ví dụ",
    "對話": "Hội thoại",
    "對話一": "Hội thoại 1",
    "短文": "Đoạn văn",
    "原文": "Nguyên văn",
    "注釋": "Chú thích",
    "聽力": "Nghe hiểu",
    "發音": "Phát âm",
    "發音教材": "Giáo trình phát âm",
    "儲存發音課": "Lưu bài phát âm",
    "已上傳發音": "Đã tải lên phát âm",
    "▶ 試聽": "▶ Nghe thử",
    "此瀏覽器不支援錄音，請改用上傳": "Trình duyệt này không hỗ trợ ghi âm, vui lòng tải tệp lên",
    "文言文": "Văn ngôn",
    "📜 文言文": "📜 Văn ngôn",
    "講義": "Tài liệu phát",
    "📄 講義（PDF）": "📄 Tài liệu phát (PDF)",
    "作業": "Bài tập",
    "作業簿": "Sách bài tập",
    "📒 作業簿": "📒 Sách bài tập",
    "📒 挑作業": "📒 Chọn bài tập",
    "作業完成": "Bài tập đã xong",
    "作業成績": "Điểm bài tập",
    "完成作業": "Bài tập đã làm",
    "還沒做": "Chưa làm",
    "練習": "Luyện tập",
    "練習題": "Bài luyện tập",
    "課文練習": "Luyện bài khoá",
    "題庫練習": "Luyện ngân hàng đề",
    "造句": "Đặt câu",
    "課後問答": "Hỏi đáp sau buổi học",
    "問題與討論": "Câu hỏi & thảo luận",
    "隨堂小考": "Kiểm tra nhanh",
    "📝 隨堂小考": "📝 Kiểm tra nhanh",
    "小考": "Bài kiểm tra ngắn",
    "題目": "Câu hỏi",
    "題型": "Dạng câu hỏi",
    "小題": "Câu nhỏ",
    "選項": "Lựa chọn",
    "單選": "Chọn một",
    "填空": "Điền vào chỗ trống",
    "配對": "Nối",
    "重組": "Sắp xếp lại",
    "問答": "Hỏi đáp",
    "示範": "Ví dụ mẫu",
    "正確答案": "Đáp án đúng",
    "參考答案": "Đáp án tham khảo",
    "✅ 補參考答案": "✅ Bổ sung đáp án tham khảo",
    "找不到題庫": "Không tìm thấy ngân hàng đề",
    "這本還沒有課。": "Sách này chưa có bài nào.",
    "還沒有課文": "Chưa có bài khoá",
    "看拼音寫字": "Nhìn pinyin viết chữ",
    "看意思寫字": "Nhìn nghĩa viết chữ",
    "看字選意思": "Nhìn chữ chọn nghĩa",
    "看例句填生詞": "Nhìn câu ví dụ điền từ",
    "建立並編輯": "Tạo rồi sửa",
    "建立全部": "Tạo tất cả",
    "課標成完成": "Đánh dấu bài đã xong",
    "📢 發佈內容": "📢 Đăng nội dung",
    "👥 發佈": "👥 Đăng",
    "已發佈": "Đã đăng",
    "學生會看到": "Học viên sẽ nhìn thấy",
    "學生現在看不到": "Hiện học viên chưa nhìn thấy",
    "所有學生登入首頁都會看到": "Mọi học viên đăng nhập vào trang chủ đều nhìn thấy",
    "📌 套用到全班學生": "📌 Áp dụng cho cả lớp",
    "儲存成員": "Lưu thành viên",
    "🖥 上課投影片": "🖥 Slide bài giảng",

    /* ── 批改 ── */
    "批改": "Chấm bài",
    "去批改": "Đi chấm bài",
    "待批改": "Chờ chấm",
    "已交": "Đã nộp",
    "作答中": "Đang làm",
    "未開始": "Chưa bắt đầu",
    "分數": "Điểm",
    "平均": "Trung bình",
    "答對率": "Tỷ lệ đúng",
    "百分比": "Phần trăm",
    "✓ 對": "✓ Đúng",
    "✗ 錯": "✗ Sai",
    "整體評語": "Nhận xét chung",
    "整體鼓勵或建議…": "Lời động viên hoặc góp ý chung…",
    "給這一題的建議（學生會看到）": "Góp ý cho câu này (học viên sẽ thấy)",
    "儲存建議": "Lưu góp ý",
    "💾 儲存建議": "💾 Lưu góp ý",
    "已儲存建議": "Đã lưu góp ý",
    "已批改，學生可看到建議": "Đã chấm, học viên xem được góp ý",
    "已改回進行中": "Đã chuyển lại thành đang tiến hành",
    "目前沒有待批改的項目 🎉": "Hiện không có mục nào chờ chấm 🎉",
    "老師的話": "Lời của giáo viên",
    "這個月的進步": "Tiến bộ trong tháng",
    "謝謝你這段時間的努力 ♡": "Cảm ơn em đã cố gắng trong thời gian qua ♡",
    "開口說": "Luyện nói",
    "專心度": "Mức độ tập trung",
    "上課回饋單": "Phiếu nhận xét buổi học",
    "月總結": "Tổng kết tháng",
    "📄 學習報告": "📄 Báo cáo học tập",

    /* ── 財務 ── */
    "繳費": "Nộp phí",
    "💰 繳費": "💰 Nộp phí",
    "💰 記繳費": "💰 Ghi nộp phí",
    "💰 記一筆收款": "💰 Ghi một khoản thu",
    "繳費記錄": "Lịch sử nộp phí",
    "學費": "Học phí",
    "未設學費": "Chưa đặt học phí",
    "計費": "Tính phí",
    "單價": "Đơn giá",
    "沒填單價": "Chưa điền đơn giá",
    "沒設單價": "Chưa đặt đơn giá",
    "金額": "Số tiền",
    "金額 *": "Số tiền *",
    "請填金額": "Vui lòng nhập số tiền",
    "合計": "Tổng cộng",
    "數量": "Số lượng",
    "幣別": "Loại tiền",
    "總費用幣別": "Loại tiền của tổng phí",
    "臺幣 NT$": "Đài tệ NT$",
    "美元 US$": "Đô la Mỹ US$",
    "越南盾 VND": "Việt Nam Đồng VND",
    "越南盾 VND（打千位）": "Việt Nam Đồng VND (nhập theo nghìn)",
    "越南盾打千位": "VND nhập theo nghìn",
    "VND 千": "VND nghìn",
    "折合帳單幣別": "Quy đổi sang loại tiền của hoá đơn",
    "未換算": "Chưa quy đổi",
    "付款日": "Ngày thanh toán",
    "收款日期 *": "Ngày thu *",
    "收款方式": "Hình thức thu",
    "💳 收款帳號": "💳 Tài khoản nhận tiền",
    "帳號": "Tài khoản",
    "應收": "Phải thu",
    "已收": "Đã thu",
    "已繳": "Đã nộp",
    "· 已繳": "· Đã nộp",
    "尚欠": "Còn nợ",
    "預繳": "Trả trước",
    "結餘": "Số dư",
    "已結清": "Đã thanh toán xong",
    "✅ 已結清": "✅ Đã thanh toán xong",
    "累計": "Luỹ kế",
    "累計應收": "Tổng phải thu",
    "累計實收": "Tổng đã thu",
    "累計收入": "Thu nhập luỹ kế",
    "還沒收到": "Chưa nhận được",
    "🔴 還沒收": "🔴 Chưa thu",
    "🧾 目前應收：": "🧾 Phải thu hiện tại:",
    "已處理": "Đã xử lý",
    "退費單": "Phiếu hoàn phí",
    "價目表": "Bảng giá",
    "價目表還是空的": "Bảng giá vẫn trống",
    "名稱": "Tên",
    "項目": "Hạng mục",
    "類別": "Phân loại",
    "💰 開一張報價單": "💰 Lập một phiếu báo giá",
    "📊 匯出對帳資料": "📊 Xuất dữ liệu đối chiếu",
    "收入會併進「營運 → 🧮 總收入」。": "Khoản thu sẽ được gộp vào “Vận hành → 🧮 Tổng thu nhập”.",

    /* ── 留學業務 ── */
    "留學代辦": "Dịch vụ du học",
    "代辦": "Dịch vụ",
    "代辦申請": "Hồ sơ dịch vụ",
    "代書": "Viết hồ sơ thuê",
    "文件代寫": "Viết hồ sơ",
    "申請學校": "Trường ứng tuyển",
    "學校": "Trường",
    "客戶資料": "Thông tin khách hàng",
    "看客戶": "Xem khách hàng",
    "刪除這位客戶": "Xoá khách hàng này",
    "文件名稱": "Tên hồ sơ",
    "入學申請資料表": "Phiếu thông tin nhập học",
    "自傳": "Bài tự giới thiệu",
    "推薦信": "Thư giới thiệu",
    "修改讀書計畫": "Sửa kế hoạch học tập",
    "承辦人": "Người phụ trách",
    "階段": "Giai đoạn",
    "進度": "Tiến độ",
    "＋ 新增一筆進度": "＋ Thêm một mốc tiến độ",
    "交件": "Nộp hồ sơ",
    "還缺": "Còn thiếu",
    "這一本還缺": "Phần này còn thiếu",
    "📄 正式案件": "📄 Hồ sơ chính thức",
    "✕ 沒談成": "✕ Không chốt được",
    "面試": "Phỏng vấn",
    "面試日": "Ngày phỏng vấn",
    "面試練習": "Luyện phỏng vấn",
    "🎤 面試練習": "🎤 Luyện phỏng vấn",
    "🎯 正式面試": "🎯 Phỏng vấn chính thức",
    "面試目標": "Mục tiêu phỏng vấn",
    "✅ 通過": "✅ Đạt",
    "❌ 沒通過": "❌ Không đạt",
    "📎 上傳／查看檔案": "📎 Tải lên / xem tệp",
    "📤 上傳區": "📤 Khu tải lên",
    "檔案": "Tệp",
    "個檔案": "tệp",
    "📋 提醒訊息": "📋 Tin nhắn nhắc nhở",
    "📄 報告與證書": "📄 Báo cáo & chứng chỉ",
    "✉️ 聯絡與提醒": "✉️ Liên hệ & nhắc nhở",
    "📁 檔案與紀錄": "📁 Tệp & hồ sơ",
    "📌 其他": "📌 Khác",
    "＋ 記下來": "＋ Ghi lại",
    "待處理": "Chờ xử lý",
    "目前": "Hiện tại",
    "中文": "Tiếng Trung",
    "說明": "Hướng dẫn",
    "類型": "Loại",
    "開立時間": "Thời gian lập",
    "華語教學 · 留學代辦": "Dạy tiếng Trung · Dịch vụ du học",
    "中文課 ·": "Lớp tiếng Trung ·",
    "手寫": "Viết tay",
    "還有": "Còn",
    "都可以": "Đều được",
    "換上面的分類看看。": "Thử đổi phân loại ở trên xem.",
    "還沒到（今天是": "Chưa đến (hôm nay là",
    "例：Nguyễn Văn A": "Ví dụ: Nguyễn Văn A",
    "例：500": "Ví dụ: 500",
    "例：A、B": "Ví dụ: A, B",
    "選填。填了才會算「還差多少」": "Không bắt buộc. Điền vào mới tính được “còn thiếu bao nhiêu”",
    "選填，會在「待辦」提醒": "Không bắt buộc, sẽ nhắc ở mục “Việc cần làm”",
    "📧 有人報名時通知我": "📧 Báo cho tôi khi có người đăng ký",
    "第 1 步": "Bước 1",
    "第 2 步": "Bước 2",
    "學生名單": "Danh sách học viên",
    "👥 學生名單": "👥 Danh sách học viên",
    "團班每位學生各自繳自己的。": "Mỗi học viên trong lớp nhóm tự đóng phần của mình.",
    "成員": "Thành viên",
    "成員／時段": "Thành viên / Giờ học",
    "班級資訊": "Thông tin lớp",
    "課程模組": "Mô-đun bài học",
    "繳交狀況": "Tình hình nộp bài",
    "🗓 上課點名": "🗓 Điểm danh buổi học",
    "🖨 班級總覽": "🖨 Tổng quan lớp",
    "📤 匯出這班的學生": "📤 Xuất học viên lớp này",
    "已上課": "Đã học",
    "下次上課": "Buổi học kế tiếp",
    "還沒排": "Chưa xếp lịch",
    "還沒點過名": "Chưa điểm danh lần nào",
    "已上": "Đã học",
    "目前結餘": "Số dư hiện tại",
    "還沒開始上課": "Chưa bắt đầu học",
    "還沒設定學費": "Chưa đặt học phí",
    "總覽": "Tổng quan",
    "📋 週報": "📋 Báo cáo tuần",
    "💰 收款": "💰 Thu tiền",
    "📤 匯出": "📤 Xuất dữ liệu",
    "🎥 教室": "🎥 Phòng học",
    "📁 資料夾": "📁 Thư mục",
    "⋯ 更多工具": "⋯ Công cụ khác",
    "🔎 完整檔案": "🔎 Hồ sơ đầy đủ",
    "📄 檔案卡": "📄 Thẻ hồ sơ",
    "🧾 對帳單": "🧾 Bảng đối chiếu",
    "＋ 記一堂課": "＋ Ghi một buổi học",
    "＋ 記一筆繳費": "＋ Ghi một khoản nộp phí",
    "還沒有繳費記錄。": "Chưa có lịch sử nộp phí.",
    "還沒有繳費記錄": "Chưa có lịch sử nộp phí",
    "還沒有成員": "Chưa có thành viên",
    "收款金額": "Số tiền đã thu",
    "這個分頁只有主管理員看得到。": "Trang này chỉ quản trị viên chính mới xem được.",
    "待辦": "Việc cần làm",
    "今天要處理": "Cần xử lý hôm nay",
    "今天的課": "Buổi học hôm nay",
    "備忘": "Ghi nhớ",
    "本月收入": "Thu nhập tháng này",
    "尚未收款": "Chưa thu tiền",
    "堂數快用完": "Sắp hết số buổi",
    "費用明細": "Chi tiết thu chi",
    "華語教學": "Dạy tiếng Trung",
    "營運": "Vận hành",
    "🧮 總收入": "🧮 Tổng thu nhập",

    /* ══ 第二批 VI_V963 ══ */
    /* 今日總覽 */
    "早安": "Chào buổi sáng",
    "午安": "Chào buổi trưa",
    "晚安": "Chào buổi tối",
    "QNA CHINESE · 教師工作台": "QNA CHINESE · Bàn làm việc giáo viên",
    "資料更新於": "Dữ liệu cập nhật lúc",
    "今天有": "Hôm nay có",
    "份作業等你批改": "bài tập đang chờ chấm",
    "最久的一份已經等了": "Bài chờ lâu nhất đã",
    "今天沒有待批改的作業": "Hôm nay không có bài nào chờ chấm",
    "；另外有": "; ngoài ra có",
    "位學生的學費還沒收到": "học viên chưa nộp học phí",
    "✍️ 去批改": "✍️ Đi chấm bài",
    "待辦提醒": "Nhắc việc",
    "我負責的學生": "Học viên tôi phụ trách",
    "目前沒有記著的事。想到什麼就打在上面，做完打勾。": "Hiện chưa ghi việc nào. Nghĩ ra gì thì gõ ở trên, xong thì tích vào.",
    "目前沒有待辦": "Hiện không có việc cần làm",
    "目前沒有需要提醒的事項 👍": "Hiện không có việc nào cần nhắc 👍",
    "目前沒有即將到期或逾期的付款 👍": "Hiện không có khoản nào sắp đến hạn hoặc quá hạn 👍",
    "目前沒有欠款的學生 👍": "Hiện không có học viên nào còn nợ 👍",
    "目前沒有待批改的作業 👍": "Hiện không có bài tập nào chờ chấm 👍",
    "目前沒有待批改的造句 👍": "Hiện không có câu đặt nào chờ chấm 👍",
    "目前沒有待批改的問題與討論 👍": "Hiện không có câu hỏi & thảo luận nào chờ chấm 👍",
    "目前每一位學生的作業都交齊了 👍": "Hiện tất cả học viên đều đã nộp đủ bài 👍",
    "先到「學生名冊」新增學生。": "Hãy vào “Danh sách học viên” để thêm học viên trước.",
    "💰 欠": "💰 Nợ",
    "🔁 待補": "🔁 Chờ bù",
    "補登": "Ghi bù",
    "🎯 待填結果": "🎯 Chờ điền kết quả",
    "填面試結果": "Điền kết quả phỏng vấn",
    "交件已過": "Đã quá hạn nộp hồ sơ",
    "今天要交件！": "Hôm nay phải nộp hồ sơ!",
    "明天要交件": "Ngày mai phải nộp hồ sơ",
    "繳件已過": "Đã quá hạn nộp",
    "今天要繳件！": "Hôm nay phải nộp!",
    "明天要繳件": "Ngày mai phải nộp",
    "還沒備份過": "Chưa sao lưu lần nào",
    "這週還沒備份": "Tuần này chưa sao lưu",
    "📦 備份": "📦 Sao lưu",
    "改標題、內容或日期": "Sửa tiêu đề, nội dung hoặc ngày",
    "刪掉這一件": "Xoá việc này",
    "要哪天做完（可不填）": "Ngày hoàn thành (có thể bỏ trống)",
    "已逾期": "Đã quá hạn",

    /* 課表 */
    "週一": "Thứ 2", "週二": "Thứ 3", "週三": "Thứ 4", "週四": "Thứ 5",
    "週五": "Thứ 6", "週六": "Thứ 7", "週日": "Chủ nhật",
    "星期": "Thứ",
    "結束": "Kết thúc",
    "加堂": "Thêm buổi",
    "進入教室": "Vào lớp học",
    "進入教室（開新分頁進入 Google Meet）": "Vào lớp (mở tab mới tới Google Meet)",
    "刪除時段": "Xoá khung giờ",
    "還沒有上課時段，請先到上面新增": "Chưa có khung giờ học, vui lòng thêm ở trên",
    "請選擇": "Vui lòng chọn",
    "🗓 排課": "🗓 Xếp lịch",
    "把某一週的課整組往後排": "Dời cả tuần học sang sau",
    "📆 這一週": "📆 Tuần này",
    "🗓 這個月": "🗓 Tháng này",
    "👥 上課記錄": "👥 Lịch sử buổi học",
    "固定週表": "Lịch tuần cố định",
    "預排的課": "Buổi đã xếp trước",
    "各自一次。": "mỗi loại một lần.",
    "會排成每週重複，": "sẽ lặp lại hằng tuần,",
    "📅 加入日曆": "📅 Thêm vào lịch",
    "📅 匯出全部上課日曆": "📅 Xuất toàn bộ lịch học",
    "含已休學": "Gồm cả đã tạm nghỉ",
    "這個月還沒有課": "Tháng này chưa có buổi học nào",
    "各學生計費堂數": "Số buổi tính phí của từng học viên",
    "整個團班刪掉這一堂": "Xoá buổi này cho cả lớp nhóm",
    "台灣時間（GMT+8）": "Giờ Đài Loan (GMT+8)",
    "越南時間 ＝ 台灣 − 1 小時": "Giờ Việt Nam = giờ Đài Loan − 1 tiếng",
    "🕒 時間都以": "🕒 Mọi giờ đều theo",
    "為準；": "làm chuẩn;",
    "這一堂上了哪一課": "Buổi này học bài nào",
    "✅ 記錄這一堂並點名": "✅ Ghi buổi này và điểm danh",
    "✅ 加入預排": "✅ Thêm vào lịch dự kiến",
    "已排": "Đã xếp",
    "已記錄": "Đã ghi",
    "全選": "Chọn tất cả",
    "全不選": "Bỏ chọn tất cả",
    "排課失敗": "Xếp lịch thất bại",
    "這個團班還沒有成員": "Lớp nhóm này chưa có thành viên",
    "那天已經點名過": "Ngày đó đã điểm danh rồi",
    "那天已經排過": "Ngày đó đã xếp lịch rồi",
    "🚀 排下去": "🚀 Xếp lịch",
    "請至少選一位學生": "Vui lòng chọn ít nhất một học viên",
    "🌙 請假（照計）": "🌙 Nghỉ phép (vẫn tính)",
    "🌙 請假": "🌙 Nghỉ phép",
    "🙈 缺席": "🙈 Vắng mặt",
    "不計費": "Không tính phí",
    "⏱ 這堂": "⏱ Buổi này",

    /* 教材・課程 */
    "🎒 試做": "🎒 Làm thử",
    "📤 送出": "📤 Nộp",
    "其他練習": "Bài luyện khác",
    "解答": "Đáp án",
    "學生版": "Bản học viên",
    "要出哪一課": "Ra bài nào",
    "要出哪幾課": "Ra những bài nào",
    "未發佈": "Chưa đăng",
    "標題 *": "Tiêu đề *",
    "圖片已上傳": "Đã tải ảnh lên",
    "圖片好了": "Ảnh đã xong",
    "已上傳": "Đã tải lên",
    "⬆ 上傳": "⬆ Tải lên",
    "⬆ 上傳檔案": "⬆ Tải tệp lên",
    "＋ 加一題": "＋ Thêm một câu",
    "⏹ 停止": "⏹ Dừng",
    "🎙 錄音": "🎙 Ghi âm",
    "● 錄音中…再按一次停止": "● Đang ghi âm… bấm lần nữa để dừng",
    "無法使用麥克風，請允許權限或改用上傳": "Không dùng được micro, hãy cấp quyền hoặc tải tệp lên",
    "無法讀取音檔：": "Không đọc được tệp âm thanh:",
    "課號": "Mã bài",
    "課文段落": "Đoạn bài khoá",
    "內文": "Nội dung",
    "影片": "Video",
    "🎬 影片": "🎬 Video",
    "課室活動": "Hoạt động trong lớp",
    "文化": "Văn hoá",
    "聽力文本": "Lời thoại nghe",
    "答案": "Đáp án",
    "放哪一邊": "Đặt ở bên nào",
    "屬於哪個語法": "Thuộc điểm ngữ pháp nào",
    "音檔": "Tệp âm thanh",
    "圖片": "Hình ảnh",
    "口說": "Nói",
    "單元": "Đơn vị bài",
    "回家作業": "Bài về nhà",
    "課數": "Số bài",
    "題數": "Số câu",
    "發佈進度": "Tiến độ đăng bài",
    "學生進度": "Tiến độ học viên",
    "已有": "Đã có",
    "沒有練習題": "Không có bài luyện tập",
    "題目都齊了": "Câu hỏi đã đủ",
    "還沒有人做完": "Chưa có ai làm xong",
    "要發給：": "Đăng cho:",
    "發佈給誰": "Đăng cho ai",
    "儲存發佈": "Lưu đăng bài",
    "儲存順序": "Lưu thứ tự",
    "已套用": "Đã áp dụng",
    "請輸入課名": "Vui lòng nhập tên bài",
    "這本教材沒有課，換一本試試。": "Giáo trình này chưa có bài, thử đổi sang cuốn khác.",
    "上面選一本教材。": "Chọn một giáo trình ở trên.",
    "還沒選學生。": "Chưa chọn học viên.",
    "已移到垃圾桶（可復原）": "Đã chuyển vào thùng rác (có thể khôi phục)",
    "復原": "Khôi phục",
    "收回中…": "Đang thu hồi…",
    "已收回發佈，學生已看不到": "Đã thu hồi, học viên không còn nhìn thấy",
    "收回這份練習": "Thu hồi bài luyện này",
    "正解：": "Đáp án đúng:",
    "沒有可留空": "Không có chỗ để trống",
    "投影片.pdf": "slide.pdf",
    "放在整課最上面，例如作者畫像或情境圖": "Đặt ở đầu bài, ví dụ chân dung tác giả hoặc ảnh tình huống",
    "上傳作業簿": "Tải sách bài tập lên",
    "上傳練習": "Tải bài luyện lên",
    "小考練習": "Bài kiểm tra ngắn",
    "自訂題目": "Câu hỏi tự soạn",
    "🎙️ 老師錄音聽寫": "🎙️ Giáo viên ghi âm chính tả",
    "聽寫": "Chính tả",
    "＋ 建立隨堂小考": "＋ Tạo bài kiểm tra nhanh",
    "🎮 即時比賽（Kahoot 式）": "🎮 Thi đấu trực tiếp (kiểu Kahoot)",
    "＋ 新增即時比賽題庫（自己出題）": "＋ Thêm ngân hàng đề thi đấu (tự soạn)",
    "· 可以重做": "· Được làm lại",
    "· 只能做一次": "· Chỉ làm được một lần",
    "做完": "Làm xong",
    "做完的": "Đã làm xong",
    "改期限": "Đổi thời hạn",
    "📤 指派出去": "📤 Giao bài",
    "📤 指派出去的題庫練習": "📤 Bài ngân hàng đề đã giao",
    "還沒有指派過。挑一份題庫按「📤 指派」就可以了。": "Chưa giao lần nào. Chọn một ngân hàng đề rồi bấm “📤 Giao bài” là được.",
    "二 寫出拼音": "2. Viết pinyin",
    "三 寫出中國字": "3. Viết chữ Hán",
    "四 句子重組": "4. Sắp xếp lại câu",
    "六 圖片描述": "6. Miêu tả tranh",
    "七 語法練習": "7. Luyện ngữ pháp",
    "A 聲調辨識": "A. Nhận biết thanh điệu",
    "B 選出發音": "B. Chọn cách phát âm",
    "發音課": "Bài phát âm",
    "＋ 開放上傳格子": "＋ Mở ô nộp bài",
    "請先輸入區域名稱": "Vui lòng nhập tên khu vực trước",
    "把檔案拖進來，或點這裡選檔": "Kéo tệp vào đây, hoặc bấm để chọn tệp",
    "📎 檔案 ·": "📎 Tệp ·",
    "✅ 已上傳": "✅ Đã tải lên",
    "挑幾組練習當回家作業": "Chọn vài nhóm bài luyện làm bài về nhà",
    "常用：": "Hay dùng:",

    /* 批改・成績 */
    "成績": "Điểm số",
    "得分": "Điểm đạt",
    "答對": "Trả lời đúng",
    "總題數": "Tổng số câu",
    "顆星": "sao",
    "未評": "Chưa đánh giá",
    "操作": "Thao tác",
    "儲存評語": "Lưu nhận xét",
    "✓ 已寫": "✓ Đã viết",
    "寫這一堂的回饋單": "Viết phiếu nhận xét buổi này",
    "找不到這一堂": "Không tìm thấy buổi học này",
    "這位學生還沒有上課記錄": "Học viên này chưa có buổi học nào",
    "這個月沒有上課記錄": "Tháng này chưa có buổi học nào",
    "上課回饋": "Nhận xét buổi học",
    "華語教學 · 教師回饋單": "Dạy tiếng Trung · Phiếu nhận xét của giáo viên",
    "學習總結": "Tổng kết học tập",
    "需要改進": "Cần cải thiện",
    "下個月練習": "Luyện tập tháng sau",
    "學生資料": "Dữ liệu học viên",
    "學生檔案": "Hồ sơ học viên",
    "✨ 幫我擬草稿": "✨ Soạn bản nháp giúp tôi",
    "✨ AI 幫我翻越南文（草稿）": "✨ AI dịch sang tiếng Việt (bản nháp)",
    "AI 想一下…": "AI đang nghĩ…",
    "還沒設定 AI 金鑰。": "Chưa thiết lập khoá AI.",
    "這是 AI 草稿，還沒存檔、學生也還看不到。": "Đây là bản nháp AI, chưa lưu và học viên chưa nhìn thấy.",
    "＋整體評語": "＋ Nhận xét chung",
    "已送出，等主管理員確認": "Đã gửi, chờ quản trị viên chính xác nhận",
    "已退回": "Đã trả lại",
    "送出失敗": "Gửi thất bại",
    "未設截止日": "Chưa đặt hạn nộp",
    "份未交": "bài chưa nộp",
    "全部未交": "Tất cả chưa nộp",
    "📋 複製提醒訊息": "📋 Sao chép tin nhắn nhắc",
    "📋 複製": "📋 Sao chép",
    "沒有逾期或快到期的作業 👍　（按「看全部未交」可以看其他的）": "Không có bài nào quá hạn hoặc sắp đến hạn 👍 (bấm “Xem tất cả chưa nộp” để xem thêm)",
    "· 七天內到期": "· Đến hạn trong 7 ngày",
    "💡 在課文的「發佈」裡設「截止日期」，這裡才會自動排出誰快遲交。": "💡 Đặt “Hạn nộp” trong phần “Đăng” của bài khoá thì ở đây mới tự xếp ra ai sắp trễ.",

    /* 繳費・對帳 */
    "計費單位": "Đơn vị tính phí",
    "計費方式": "Cách tính phí",
    "每小時": "Mỗi giờ",
    "每堂": "Mỗi buổi",
    "上課筆數": "Số buổi học",
    "付費日期": "Ngày thanh toán",
    "請選收款日期": "Vui lòng chọn ngày thu",
    "已記錄收款 ✓": "Đã ghi khoản thu ✓",
    "刪除這筆收款紀錄？": "Xoá khoản thu này?",
    "繳費收據": "Biên lai nộp phí",
    "月結單": "Bảng kê tháng",
    "對帳單": "Bảng đối chiếu",
    "對帳總表": "Bảng đối chiếu tổng hợp",
    "報價單": "Phiếu báo giá",
    "客戶": "Khách hàng",
    "面試練習繳費": "Phí luyện phỏng vấn",
    "要匯出哪幾張表？": "Xuất những bảng nào?",
    "每一堂一列，含這堂算多少錢": "Mỗi buổi một dòng, kèm số tiền của buổi đó",
    "每一筆收款一列": "Mỗi khoản thu một dòng",
    "全部（不限期間）": "Tất cả (không giới hạn kỳ)",
    "自己指定起訖日": "Tự chọn ngày bắt đầu và kết thúc",
    "至少要勾一張表": "Phải chọn ít nhất một bảng",
    "起日不能晚於迄日": "Ngày bắt đầu không được sau ngày kết thúc",
    "最早": "Sớm nhất",
    "已匯出": "Đã xuất",
    "筆資料": "mục dữ liệu",
    "還沒勾任何學生": "Chưa chọn học viên nào",
    "這個條件下沒有學生": "Không có học viên nào theo điều kiện này",
    "⚠ 學費未設定": "⚠ Chưa đặt học phí",
    "⚠ 未換算": "⚠ Chưa quy đổi",
    "✅ 結清": "✅ Đã thanh toán xong",
    "🟠 溢繳": "🟠 Nộp dư",
    "點一下切換：這位學生自己看不看得到費用": "Bấm để chuyển: học viên này có xem được học phí hay không",
    "👁 學生看得到": "👁 Học viên xem được",
    "🙈 學生看不到": "🙈 Học viên không xem được",
    "· 與": "· Chung với",
    "共用": "dùng chung",
    "🎟️ 已上": "🎟️ Đã học",
    "沒設「每堂多少錢」，所以算不出應收": "Chưa đặt “mỗi buổi bao nhiêu tiền” nên không tính được khoản phải thu",
    "這些不影響學生上課，但會讓你的堂數／收入統計不準，建議抽空修一修。": "Những mục này không ảnh hưởng việc học, nhưng làm thống kê số buổi / thu nhập sai lệch, nên tranh thủ sửa lại.",
    "去修正": "Đi sửa",
    "💰 收錢請到左邊選單的「💰 繳費」，所有學生（含團班）都在那一頁記。": "💰 Thu tiền vui lòng vào “💰 Nộp phí” ở menu bên trái, mọi học viên (kể cả lớp nhóm) đều ghi ở trang đó.",

    /* 留學業務・文件 */
    "代辦客戶": "Khách dịch vụ",
    "去代辦申請": "Đến hồ sơ dịch vụ",
    "申請文件清單": "Danh sách hồ sơ cần nộp",
    "還沒有文件清單": "Chưa có danh sách hồ sơ",
    "收到／寄出的日期": "Ngày nhận / gửi",
    "備註（選填）": "Ghi chú (không bắt buộc)",
    "刪掉這一列": "Xoá dòng này",
    "方向": "Chiều",
    "護照影本": "Bản sao hộ chiếu",
    "身分證影本": "Bản sao CCCD/CMND",
    "最高學歷畢業證書（經驗證）": "Bằng tốt nghiệp cao nhất (đã chứng thực)",
    "歷年成績單（經驗證）": "Bảng điểm các năm (đã chứng thực)",
    "中文或英文能力證明": "Chứng chỉ năng lực tiếng Trung hoặc tiếng Anh",
    "財力證明／存款證明": "Chứng minh tài chính / sổ tiết kiệm",
    "證件照（白底）": "Ảnh thẻ (nền trắng)",
    "讀書計畫": "Kế hoạch học tập",
    "健康檢查表": "Giấy khám sức khoẻ",
    "申請表（本人簽名）": "Đơn đăng ký (có chữ ký)",
    "填好的入學申請表": "Đơn nhập học đã điền",
    "學校錄取通知書": "Giấy báo trúng tuyển",
    "學校繳費單／收據": "Phiếu thu / biên lai của trường",
    "簽證面試需要的文件": "Hồ sơ cần cho phỏng vấn visa",
    "年 / 月 / 日": "Năm / Tháng / Ngày",
    "是 Có ／ 否 Không": "Có / Không",
    "填寫說明 / Hướng dẫn điền": "Hướng dẫn điền",
    "以上資料均為本人親自填寫，內容屬實。": "Tôi xin cam đoan những thông tin trên là do chính tôi điền và hoàn toàn đúng sự thật.",
    "清單是空的，先按「📋 帶入範本」或自己加幾列": "Danh sách đang trống, hãy bấm “📋 Dùng mẫu” hoặc tự thêm vài dòng",
    "列印日期": "Ngày in",
    "沒填日期的就是還沒收到／還沒寄出。": "Mục chưa có ngày là chưa nhận / chưa gửi.",
    "Word 檔已下載": "Đã tải tệp Word",
    "使用說明卡": "Thẻ hướng dẫn sử dụng",
    "練習題卷": "Phiếu bài luyện tập",
    "學習報告": "Báo cáo học tập",
    "結業證書": "Chứng chỉ hoàn thành",
    "🎓 留學業務": "🎓 Dịch vụ du học",
    "🧑‍🏫 教學": "🧑‍🏫 Giảng dạy",
    "👧 對方比我小": "👧 Người kia nhỏ tuổi hơn",
    "🧑 對方比我大": "🧑 Người kia lớn tuổi hơn",
    "🤝 平輩・不確定": "🤝 Ngang tuổi・không chắc",
    "叫對方 em，自己是 chị": "Gọi đối phương là em, mình là chị",
    "叫對方 anh／chị，自己是 em": "Gọi đối phương là anh/chị, mình là em",
    "用 bạn／mình": "Dùng bạn / mình",

    /* 回覆範本・價目表 */
    "有中文": "Có tiếng Trung",
    "沒有中文": "Không có tiếng Trung",
    "有越南文": "Có tiếng Việt",
    "沒有越南文": "Không có tiếng Việt",
    "沒有關鍵字": "Không có từ khoá",
    "還沒有內容——按「✏️ 編輯」把說法打進去": "Chưa có nội dung — bấm “✏️ Sửa” để nhập cách nói vào",
    "刪除這一份": "Xoá mẫu này",
    "📮 回覆客人": "📮 Trả lời khách",
    "一份": "một mẫu",
    "搜尋：語言學校、碩士、團班…": "Tìm: trường tiếng, thạc sĩ, lớp nhóm…",
    "符合": "khớp",
    "份還沒填內容": "mẫu chưa có nội dung",
    "把範本列印或存成 PDF，可以挑分類、語言和字體": "In mẫu hoặc lưu PDF, có thể chọn phân loại, ngôn ngữ và phông chữ",
    "還沒有任何範本": "Chưa có mẫu nào",
    "按「＋ 新增一份」建立，例如「申請語言學校費用」。": "Bấm “＋ Thêm một mẫu” để tạo, ví dụ “Phí đăng ký trường tiếng”.",
    "中文和越南文各存一份，之後客人一問就複製貼上。": "Lưu cả bản tiếng Trung và tiếng Việt, khách hỏi là sao chép dán ngay.",
    "＋ 新增一份": "＋ Thêm một mẫu",
    "＋ 新增一個項目": "＋ Thêm một hạng mục",
    "先把你的項目和單價設進去，": "Hãy đặt hạng mục và đơn giá của bạn vào trước,",
    "要一次把所有費用傳給客人，或是印一張留底，就用這兩顆": "Muốn gửi toàn bộ bảng phí cho khách hoặc in một bản lưu thì dùng hai nút này",
    "搬到只有主管理員讀得到的位置": "Chuyển đến nơi chỉ quản trị viên chính đọc được",

    /* 程度 */
    "入門": "Nhập môn", "基礎": "Cơ bản", "初階": "Sơ cấp",
    "進階": "Nâng cao", "高階": "Cao cấp", "流利": "Thành thạo", "精通": "Tinh thông",

    /* 設定・管理 */
    "＋ 新增管理員": "＋ Thêm quản trị viên",
    "請輸入 Email 與密碼": "Vui lòng nhập Email và mật khẩu",
    "Email 格式不正確": "Định dạng Email không đúng",
    "密碼不正確": "Mật khẩu không đúng",
    "系統預設": "Mặc định hệ thống",
    "寄測試通知": "Gửi thông báo thử",
    "你現在是": "Bạn hiện là",
    "聯絡：": "Liên hệ:",
    "🧪 測試": "🧪 Thử nghiệm",
    "發生錯誤": "Đã xảy ra lỗi",
    "存不進去": "Không lưu được",
    "只有主管理員可以做這個動作": "Chỉ quản trị viên chính mới làm được thao tác này",
    "資料還沒載入完，請稍候再試": "Dữ liệu chưa tải xong, vui lòng thử lại sau",
    "這個分頁顯示時發生問題": "Trang này gặp sự cố khi hiển thị",
    "請允許彈出視窗後再按一次": "Vui lòng cho phép cửa sổ bật lên rồi bấm lại",
    "標楷體 ＋ Times New Roman —— 標準": "Kaiti ＋ Times New Roman —— Tiêu chuẩn",
    "跟平台一樣": "Giống nền tảng",
    "已開放給學生 ✅": "Đã mở cho học viên ✅",
    "已對學生關閉": "Đã đóng với học viên",
    "跟原本一樣，沒有實際變動。": "Giống hệt bản gốc, không có thay đổi thực tế.",
    "改前": "Trước khi sửa",
    "改後": "Sau khi sửa",
    "剛剛讀的": "Vừa đọc",
    "分鐘前讀的": "phút trước đã đọc",
    "小時前讀的": "giờ trước đã đọc",
    "基本資料與學費": "Thông tin cơ bản và học phí",
    "基本資料與上課記錄": "Thông tin cơ bản và lịch sử buổi học",
    "每位學生的上課時段與 Meet 教室": "Giờ học và phòng Meet của từng học viên",
    "管理員 ·": "Quản trị viên ·",
    "越南名字不用打聲調——打 Luong 就找得到 Lương。": "Tên tiếng Việt không cần gõ dấu — gõ Luong là tìm được Lương.",
    "只列前 6 筆": "Chỉ hiện 6 mục đầu",
    "正在搬移中，請稍等…": "Đang chuyển dữ liệu, vui lòng đợi…",
    "沒有需要搬移的資料": "Không có dữ liệu cần chuyển",
    "搬移中…": "Đang chuyển…",

    /* ══ VI_V966 首頁拼出來的句子，一段一段 ══ */
    "今天沒有待批改的作業；另外有": "Hôm nay không có bài nào chờ chấm; ngoài ra có",
    "位學生的學費還沒收到。往下有「今天要處理」和「今天的課」。": "học viên chưa nộp học phí. Bên dưới có “Cần xử lý hôm nay” và “Buổi học hôm nay”.",
    "。往下有「今天要處理」和「今天的課」。": ". Bên dưới có “Cần xử lý hôm nay” và “Buổi học hôm nay”.",
    "，還有": ", còn",
    /* 繳費頁 */
    "還沒收": "Chưa thu",
    "✅ 都收齊了": "✅ Đã thu đủ",
    "＋ 記一筆": "＋ Ghi một khoản",
    "✅ 已處理": "✅ Đã xử lý",
    "人": "người"
  }
};
