/* QNA CHINESE — 教師後台介面越南文字典
   VI_V962 第一批：側邊選單、分頁、按鈕、表格欄位、狀態、常見提示。
   M = 整句完全相同才換；R = 帶數字的句型，用規則換。
   還沒收錄的句子會維持中文，不會變成空白或亂碼。
   有翻得不好的地方直接跟我說哪一句，我改這個檔案就好，不用動 teacher.html。 */
window.QNA_VI = {
  wave: 1,
  R: [
    ["^共 ?(\\d+(?:\\.\\d+)?) ?堂$", "Tổng $1 buổi"],
    ["^共 ?(\\d+) ?筆$", "Tổng $1 mục"],
    ["^共 ?(\\d+) ?題$", "Tổng $1 câu"],
    ["^共 ?(\\d+) ?課$", "Tổng $1 bài"],
    ["^(\\d+(?:\\.\\d+)?) ?小時$", "$1 giờ"],
    ["^(\\d+(?:\\.\\d+)?) ?堂$", "$1 buổi"],
    ["^(\\d+) ?題$", "$1 câu"],
    ["^(\\d+) ?課$", "$1 bài"],
    ["^(\\d+) ?筆$", "$1 mục"],
    ["^(\\d+) ?份$", "$1 bài"],
    ["^(\\d+) ?位$", "$1 người"],
    ["^(\\d+) ?人$", "$1 người"],
    ["^(\\d+) ?次$", "$1 lần"],
    ["^(\\d+) ?天$", "$1 ngày"],
    ["^(\\d+) ?個生詞$", "$1 từ vựng"],
    ["^(\\d+) ?位學生$", "$1 học viên"],
    ["^還剩 ?(\\d+) ?堂$", "Còn $1 buổi"],
    ["^逾期 ?(\\d+) ?天$", "Quá hạn $1 ngày"],
    ["^還有 ?(\\d+) ?天$", "Còn $1 ngày"],
    ["^已交 ?(\\d+)/(\\d+)$", "Đã nộp $1/$2"],
    ["^儲存失敗：([\\s\\S]*)$", "Lưu thất bại: $1"],
    ["^刪除失敗：([\\s\\S]*)$", "Xoá thất bại: $1"],
    ["^上傳失敗：([\\s\\S]*)$", "Tải lên thất bại: $1"],
    ["^下載失敗：([\\s\\S]*)$", "Tải xuống thất bại: $1"],
    ["^匯出失敗：([\\s\\S]*)$", "Xuất thất bại: $1"],
    ["^載入失敗：([\\s\\S]*)$", "Tải dữ liệu thất bại: $1"],
    ["^讀取失敗：([\\s\\S]*)$", "Đọc dữ liệu thất bại: $1"],
    ["^失敗：([\\s\\S]*)$", "Thất bại: $1"],
    ["^寄送失敗：([\\s\\S]*)$", "Gửi thất bại: $1"],
    ["^尚欠 ?(.+)$", "Còn nợ $1"],
    ["^欠 ?(.+)$", "Nợ $1"],
    ["^預繳 ?(.+)$", "Trả trước $1"],
    ["^應收 ?(.+)$", "Phải thu $1"],
    ["^已收 ?(.+)$", "Đã thu $1"],
    ["^本月收入（(.+)）$", "Thu nhập tháng này ($1)"],
    ["^最新 ?(\\d+) ?筆$", "$1 mục mới nhất"],
    ["^最近 ?(\\d+) ?筆，共 ?(\\d+) ?筆$", "$1 mục gần nhất, tổng $2 mục"],
    ["^還剩 ?(\\d+) ?堂$", "Còn $1 buổi"],
    ["^(\\d+) ?/ ?(\\d+)$", "$1 / $2"]
  ],
  M: {
    /* ── 側邊選單 ── */
    "今日總覽": "Tổng quan hôm nay",
    "學生": "Học viên",
    "課表": "Lịch học",
    "教材與課程": "Giáo trình & bài học",
    "批改・成績": "Chấm bài・Điểm",
    "課堂活動": "Hoạt động lớp",
    "留學業務": "Dịch vụ du học",
    "收費・財務": "Thu phí・Tài chính",
    "回覆範本": "Mẫu trả lời",
    "使用說明": "Hướng dẫn sử dụng",
    "設定": "Cài đặt",
    "⚙️ 設定": "⚙️ Cài đặt",
    "登出": "Đăng xuất",
    "登入": "Đăng nhập",
    "教　學": "GIẢNG DẠY",
    "業　務": "NGHIỆP VỤ",
    "其　他": "KHÁC",
    "主管理員後台": "Trang quản trị chính",
    "教師管理": "Quản lý giáo viên",
    "華語線上作業簿": "Sổ bài tập tiếng Trung trực tuyến",

    /* ── 通用按鈕 ── */
    "儲存": "Lưu",
    "💾 儲存": "💾 Lưu",
    "儲存中…": "Đang lưu…",
    "已儲存": "Đã lưu",
    "儲存失敗": "Lưu thất bại",
    "儲存失敗，請重試": "Lưu thất bại, vui lòng thử lại",
    "取消": "Huỷ",
    "關閉": "Đóng",
    "刪除": "Xoá",
    "已刪除": "Đã xoá",
    "刪除失敗": "Xoá thất bại",
    "移除": "Bỏ",
    "已移除": "Đã bỏ",
    "新增": "Thêm mới",
    "編輯": "Sửa",
    "✏️ 編輯": "✏️ Sửa",
    "✏️ 修改": "✏️ Chỉnh sửa",
    "完成": "Hoàn thành",
    "已完成": "Đã hoàn thành",
    "標記完成": "Đánh dấu hoàn thành",
    "失敗": "Thất bại",
    "建立": "Tạo",
    "＋ 建立": "＋ Tạo",
    "建立中…": "Đang tạo…",
    "已建立": "Đã tạo",
    "建立失敗": "Tạo thất bại",
    "更新失敗": "Cập nhật thất bại",
    "已更新": "Đã cập nhật",
    "預覽": "Xem trước",
    "👁 預覽": "👁 Xem trước",
    "處理中…": "Đang xử lý…",
    "載入中…": "Đang tải…",
    "上傳中…": "Đang tải lên…",
    "上傳中…（檔案大時請稍候）": "Đang tải lên… (tệp lớn vui lòng đợi)",
    "↻ 重新整理": "↻ Tải lại",
    "⬇ 下載": "⬇ Tải xuống",
    "⬆ 上傳圖片": "⬆ Tải ảnh lên",
    "⬆ 上傳音檔": "⬆ Tải tệp âm thanh lên",
    "⬆ 上傳 PDF": "⬆ Tải PDF lên",
    "⬇ 匯出 Excel": "⬇ Xuất Excel",
    "⬇ 下載完整備份": "⬇ Tải bản sao lưu đầy đủ",
    "全選 / 取消": "Chọn tất cả / Bỏ chọn",
    "✔ 全選在學中": "✔ Chọn tất cả đang học",
    "✕ 清除": "✕ Xoá trắng",
    "▾ 全部展開": "▾ Mở tất cả",
    "已選": "Đã chọn",
    "還沒選人": "Chưa chọn ai",
    "選填": "Không bắt buộc",
    "可以不填": "Có thể để trống",
    "全部": "Tất cả",
    "其他": "Khác",
    "列表": "Danh sách",
    "🖨 列印 / 存成 PDF": "🖨 In / Lưu PDF",
    "🖨 列印／PDF": "🖨 In / PDF",
    "列印時這排按鈕不會印出來": "Hàng nút này sẽ không được in ra",
    "語言": "Ngôn ngữ",
    "字體": "Phông chữ",
    "中文 ＋ Tiếng Việt": "中文 ＋ Tiếng Việt",
    "⋯ 更多": "⋯ Thêm",
    "沒有權限": "Không có quyền",
    "這個功能只有主管理員可以用": "Chức năng này chỉ quản trị viên chính mới dùng được",
    "只有主管理員可以用": "Chỉ quản trị viên chính mới dùng được",
    "主管理員": "Quản trị viên chính",
    "老師": "Giáo viên",
    "存不起來": "Không lưu được",
    "未連 Storage": "Chưa kết nối Storage",
    "複製失敗，請手動選取": "Sao chép thất bại, vui lòng bôi đen thủ công",
    "匯出元件還在載入，請過幾秒再按一次": "Công cụ xuất đang tải, vui lòng bấm lại sau vài giây",

    /* ── 學生・班級 ── */
    "姓名": "Họ tên",
    "姓名 *": "Họ tên *",
    "請填姓名": "Vui lòng nhập họ tên",
    "找不到這位學生": "Không tìm thấy học viên này",
    "還沒有學生": "Chưa có học viên",
    "全部學生": "Tất cả học viên",
    "位學生": "học viên",
    "團班": "Lớp nhóm",
    "一對一": "Học 1 kèm 1",
    "🧑‍🏫 一對一": "🧑‍🏫 Học 1 kèm 1",
    "👥 團班（尚未分班）": "👥 Lớp nhóm (chưa xếp lớp)",
    "班級": "Lớp",
    "課程型態": "Hình thức lớp",
    "國籍": "Quốc tịch",
    "電話": "Điện thoại",
    "電話／Zalo／LINE": "Điện thoại / Zalo / LINE",
    "聯絡方式": "Thông tin liên hệ",
    "基本資料": "Thông tin cơ bản",
    "📋 基本資料": "📋 Thông tin cơ bản",
    "備註": "Ghi chú",
    "換頭像": "Đổi ảnh đại diện",
    "← 回學生列表": "← Về danh sách học viên",
    "去學生頁": "Đến trang học viên",
    "合併帳戶": "Tài khoản gộp",
    "主管理員還沒有把學生分配給你。": "Quản trị viên chính chưa phân học viên cho bạn.",

    /* ── 就學狀態 ── */
    "在學中": "Đang học",
    "試學": "Học thử",
    "休學": "Tạm nghỉ",
    "已結案": "Đã kết thúc",
    "預約": "Đặt lịch",
    "預約中": "Đang hẹn",
    "預約・詢問中": "Đang hỏi・đặt lịch",

    /* ── 上課 ── */
    "上課": "Buổi học",
    "上課記錄": "Lịch sử buổi học",
    "🗓 上課記錄": "🗓 Lịch sử buổi học",
    "還沒有上課記錄": "Chưa có buổi học nào",
    "上課時段": "Giờ học",
    "上課日期": "Ngày học",
    "上課內容": "Nội dung buổi học",
    "課後小結": "Tóm tắt sau buổi học",
    "時段": "Khung giờ",
    "日期": "Ngày",
    "日期 *": "Ngày *",
    "請選日期": "Vui lòng chọn ngày",
    "月份": "Tháng",
    "今天": "Hôm nay",
    "明天": "Ngày mai",
    "填今天": "Điền hôm nay",
    "本月": "Tháng này",
    "最近": "Gần đây",
    "最新": "Mới nhất",
    "期間": "Kỳ",
    "未來": "Sắp tới",
    "開始": "Bắt đầu",
    "截止": "Hạn chót",
    "截止日期": "Hạn nộp",
    "期限": "Thời hạn",
    "沒設期限": "Chưa đặt thời hạn",
    "今天到期": "Hết hạn hôm nay",
    "逾期": "Quá hạn",
    "已過": "Đã qua",
    "快開始了": "Sắp bắt đầu",
    "出席": "Có mặt",
    "出席率": "Tỷ lệ đi học",
    "請假": "Nghỉ phép",
    "🏖 請假": "🏖 Nghỉ phép",
    "缺席": "Vắng mặt",
    "補課": "Học bù",
    "免費": "Miễn phí",
    "🎁 免費": "🎁 Miễn phí",
    "時數": "Số giờ",
    "小時": "giờ",
    "堂課": "buổi học",
    "狀態": "Trạng thái",
    "✍️ 去點名": "✍️ Điểm danh",
    "✅ 已點名": "✅ Đã điểm danh",
    "📌 預排": "📌 Đã xếp lịch",
    "🔁 固定時段": "🔁 Giờ cố định",
    "🔁 照上一週排下一週": "🔁 Xếp tuần sau theo tuần trước",
    "‹ 上個月": "‹ Tháng trước",
    "下個月 ›": "Tháng sau ›",
    "＋ 新增時段": "＋ Thêm khung giờ",
    "＋ 新增練習時間": "＋ Thêm buổi luyện tập",
    "排課中…": "Đang xếp lịch…",
    "刪掉這一堂": "Xoá buổi này",
    "線上教室：": "Lớp học trực tuyến:",
    "📝 記一堂課": "📝 Ghi một buổi học",
    "📌 排一堂課": "📌 Xếp một buổi học",
    "💬 寫回饋單": "💬 Viết phiếu nhận xét",

    /* ── 教材・課程 ── */
    "教材": "Giáo trình",
    "課程": "Khoá học",
    "課文": "Bài khoá",
    "課名": "Tên bài",
    "課名 *": "Tên bài *",
    "課序": "Thứ tự bài",
    "第幾課": "Bài số mấy",
    "標題": "Tiêu đề",
    "請填標題": "Vui lòng nhập tiêu đề",
    "內容": "Nội dung",
    "段落": "Đoạn",
    "小節": "Mục nhỏ",
    "小節（選填）": "Mục nhỏ (không bắt buộc)",
    "生詞": "Từ vựng",
    "生詞語法": "Từ vựng & ngữ pháp",
    "語法": "Ngữ pháp",
    "語法練習": "Luyện ngữ pháp",
    "屬於哪個語法點": "Thuộc điểm ngữ pháp nào",
    "例句": "Câu ví dụ",
    "對話": "Hội thoại",
    "對話一": "Hội thoại 1",
    "短文": "Đoạn văn",
    "原文": "Nguyên văn",
    "注釋": "Chú thích",
    "聽力": "Nghe hiểu",
    "發音": "Phát âm",
    "發音教材": "Giáo trình phát âm",
    "儲存發音課": "Lưu bài phát âm",
    "已上傳發音": "Đã tải lên phát âm",
    "▶ 試聽": "▶ Nghe thử",
    "此瀏覽器不支援錄音，請改用上傳": "Trình duyệt này không hỗ trợ ghi âm, vui lòng tải tệp lên",
    "文言文": "Văn ngôn",
    "📜 文言文": "📜 Văn ngôn",
    "講義": "Tài liệu phát",
    "📄 講義（PDF）": "📄 Tài liệu phát (PDF)",
    "作業": "Bài tập",
    "作業簿": "Sách bài tập",
    "📒 作業簿": "📒 Sách bài tập",
    "📒 挑作業": "📒 Chọn bài tập",
    "作業完成": "Bài tập đã xong",
    "作業成績": "Điểm bài tập",
    "完成作業": "Bài tập đã làm",
    "還沒做": "Chưa làm",
    "練習": "Luyện tập",
    "練習題": "Bài luyện tập",
    "課文練習": "Luyện bài khoá",
    "題庫練習": "Luyện ngân hàng đề",
    "造句": "Đặt câu",
    "課後問答": "Hỏi đáp sau buổi học",
    "問題與討論": "Câu hỏi & thảo luận",
    "隨堂小考": "Kiểm tra nhanh",
    "📝 隨堂小考": "📝 Kiểm tra nhanh",
    "小考": "Bài kiểm tra ngắn",
    "題目": "Câu hỏi",
    "題型": "Dạng câu hỏi",
    "小題": "Câu nhỏ",
    "選項": "Lựa chọn",
    "單選": "Chọn một",
    "填空": "Điền vào chỗ trống",
    "配對": "Nối",
    "重組": "Sắp xếp lại",
    "問答": "Hỏi đáp",
    "示範": "Ví dụ mẫu",
    "正確答案": "Đáp án đúng",
    "參考答案": "Đáp án tham khảo",
    "✅ 補參考答案": "✅ Bổ sung đáp án tham khảo",
    "找不到題庫": "Không tìm thấy ngân hàng đề",
    "這本還沒有課。": "Sách này chưa có bài nào.",
    "還沒有課文": "Chưa có bài khoá",
    "看拼音寫字": "Nhìn pinyin viết chữ",
    "看意思寫字": "Nhìn nghĩa viết chữ",
    "看字選意思": "Nhìn chữ chọn nghĩa",
    "看例句填生詞": "Nhìn câu ví dụ điền từ",
    "建立並編輯": "Tạo rồi sửa",
    "建立全部": "Tạo tất cả",
    "課標成完成": "Đánh dấu bài đã xong",
    "📢 發佈內容": "📢 Đăng nội dung",
    "👥 發佈": "👥 Đăng",
    "已發佈": "Đã đăng",
    "學生會看到": "Học viên sẽ nhìn thấy",
    "學生現在看不到": "Hiện học viên chưa nhìn thấy",
    "所有學生登入首頁都會看到": "Mọi học viên đăng nhập vào trang chủ đều nhìn thấy",
    "📌 套用到全班學生": "📌 Áp dụng cho cả lớp",
    "儲存成員": "Lưu thành viên",
    "🖥 上課投影片": "🖥 Slide bài giảng",

    /* ── 批改 ── */
    "批改": "Chấm bài",
    "去批改": "Đi chấm bài",
    "待批改": "Chờ chấm",
    "已交": "Đã nộp",
    "作答中": "Đang làm",
    "未開始": "Chưa bắt đầu",
    "分數": "Điểm",
    "平均": "Trung bình",
    "答對率": "Tỷ lệ đúng",
    "百分比": "Phần trăm",
    "✓ 對": "✓ Đúng",
    "✗ 錯": "✗ Sai",
    "整體評語": "Nhận xét chung",
    "整體鼓勵或建議…": "Lời động viên hoặc góp ý chung…",
    "給這一題的建議（學生會看到）": "Góp ý cho câu này (học viên sẽ thấy)",
    "儲存建議": "Lưu góp ý",
    "💾 儲存建議": "💾 Lưu góp ý",
    "已儲存建議": "Đã lưu góp ý",
    "已批改，學生可看到建議": "Đã chấm, học viên xem được góp ý",
    "已改回進行中": "Đã chuyển lại thành đang tiến hành",
    "目前沒有待批改的項目 🎉": "Hiện không có mục nào chờ chấm 🎉",
    "老師的話": "Lời của giáo viên",
    "這個月的進步": "Tiến bộ trong tháng",
    "謝謝你這段時間的努力 ♡": "Cảm ơn em đã cố gắng trong thời gian qua ♡",
    "開口說": "Luyện nói",
    "專心度": "Mức độ tập trung",
    "上課回饋單": "Phiếu nhận xét buổi học",
    "月總結": "Tổng kết tháng",
    "📄 學習報告": "📄 Báo cáo học tập",

    /* ── 財務 ── */
    "繳費": "Nộp phí",
    "💰 繳費": "💰 Nộp phí",
    "💰 記繳費": "💰 Ghi nộp phí",
    "💰 記一筆收款": "💰 Ghi một khoản thu",
    "繳費記錄": "Lịch sử nộp phí",
    "學費": "Học phí",
    "未設學費": "Chưa đặt học phí",
    "計費": "Tính phí",
    "單價": "Đơn giá",
    "沒填單價": "Chưa điền đơn giá",
    "沒設單價": "Chưa đặt đơn giá",
    "金額": "Số tiền",
    "金額 *": "Số tiền *",
    "請填金額": "Vui lòng nhập số tiền",
    "合計": "Tổng cộng",
    "數量": "Số lượng",
    "幣別": "Loại tiền",
    "總費用幣別": "Loại tiền của tổng phí",
    "臺幣 NT$": "Đài tệ NT$",
    "美元 US$": "Đô la Mỹ US$",
    "越南盾 VND": "Việt Nam Đồng VND",
    "越南盾 VND（打千位）": "Việt Nam Đồng VND (nhập theo nghìn)",
    "越南盾打千位": "VND nhập theo nghìn",
    "VND 千": "VND nghìn",
    "折合帳單幣別": "Quy đổi sang loại tiền của hoá đơn",
    "未換算": "Chưa quy đổi",
    "付款日": "Ngày thanh toán",
    "收款日期 *": "Ngày thu *",
    "收款方式": "Hình thức thu",
    "💳 收款帳號": "💳 Tài khoản nhận tiền",
    "帳號": "Tài khoản",
    "應收": "Phải thu",
    "已收": "Đã thu",
    "已繳": "Đã nộp",
    "· 已繳": "· Đã nộp",
    "尚欠": "Còn nợ",
    "預繳": "Trả trước",
    "結餘": "Số dư",
    "已結清": "Đã thanh toán xong",
    "✅ 已結清": "✅ Đã thanh toán xong",
    "累計": "Luỹ kế",
    "累計應收": "Tổng phải thu",
    "累計實收": "Tổng đã thu",
    "累計收入": "Thu nhập luỹ kế",
    "還沒收到": "Chưa nhận được",
    "🔴 還沒收": "🔴 Chưa thu",
    "🧾 目前應收：": "🧾 Phải thu hiện tại:",
    "已處理": "Đã xử lý",
    "退費單": "Phiếu hoàn phí",
    "價目表": "Bảng giá",
    "價目表還是空的": "Bảng giá vẫn trống",
    "名稱": "Tên",
    "項目": "Hạng mục",
    "類別": "Phân loại",
    "💰 開一張報價單": "💰 Lập một phiếu báo giá",
    "📊 匯出對帳資料": "📊 Xuất dữ liệu đối chiếu",
    "收入會併進「營運 → 🧮 總收入」。": "Khoản thu sẽ được gộp vào “Vận hành → 🧮 Tổng thu nhập”.",

    /* ── 留學業務 ── */
    "留學代辦": "Dịch vụ du học",
    "代辦": "Dịch vụ",
    "代辦申請": "Hồ sơ dịch vụ",
    "代書": "Viết hồ sơ thuê",
    "文件代寫": "Viết hồ sơ",
    "申請學校": "Trường ứng tuyển",
    "學校": "Trường",
    "客戶資料": "Thông tin khách hàng",
    "看客戶": "Xem khách hàng",
    "刪除這位客戶": "Xoá khách hàng này",
    "文件名稱": "Tên hồ sơ",
    "入學申請資料表": "Phiếu thông tin nhập học",
    "自傳": "Bài tự giới thiệu",
    "推薦信": "Thư giới thiệu",
    "修改讀書計畫": "Sửa kế hoạch học tập",
    "承辦人": "Người phụ trách",
    "階段": "Giai đoạn",
    "進度": "Tiến độ",
    "＋ 新增一筆進度": "＋ Thêm một mốc tiến độ",
    "交件": "Nộp hồ sơ",
    "還缺": "Còn thiếu",
    "這一本還缺": "Phần này còn thiếu",
    "📄 正式案件": "📄 Hồ sơ chính thức",
    "✕ 沒談成": "✕ Không chốt được",
    "面試": "Phỏng vấn",
    "面試日": "Ngày phỏng vấn",
    "面試練習": "Luyện phỏng vấn",
    "🎤 面試練習": "🎤 Luyện phỏng vấn",
    "🎯 正式面試": "🎯 Phỏng vấn chính thức",
    "面試目標": "Mục tiêu phỏng vấn",
    "✅ 通過": "✅ Đạt",
    "❌ 沒通過": "❌ Không đạt",
    "📎 上傳／查看檔案": "📎 Tải lên / xem tệp",
    "📤 上傳區": "📤 Khu tải lên",
    "檔案": "Tệp",
    "個檔案": "tệp",
    "📋 提醒訊息": "📋 Tin nhắn nhắc nhở",
    "📄 報告與證書": "📄 Báo cáo & chứng chỉ",
    "✉️ 聯絡與提醒": "✉️ Liên hệ & nhắc nhở",
    "📁 檔案與紀錄": "📁 Tệp & hồ sơ",
    "📌 其他": "📌 Khác",
    "＋ 記下來": "＋ Ghi lại",
    "待處理": "Chờ xử lý",
    "目前": "Hiện tại",
    "中文": "Tiếng Trung",
    "說明": "Hướng dẫn",
    "類型": "Loại",
    "開立時間": "Thời gian lập",
    "華語教學 · 留學代辦": "Dạy tiếng Trung · Dịch vụ du học",
    "中文課 ·": "Lớp tiếng Trung ·",
    "手寫": "Viết tay",
    "還有": "Còn",
    "都可以": "Đều được",
    "換上面的分類看看。": "Thử đổi phân loại ở trên xem.",
    "還沒到（今天是": "Chưa đến (hôm nay là",
    "例：Nguyễn Văn A": "Ví dụ: Nguyễn Văn A",
    "例：500": "Ví dụ: 500",
    "例：A、B": "Ví dụ: A, B",
    "選填。填了才會算「還差多少」": "Không bắt buộc. Điền vào mới tính được “còn thiếu bao nhiêu”",
    "選填，會在「待辦」提醒": "Không bắt buộc, sẽ nhắc ở mục “Việc cần làm”",
    "📧 有人報名時通知我": "📧 Báo cho tôi khi có người đăng ký",
    "第 1 步": "Bước 1",
    "第 2 步": "Bước 2",
    "學生名單": "Danh sách học viên",
    "👥 學生名單": "👥 Danh sách học viên",
    "團班每位學生各自繳自己的。": "Mỗi học viên trong lớp nhóm tự đóng phần của mình.",
    "成員": "Thành viên",
    "成員／時段": "Thành viên / Giờ học",
    "班級資訊": "Thông tin lớp",
    "課程模組": "Mô-đun bài học",
    "繳交狀況": "Tình hình nộp bài",
    "🗓 上課點名": "🗓 Điểm danh buổi học",
    "🖨 班級總覽": "🖨 Tổng quan lớp",
    "📤 匯出這班的學生": "📤 Xuất học viên lớp này",
    "已上課": "Đã học",
    "下次上課": "Buổi học kế tiếp",
    "還沒排": "Chưa xếp lịch",
    "還沒點過名": "Chưa điểm danh lần nào",
    "已上": "Đã học",
    "目前結餘": "Số dư hiện tại",
    "還沒開始上課": "Chưa bắt đầu học",
    "還沒設定學費": "Chưa đặt học phí",
    "沒設單價": "Chưa đặt đơn giá",
    "總覽": "Tổng quan",
    "📝 記一堂課": "📝 Ghi một buổi học",
    "📋 週報": "📋 Báo cáo tuần",
    "💰 收款": "💰 Thu tiền",
    "📤 匯出": "📤 Xuất dữ liệu",
    "🎥 教室": "🎥 Phòng học",
    "📁 資料夾": "📁 Thư mục",
    "⋯ 更多工具": "⋯ Công cụ khác",
    "🔎 完整檔案": "🔎 Hồ sơ đầy đủ",
    "📄 檔案卡": "📄 Thẻ hồ sơ",
    "🧾 對帳單": "🧾 Bảng đối chiếu",
    "＋ 記一堂課": "＋ Ghi một buổi học",
    "＋ 記一筆繳費": "＋ Ghi một khoản nộp phí",
    "還沒有繳費記錄。": "Chưa có lịch sử nộp phí.",
    "還沒有繳費記錄": "Chưa có lịch sử nộp phí",
    "還沒有成員": "Chưa có thành viên",
    "收款金額": "Số tiền đã thu",
    "這個分頁只有主管理員看得到。": "Trang này chỉ quản trị viên chính mới xem được.",
    "沒設單價": "Chưa đặt đơn giá",
    "待辦": "Việc cần làm",
    "今天要處理": "Cần xử lý hôm nay",
    "今天的課": "Buổi học hôm nay",
    "備忘": "Ghi nhớ",
    "本月收入": "Thu nhập tháng này",
    "尚未收款": "Chưa thu tiền",
    "堂數快用完": "Sắp hết số buổi",
    "費用明細": "Chi tiết thu chi",
    "華語教學": "Dạy tiếng Trung",
    "營運": "Vận hành",
    "🧮 總收入": "🧮 Tổng thu nhập"
  }
};
